package com.cretas.aims.dto.approval;

import com.cretas.aims.entity.config.ApprovalChainConfig.DecisionType;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * 创建审批链配置请求 DTO (Rule 17.1 cleanup — Issue #384 batch 6 final).
 *
 * <p>替代 {@code @RequestBody ApprovalChainConfig} 实体直绑模式. 隔离 wire contract
 * 与 {@link com.cretas.aims.entity.config.ApprovalChainConfig} 持久化模型 — 防止
 * {@code @Builder.Default} 字段 ({@code requiredApprovers = 1}, {@code priority = 0},
 * {@code enabled = true}, {@code version = 1}) 通过 {@code @NoArgsConstructor} 字段
 * 初始化器在 Jackson 反序列化时静默写入, 进而隐式覆盖客户端意图.
 *
 * <p>Auto-managed by service / DB:
 * <ul>
 *   <li>{@code id} — generated by Hibernate UUID2 strategy</li>
 *   <li>{@code factoryId} — overridden by {@code @PathVariable} in
 *       {@code ApprovalChainServiceImpl.createConfig}</li>
 *   <li>{@code requiredApprovers} default 1 — applied by service when null</li>
 *   <li>{@code priority} default 0 — applied by service when null</li>
 *   <li>{@code enabled} default true — applied by service when null</li>
 *   <li>{@code version} default 1 — applied by service when null</li>
 *   <li>{@code createdAt}, {@code updatedAt}, {@code deletedAt} — BaseEntity-managed</li>
 * </ul>
 *
 * <p>Also serves as wire contract for {@code POST /approval-chains/validate}
 * (which exercises the same validation pipeline without persisting).
 *
 * @see com.cretas.aims.entity.config.ApprovalChainConfig
 * @see <a href="https://github.com/j4xie/my-prototype-logistics/issues/384">Issue #384 Rule 17.1 batch 6</a>
 * @since 2026-05-11
 */
@Data
@Schema(description = "创建审批链配置请求")
public class CreateApprovalChainConfigRequest {

    @Schema(description = "决策类型", example = "QUALITY_RELEASE",
            requiredMode = Schema.RequiredMode.REQUIRED)
    @NotNull(message = "决策类型不能为空")
    private DecisionType decisionType;

    @Schema(description = "配置名称", example = "一级审批 - 质量放行",
            requiredMode = Schema.RequiredMode.REQUIRED)
    @NotBlank(message = "配置名称不能为空")
    @Size(max = 100, message = "配置名称长度不能超过100个字符")
    private String name;

    @Schema(description = "配置描述")
    @Size(max = 500, message = "配置描述长度不能超过500个字符")
    private String description;

    @Schema(description = "触发条件 (JSON 字符串)",
            example = "{\"impactLevel\":\"HIGH\",\"delayMinutes\":\">60\"}")
    private String triggerCondition;

    @Schema(description = "审批级别 (1=一级审批, 2=二级审批, ...)",
            example = "1", requiredMode = Schema.RequiredMode.REQUIRED)
    @NotNull(message = "审批级别不能为空")
    @Min(value = 1, message = "审批级别必须大于0")
    private Integer approvalLevel;

    @Schema(description = "必需审批人数, 不传时由服务端默认 1", example = "1")
    @Min(value = 1, message = "必需审批人数必须大于0")
    private Integer requiredApprovers;

    @Schema(description = "可审批角色列表 (JSON 数组)",
            example = "[\"factory_super_admin\",\"department_admin\"]")
    private String approverRoles;

    @Schema(description = "可审批用户ID列表 (JSON 数组, 可选)", example = "[1,2,3]")
    private String approverUserIds;

    @Schema(description = "超时时间 (分钟)", example = "120")
    private Integer timeoutMinutes;

    @Schema(description = "超时后升级到的配置ID")
    @Size(max = 36, message = "升级配置ID长度不能超过36个字符")
    private String escalationConfigId;

    @Schema(description = "自动审批条件 (JSON 字符串)")
    private String autoApproveCondition;

    @Schema(description = "自动拒绝条件 (JSON 字符串)")
    private String autoRejectCondition;

    @Schema(description = "优先级 (数值越大优先级越高), 不传时由服务端默认 0", example = "0")
    private Integer priority;

    @Schema(description = "是否启用, 不传时由服务端默认 true", example = "true")
    private Boolean enabled;
}
