-- Sprint 2 Track E (S-MRP-1 / N31): 销售订单缺料分析报告快照
-- 由 SalesOrderShortageReportListener (@Async @EventListener) 在
-- SalesOrderFinanceApprovedEvent 发布后异步写入。
-- 数据由 ShortageAnalysisService 生成 (read-only orchestrate 4 个现有 service)。

CREATE TABLE sales_order_shortage_report (
    id VARCHAR(36) PRIMARY KEY,  -- generated by JPA @PrePersist (UUID.randomUUID())
    factory_id VARCHAR(36) NOT NULL,
    sales_order_id VARCHAR(36) NOT NULL,

    -- PENDING (placeholder pre-analysis) / COMPLETED (analysis ok) / FAILED (exception)
    analysis_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    -- BOM 原料需求 (List<MaterialRequirement>) — 对所有 FG 缺口展开后聚合
    total_required JSONB,

    -- FG 库存匹配结果 (List<LineItemMatch>) — 每行: required/available/shortfall
    available JSONB,

    -- BOM 原料短缺 (List<MaterialShortfall>) — 驱动采购建议
    shortage JSONB,

    -- List<ProcurementSuggestion> — 建议供应商/单价/leadDays/三价
    procurement_suggestions JSONB,

    -- List<ProductionPlanSuggestion> — 工序链/计划起止
    production_suggestions JSONB,

    -- 人类可读摘要 (AIChat 文字回复 / 钉钉卡片标题)
    analysis_summary TEXT,

    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMP NULL
);

-- 查询热路径: (factory_id, sales_order_id) 唯一 — 一单一报告 (最新覆盖旧)
CREATE INDEX idx_sosr_factory_sales ON sales_order_shortage_report (factory_id, sales_order_id) WHERE deleted_at IS NULL;

-- AIChat / 列表场景按 factory + status 过滤
CREATE INDEX idx_sosr_factory_status ON sales_order_shortage_report (factory_id, analysis_status) WHERE deleted_at IS NULL;

COMMENT ON TABLE sales_order_shortage_report IS 'Sprint 2 Track E (S-MRP-1 / N31): 销售订单缺料分析报告快照。由 SalesOrderShortageReportListener 在财务审核通过后异步生成。';
