-- V20260430_01__phase2a_test_factory_F999.sql
-- Phase 2A test factory: enables F999 to receive JWT and serve byte-shape goldens for /alerts and other Phase 2A endpoints.
-- Copies F001's smart_bi_*_data seed via INSERT ... SELECT (DEMO_FACTORY data does not exist; spec rev for F001 source).
-- See docs/adr/2026-04-29-phase2a-synthetic-test-factory-f999.md for rationale (ADR pending).

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. FACTORY (idempotent via ON CONFLICT (id) DO NOTHING)
-- ─────────────────────────────────────────────────────────────────────────────
-- type: FACTORY is the only correct enum value for a standalone food-processing
--       factory (options: FACTORY, RESTAURANT, HEADQUARTERS, BRANCH, CENTRAL_KITCHEN).
-- level: 0 = independent / top-level (no parent).
-- ai_weekly_quota, is_active, manually_verified: all NOT NULL per BaseEntity and
--   entity field definitions.
INSERT INTO factories (
    id,
    name,
    type,
    level,
    address,
    industry,
    is_active,
    manually_verified,
    ai_weekly_quota,
    created_at,
    updated_at
)
VALUES (
    'F999',
    'Phase2A 合成测试工厂',
    'FACTORY',
    0,
    '测试环境',
    '食品加工',
    true,
    false,
    20,
    NOW(),
    NOW()
)
ON CONFLICT (id) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. USER (idempotent via ON CONFLICT (username) DO NOTHING)
-- ─────────────────────────────────────────────────────────────────────────────
-- role_code: 'factory_super_admin' is a valid FactoryUserRole enum value (level 0,
--   gives full factory permissions — needed for golden-recording JWT requests).
-- password_hash: ${PHASE2A_TEST_USER_PASSWORD_HASH} is a Flyway placeholder.
--   Flyway substitutes from spring.flyway.placeholders.PHASE2A_TEST_USER_PASSWORD_HASH.
--   - application-pg.properties (test):     reads from env var PHASE2A_TEST_USER_PASSWORD_HASH
--                                            (set in /www/wwwroot/cretas/.env.test on server)
--   - application-pg-prod.properties (prod): hardcoded literal "DISABLED" so login always fails.
--   Plaintext password kept in PHASE2A_TEST_USER_PASSWORD env var (recorder reads it, not committed).
-- platform_type: 'web,mobile' allows both web-admin and mobile app login.
INSERT INTO users (
    factory_id,
    username,
    password_hash,
    full_name,
    role_code,
    is_active,
    platform_type,
    created_at,
    updated_at
)
VALUES (
    'F999',
    'phase2a_test_user',
    '${PHASE2A_TEST_USER_PASSWORD_HASH}',
    'Phase2A 测试用户',
    'factory_super_admin',
    true,
    'web,mobile',
    NOW(),
    NOW()
)
ON CONFLICT (username) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. smart_bi_sales_data: copy from F001 (idempotent guard)
-- ─────────────────────────────────────────────────────────────────────────────
-- Column list matches V2026_01_18_02__smart_bi_sample_data.sql INSERT verbatim
-- (factory_id substituted to 'F999'; id excluded — auto-generated by sequence;
--  created_at / updated_at set to NOW() for freshness).
-- Idempotent: outer DO block skips the INSERT if F999 rows already exist.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM smart_bi_sales_data WHERE factory_id = 'F999' LIMIT 1
    ) THEN
        INSERT INTO smart_bi_sales_data (
            factory_id,
            order_date,
            salesperson_id,
            salesperson_name,
            department,
            region,
            province,
            city,
            customer_name,
            customer_type,
            product_id,
            product_name,
            product_category,
            quantity,
            amount,
            unit_price,
            cost,
            profit,
            gross_margin,
            monthly_target,
            created_at,
            updated_at
        )
        SELECT
            'F999',
            order_date,
            salesperson_id,
            salesperson_name,
            department,
            region,
            province,
            city,
            customer_name,
            customer_type,
            product_id,
            product_name,
            product_category,
            quantity,
            amount,
            unit_price,
            cost,
            profit,
            gross_margin,
            monthly_target,
            NOW(),
            NOW()
        FROM smart_bi_sales_data
        WHERE factory_id = 'F001'
          AND deleted_at IS NULL;
    END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. smart_bi_finance_data: copy from F001 (idempotent guard)
-- ─────────────────────────────────────────────────────────────────────────────
-- The finance table stores 4 record_types (COST, AR, AP, BUDGET) with
-- partially overlapping column sets. All columns are nullable except:
--   factory_id, record_date, record_type (NOT NULL / ENUM).
-- We copy the full row superset so each record_type's relevant columns transfer.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM smart_bi_finance_data WHERE factory_id = 'F999' LIMIT 1
    ) THEN
        INSERT INTO smart_bi_finance_data (
            factory_id,
            record_date,
            record_type,
            department,
            category,
            customer_name,
            supplier_name,
            material_cost,
            labor_cost,
            overhead_cost,
            total_cost,
            receivable_amount,
            collection_amount,
            aging_days,
            payable_amount,
            payment_amount,
            budget_amount,
            actual_amount,
            variance_amount,
            due_date,
            created_at,
            updated_at
        )
        SELECT
            'F999',
            record_date,
            record_type,
            department,
            category,
            customer_name,
            supplier_name,
            material_cost,
            labor_cost,
            overhead_cost,
            total_cost,
            receivable_amount,
            collection_amount,
            aging_days,
            payable_amount,
            payment_amount,
            budget_amount,
            actual_amount,
            variance_amount,
            due_date,
            NOW(),
            NOW()
        FROM smart_bi_finance_data
        WHERE factory_id = 'F001'
          AND deleted_at IS NULL;
    END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. smart_bi_department_data: copy from F001 (idempotent guard)
-- ─────────────────────────────────────────────────────────────────────────────
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM smart_bi_department_data WHERE factory_id = 'F999' LIMIT 1
    ) THEN
        INSERT INTO smart_bi_department_data (
            factory_id,
            record_date,
            department,
            department_id,
            manager_name,
            headcount,
            sales_amount,
            sales_target,
            cost_amount,
            per_capita_sales,
            per_capita_cost,
            created_at,
            updated_at
        )
        SELECT
            'F999',
            record_date,
            department,
            department_id,
            manager_name,
            headcount,
            sales_amount,
            sales_target,
            cost_amount,
            per_capita_sales,
            per_capita_cost,
            NOW(),
            NOW()
        FROM smart_bi_department_data
        WHERE factory_id = 'F001'
          AND deleted_at IS NULL;
    END IF;
END $$;
