-- V20260409_02__seed_sales_order_bom_schema.sql
-- Canvas Config Phase 1: Seed module_schemas for sales_order + bom

INSERT INTO module_schemas (module_code, module_name, module_category, module_version,
    field_schema, workflow_schema, validation_schema, permission_schema, default_config, description)
VALUES (
    'sales_order', '销售订单', 'SALES', 1,
    -- field_schema
    '{"fields":[{"code":"orderNumber","label":"订单号","type":"string","required":true,"configurable":false,"autoGenerate":true,"listVisible":true,"listOrder":1,"listWidth":150,"group":"basic"},{"code":"customerId","label":"客户","type":"reference","required":true,"configurable":false,"referenceConfig":{"entity":"customer","displayField":"name","valueField":"id","apiEndpoint":"/api/mobile/{factoryId}/customers"},"listVisible":true,"listOrder":2,"listWidth":140,"group":"basic"},{"code":"orderDate","label":"下单日期","type":"date","required":true,"configurable":false,"defaultValue":"TODAY","listVisible":true,"listOrder":3,"listWidth":120,"group":"basic"},{"code":"requiredDeliveryDate","label":"要求交货日期","type":"date","required":false,"configurable":true,"defaultVisible":true,"listVisible":true,"listOrder":4,"listWidth":120,"group":"basic"},{"code":"salesperson","label":"业务员","type":"string","required":false,"configurable":true,"defaultVisible":true,"group":"basic"},{"code":"remark","label":"备注","type":"textarea","required":false,"configurable":true,"defaultVisible":true,"group":"basic"},{"code":"totalAmount","label":"订单总金额","type":"decimal","required":false,"configurable":false,"computed":"SUM(items[].lineAmount)","readonly":true,"listVisible":true,"listOrder":5,"listWidth":120,"formatter":"currency","group":"amounts"},{"code":"shippingIncluded","label":"是否含运费","type":"boolean","required":false,"configurable":true,"defaultVisible":true,"defaultValue":false,"group":"费用"},{"code":"shippingFee","label":"运费","type":"decimal","required":false,"configurable":true,"defaultVisible":true,"min":0,"dependsOn":{"field":"shippingIncluded","value":true},"group":"费用"},{"code":"extraFees","label":"其他费用","type":"json_array","required":false,"configurable":true,"defaultVisible":true,"itemSchema":{"fields":[{"code":"name","type":"string","label":"费用名","required":true},{"code":"amount","type":"decimal","label":"金额","required":true,"min":0},{"code":"remark","type":"string","label":"备注","required":false}]},"group":"费用"},{"code":"boxQuantity","label":"下单箱数","type":"decimal","required":false,"configurable":true,"defaultVisible":true,"min":0,"group":"basic"},{"code":"status","label":"状态","type":"select","required":false,"configurable":false,"readonly":true,"listVisible":true,"listOrder":6,"listWidth":100,"group":"basic"}],"groups":[{"code":"basic","label":"基本信息","order":1},{"code":"items","label":"订单明细","order":2},{"code":"amounts","label":"金额汇总","order":3},{"code":"费用","label":"运费与其他费用","order":4},{"code":"business","label":"业务中心","order":5}]}'::jsonb,
    -- workflow_schema
    '{"states":[{"code":"DRAFT","label":"草稿","isInitial":true,"tagType":"info"},{"code":"CONFIRMED","label":"已确认","tagType":""},{"code":"PENDING_FINANCE_REVIEW","label":"待财务审核","configurable":true,"tagType":"warning"},{"code":"FINANCE_APPROVED","label":"财务已审核","configurable":true,"tagType":"success"},{"code":"PROCESSING","label":"生产中","tagType":""},{"code":"PARTIAL_DELIVERED","label":"部分发货","tagType":"warning"},{"code":"SHIPPED","label":"已发货","tagType":"success"},{"code":"COMPLETED","label":"已完成","isFinal":true,"tagType":"success"},{"code":"CANCELLED","label":"已取消","isFinal":true,"tagType":"danger"}],"transitions":[{"from":"DRAFT","to":"CONFIRMED","action":"confirm","label":"确认订单","buttonType":"primary"},{"from":"CONFIRMED","to":"PENDING_FINANCE_REVIEW","action":"submitForReview","label":"提交审核","buttonType":"warning","configurable":true},{"from":"PENDING_FINANCE_REVIEW","to":"FINANCE_APPROVED","action":"approveFinance","label":"审核通过","buttonType":"success","configurable":true},{"from":"CONFIRMED","to":"PROCESSING","action":"startProduction","label":"开始生产","buttonType":"primary","condition":"!config.workflow.hasFinanceReview"},{"from":"FINANCE_APPROVED","to":"PROCESSING","action":"startProduction","label":"开始生产","buttonType":"primary"},{"from":"PROCESSING","to":"SHIPPED","action":"ship","label":"确认发货","buttonType":"success"},{"from":"SHIPPED","to":"COMPLETED","action":"complete","label":"完成","buttonType":"success"},{"from":"DRAFT","to":"CANCELLED","action":"cancel","label":"取消","buttonType":"danger"},{"from":"CONFIRMED","to":"CANCELLED","action":"cancel","label":"取消","buttonType":"danger"}],"options":{"hasFinanceReview":{"type":"boolean","label":"启用财务审核","default":true,"configurable":true},"allowPartialDelivery":{"type":"boolean","label":"允许部分发货","default":true,"configurable":true}}}'::jsonb,
    -- validation_schema
    '{"rules":[{"code":"DUPLICATE_PRODUCT_CHECK","label":"同产品重复校验","enabled":true,"configurable":true},{"code":"MIN_ORDER_AMOUNT","label":"最低订单金额","enabled":false,"configurable":true,"params":{"minAmount":100}}]}'::jsonb,
    -- permission_schema
    '{"roles":["factory_super_admin","sales_manager","sales_staff","finance","warehouse","viewer"],"fieldPermissions":[{"fieldCode":"totalAmount","permissions":{"factory_super_admin":"edit","sales_manager":"edit","sales_staff":"view","finance":"view","warehouse":"hidden","viewer":"view"}},{"fieldCode":"shippingFee","permissions":{"factory_super_admin":"edit","sales_manager":"edit","sales_staff":"edit","finance":"view","warehouse":"hidden","viewer":"hidden"}}]}'::jsonb,
    -- default_config
    '{"fields":{},"workflow":{"options":{"hasFinanceReview":true,"allowPartialDelivery":true}}}'::jsonb,
    '销售订单模块: 包含订单创建/确认/审核/发货/完成全流程, 支持税率分组开票'
)
ON CONFLICT (module_code) DO NOTHING;

INSERT INTO module_schemas (module_code, module_name, module_category, module_version,
    field_schema, workflow_schema, validation_schema, permission_schema, default_config, description)
VALUES (
    'bom', 'BOM配方', 'PRODUCTION', 1,
    '{"fields":[{"code":"productTypeId","label":"产品(成品)","type":"reference","required":true,"configurable":false,"referenceConfig":{"entity":"productType","displayField":"name","valueField":"id","apiEndpoint":"/api/mobile/{factoryId}/finished-goods/product-types"},"listVisible":true,"listOrder":1,"listWidth":160,"group":"basic"},{"code":"materialTypeId","label":"原辅料","type":"reference","required":true,"configurable":false,"referenceConfig":{"entity":"materialType","displayField":"name","valueField":"id","apiEndpoint":"/api/mobile/{factoryId}/material-types"},"listVisible":true,"listOrder":2,"listWidth":160,"group":"basic"},{"code":"materialCategory","label":"物料分类","type":"select","required":true,"configurable":true,"defaultVisible":true,"options":[{"value":"RAW","label":"原料"},{"value":"AUXILIARY","label":"辅料"},{"value":"PACKAGING","label":"包材"}],"defaultValue":"RAW","listVisible":true,"listOrder":3,"listWidth":100,"group":"basic"},{"code":"standardQuantity","label":"标准用量","type":"decimal","required":true,"configurable":false,"min":0.0001,"precision":4,"listVisible":true,"listOrder":4,"listWidth":120,"group":"dosage"},{"code":"unit","label":"计量单位","type":"select","required":true,"configurable":true,"options":[{"value":"kg","label":"公斤"},{"value":"g","label":"克"},{"value":"piece","label":"个"},{"value":"pack","label":"包"}],"defaultValue":"kg","listVisible":true,"listOrder":5,"listWidth":80,"group":"dosage"},{"code":"yieldRate","label":"出成率(%)","type":"decimal","required":false,"configurable":true,"defaultVisible":true,"min":0.01,"max":100,"precision":2,"defaultValue":100.00,"listVisible":true,"listOrder":6,"listWidth":100,"group":"dosage"},{"code":"unitPrice","label":"单价","type":"decimal","required":false,"configurable":true,"defaultVisible":true,"min":0,"precision":4,"listVisible":true,"listOrder":7,"listWidth":100,"group":"cost"},{"code":"sortOrder","label":"排序","type":"integer","required":false,"configurable":true,"defaultVisible":false,"defaultValue":0,"group":"basic"},{"code":"remark","label":"备注","type":"textarea","required":false,"configurable":true,"defaultVisible":true,"group":"basic"}],"groups":[{"code":"basic","label":"基本信息","order":1},{"code":"dosage","label":"用量与出成","order":2},{"code":"cost","label":"成本","order":3}]}'::jsonb,
    '{"states":[{"code":"DRAFT","label":"草稿","isInitial":true,"tagType":"info"},{"code":"ACTIVE","label":"生效中","tagType":"success"},{"code":"DEPRECATED","label":"已废弃","isFinal":true,"tagType":"danger"}],"transitions":[{"from":"DRAFT","to":"ACTIVE","action":"activate","label":"启用","buttonType":"success"},{"from":"ACTIVE","to":"DEPRECATED","action":"deprecate","label":"废弃","buttonType":"danger"},{"from":"ACTIVE","to":"DRAFT","action":"revise","label":"修订","buttonType":"warning"}],"options":{}}'::jsonb,
    '{"rules":[]}'::jsonb,
    '{"roles":["factory_super_admin","production_manager","quality"],"fieldPermissions":[]}'::jsonb,
    '{"fields":{},"workflow":{"options":{}},"categories":{"RAW":{"enabled":true},"AUXILIARY":{"enabled":true},"PACKAGING":{"enabled":true}}}'::jsonb,
    'BOM配方模块: 原料/辅料/包材三分组, 支持出成率计算'
)
ON CONFLICT (module_code) DO NOTHING;
