-- 域默认意图表：当关键词匹配失败但域检测成功时返回默认意图
CREATE TABLE IF NOT EXISTS ai_domain_default_intents (
  id VARCHAR(36) PRIMARY KEY,
  factory_id VARCHAR(50) COMMENT '工厂ID(null=平台级)',
  domain_name VARCHAR(30) NOT NULL COMMENT 'SCALE/ALERT/MATERIAL等',
  primary_intent_code VARCHAR(50) NOT NULL COMMENT '主默认意图',
  secondary_intent_code VARCHAR(50) COMMENT '次默认意图',
  is_active BOOLEAN DEFAULT true,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL COMMENT '软删除时间戳',
  UNIQUE KEY uk_factory_domain (factory_id, domain_name)
);

-- 初始化平台级默认意图
INSERT INTO ai_domain_default_intents (id, domain_name, primary_intent_code, secondary_intent_code) VALUES
(UUID(), 'SCALE', 'SCALE_LIST_DEVICES', 'SCALE_DEVICE_DETAIL'),
(UUID(), 'ALERT', 'ALERT_LIST', 'ALERT_ACTIVE'),
(UUID(), 'MATERIAL', 'MATERIAL_BATCH_QUERY', 'REPORT_INVENTORY'),
(UUID(), 'PROCESSING', 'PROCESSING_BATCH_LIST', 'DAILY_PRODUCTION_QUERY'),
(UUID(), 'REPORT', 'REPORT_DASHBOARD_OVERVIEW', 'REPORT_PRODUCTION'),
(UUID(), 'EQUIPMENT', 'EQUIPMENT_LIST', 'EQUIPMENT_STATUS_QUERY'),
(UUID(), 'SHIPMENT', 'SHIPMENT_QUERY', 'SHIPMENT_BY_DATE'),
(UUID(), 'QUALITY', 'QUALITY_CHECK_QUERY', NULL),
(UUID(), 'CUSTOMER', 'CUSTOMER_LIST', 'CUSTOMER_SEARCH'),
(UUID(), 'SUPPLIER', 'SUPPLIER_LIST', NULL),
(UUID(), 'USER', 'USER_LIST', NULL),
(UUID(), 'TRACE', 'TRACE_BATCH', 'TRACE_FULL');
