-- V20260410_06__seed_default_values.sql
INSERT INTO factory_default_values (factory_id, module_code, field_code, default_value, condition, description) VALUES
(NULL, 'sales_order', 'orderDate', '"TODAY"', NULL, '下单日期默认今天'),
(NULL, 'sales_order', 'discountAmount', '0', NULL, '折扣默认0'),
(NULL, 'sales_order', 'discountRate', '0', NULL, '行项目折扣率默认0'),
(NULL, 'purchase_order', 'taxRate', '0', NULL, '税率默认0'),
(NULL, 'bom', 'yieldRate', '95', NULL, '默认良率95%'),
(NULL, 'bom', 'yieldRate', '90', '#industryType == ''BAKERY''', '烘焙良率90%'),
(NULL, 'bom', 'yieldRate', '75', '#industryType == ''AQUACULTURE''', '水产良率75%'),
(NULL, 'bom', 'taxRate', '13', NULL, 'BOM默认税率13%'),
(NULL, 'bom', 'sortOrder', '0', NULL, '排序默认0'),
(NULL, 'finance_ar', 'currentBalance', '0', NULL, '余额默认0'),
(NULL, 'finance_ap', 'currentBalance', '0', NULL, '余额默认0'),
(NULL, 'finance_payment', 'paymentMethod', '"BANK_TRANSFER"', NULL, '默认银行转账'),
(NULL, 'finance_payment', 'paymentDate', '"TODAY"', NULL, '付款日期默认今天'),
(NULL, 'invoice', 'invoiceType', '"NORMAL"', NULL, '默认普票'),
(NULL, 'invoice', 'taxRate', '0', NULL, '行项目税率默认0'),
(NULL, 'supplier', 'creditLimit', '0', NULL, '授信默认0'),
(NULL, 'customer', 'creditLimit', '0', NULL, '授信默认0'),
(NULL, 'rd_sample', 'urgency', '"MEDIUM"', NULL, '紧急程度默认中'),
(NULL, 'inventory', 'defaultShelfLifeDays', '90', NULL, '默认保质期90天'),
(NULL, 'inventory', 'defaultShelfLifeDays', '7', '#industryType == ''BAKERY''', '烘焙保质期7天'),
(NULL, 'production_plan', 'priority', '"NORMAL"', NULL, '排产优先级默认NORMAL'),
(NULL, 'production_report', 'defectQuantity', '0', NULL, '不良品默认0');
