#!/usr/bin/env python3
# Intent Coverage Gap Analysis

# --- Dataset 1: DB intents (from API, 242 total) ---
db_intents_raw = """ALERT_ACKNOWLEDGE
ALERT_ACTIVE
ALERT_BY_EQUIPMENT
ALERT_BY_LEVEL
ALERT_DIAGNOSE
ALERT_LIST
ALERT_RESOLVE
ALERT_STATS
ALERT_TRIAGE
ANALYZE_EQUIPMENT
APPROVAL_CONFIG_PURCHASE_ORDER
APPROVAL_SUBMIT
ATTENDANCE_ANOMALY
ATTENDANCE_DEPARTMENT
ATTENDANCE_HISTORY
ATTENDANCE_MONTHLY
ATTENDANCE_STATS
ATTENDANCE_STATS_BY_DEPT
ATTENDANCE_STATUS
ATTENDANCE_TODAY
BATCH_AUTO_LOOKUP
BATCH_UPDATE
CCP_MONITOR_DATA_DETECTION
CLOCK_IN
CLOCK_OUT
COLD_CHAIN_TEMPERATURE
CONDITION_SWITCH
CONFIG_RESET
CONTINUE_LAST_OPERATION
CONVERSION_RATE_UPDATE
COST_QUERY
COST_TREND_ANALYSIS
CUSTOMER_ACTIVE
CUSTOMER_BY_TYPE
CUSTOMER_DELETE
CUSTOMER_LIST
CUSTOMER_PURCHASE_HISTORY
CUSTOMER_SEARCH
CUSTOMER_STATS
DATA_BATCH_DELETE
E2E_PLAT_1767519593
EQUIPMENT_ALERT_ACKNOWLEDGE
EQUIPMENT_ALERT_LIST
EQUIPMENT_ALERT_RESOLVE
EQUIPMENT_ALERT_STATS
EQUIPMENT_BREAKDOWN_REPORT
EQUIPMENT_CAMERA_START
EQUIPMENT_DELETE
EQUIPMENT_DETAIL
EQUIPMENT_HEALTH_DIAGNOSIS
EQUIPMENT_LIST
EQUIPMENT_MAINTENANCE
EQUIPMENT_START
EQUIPMENT_STATS
EQUIPMENT_STATUS_QUERY
EQUIPMENT_STATUS_UPDATE
EQUIPMENT_STOP
EXCLUDE_SELECTED
EXECUTE_SWITCH
FACTORY_FEATURE_TOGGLE
FACTORY_NOTIFICATION_CONFIG
FACTORY_TEST_1767518251
FILTER_EXCLUDE_SELECTED
FOOD_KNOWLEDGE_QUERY
FORM_GENERATION
HRM_DELETE_EMPLOYEE
HR_DELETE_EMPLOYEE
HR_EMPLOYEE_DELETE
INTENT_ANALYZE
INTENT_CREATE
INTENT_UPDATE
INVENTORY_CLEAR
INVENTORY_OUTBOUND
INVENTORY_SUMMARY_QUERY
INVENTORY_TOTAL_QUERY
ISAPI_CONFIG_FIELD_DETECTION
ISAPI_CONFIG_LINE_DETECTION
ISAPI_QUERY_CAPABILITIES
MATERIAL_ADJUST_QUANTITY
MATERIAL_BATCH_CONSUME
MATERIAL_BATCH_CREATE
MATERIAL_BATCH_DELETE
MATERIAL_BATCH_QUERY
MATERIAL_BATCH_RELEASE
MATERIAL_BATCH_RESERVE
MATERIAL_BATCH_USE
MATERIAL_EXPIRED_QUERY
MATERIAL_EXPIRING_ALERT
MATERIAL_FIFO_RECOMMEND
MATERIAL_LOW_STOCK_ALERT
MATERIAL_UPDATE
MEDIA_PLAY
MEDIA_PLAY_MUSIC
MRP_CALCULATION
NAVIGATE_TO_CITY
NAVIGATE_TO_LOCATION
NAVIGATION_NEXT_PAGE
NAVIGATION_TO_CITY
NAVIGATION_TO_LOCATION
NOTIFICATION_SEND_WECHAT
NOTIFICATION_WECHAT_SEND
OPEN_CAMERA
OPERATION_UNDO_OR_RECALL
ORDER_APPROVAL
ORDER_DELETE
ORDER_FILTER
ORDER_LIST
ORDER_MODIFY
ORDER_NEW
ORDER_STATUS
ORDER_TIMEOUT_MONITOR
ORDER_TODAY
ORDER_UPDATE
PAGINATION_NEXT
PAYMENT_STATUS_QUERY
PLAN_UPDATE
PLATFORM_SHARED_1767519160
PROCESSING_BATCH_CANCEL
PROCESSING_BATCH_COMPLETE
PROCESSING_BATCH_CREATE
PROCESSING_BATCH_DETAIL
PROCESSING_BATCH_LIST
PROCESSING_BATCH_PAUSE
PROCESSING_BATCH_RESUME
PROCESSING_BATCH_START
PROCESSING_BATCH_TIMELINE
PROCESSING_BATCH_WORKERS
PROCESSING_WORKER_ASSIGN
PROCESSING_WORKER_CHECKOUT
PRODUCTION_CONFIRM_WORKERS_PRESENT
PRODUCTION_LINE_START
PRODUCTION_STATUS_QUERY
PRODUCT_SALES_RANKING
PRODUCT_TYPE_QUERY
PRODUCT_UPDATE
PROFIT_TREND_ANALYSIS
QUALITY_BATCH_MARK_AS_INSPECTED
QUALITY_CHECK_CREATE
QUALITY_CHECK_EXECUTE
QUALITY_CHECK_QUERY
QUALITY_CRITICAL_ITEMS
QUALITY_DISPOSITION_EVALUATE
QUALITY_DISPOSITION_EXECUTE
QUALITY_STATS
QUERY_APPROVAL_RECORD
QUERY_DUPONT_ANALYSIS
QUERY_EMPLOYEE_PROFILE
QUERY_EQUIPMENT_STATUS_BY_NAME
QUERY_FINANCE_ROA
QUERY_FINANCE_ROE
QUERY_GENERIC_DETAIL
QUERY_INVENTORY_QUANTITY
QUERY_INVENTORY_TOTAL
QUERY_LIQUIDITY
QUERY_MATERIAL_REJECTION_REASON
QUERY_MATERIAL_STOCK_SUMMARY
QUERY_ONLINE_STAFF_COUNT
QUERY_ORDER_PENDING_MATERIAL_QUANTITY
QUERY_PROCESSING_BATCH_SUPERVISOR
QUERY_PROCESSING_CURRENT_STEP
QUERY_PROCESSING_STEP
QUERY_RETRY_LAST
QUERY_SOLVENCY
QUERY_TRANSPORT_LINE
REPORT_AI_QUALITY
REPORT_ANOMALY
REPORT_BENEFIT_OVERVIEW
REPORT_CHECK
REPORT_DASHBOARD_OVERVIEW
REPORT_EFFICIENCY
REPORT_EXECUTIVE_DAILY
REPORT_FINANCE
REPORT_INTELLIGENT_QUALITY
REPORT_INVENTORY
REPORT_KPI
REPORT_PRODUCTION
REPORT_PRODUCTION_WEEKLY_COMPARISON
REPORT_QUALITY
REPORT_QUALITY_AI
REPORT_TRENDS
REPORT_WORKSHOP_DAILY
RULE_CONFIG
SCALE_ADD_DEVICE
SCALE_ADD_DEVICE_VISION
SCALE_DELETE_DEVICE
SCALE_DEVICE_DETAIL
SCALE_LIST_DEVICES
SCALE_UPDATE_DEVICE
SCHEDULING_COVERAGE_QUERY
SCHEDULING_EXECUTE_FOR_DATE
SCHEDULING_LIST
SCHEDULING_QUERY_COVERAGE
SCHEDULING_RUN_TOMORROW
SCHEDULING_SET_AUTO
SCHEDULING_SET_DISABLED
SCHEDULING_SET_MANUAL
SEND_WECHAT_MESSAGE
SHIPMENT_BY_CUSTOMER
SHIPMENT_BY_DATE
SHIPMENT_CREATE
SHIPMENT_DELETE
SHIPMENT_EXPEDITE
SHIPMENT_NOTIFY_WAREHOUSE_PREPARE
SHIPMENT_QUERY
SHIPMENT_STATS
SHIPMENT_STATUS_UPDATE
SHIPMENT_UPDATE
SHOPPING_CART_CLEAR
SUPPLIER_ACTIVE
SUPPLIER_BY_CATEGORY
SUPPLIER_CREATE
SUPPLIER_DELETE
SUPPLIER_EVALUATE
SUPPLIER_LIST
SUPPLIER_PRICE_COMPARISON
SUPPLIER_RANKING
SUPPLIER_SEARCH
SYSTEM_FILTER_EXCLUDE_SELECTED
SYSTEM_GO_BACK
SYSTEM_RESUME_LAST_ACTION
TASK_ASSIGN_BY_NAME
TASK_ASSIGN_EMPLOYEE
TASK_ASSIGN_WORKER
TASK_PROGRESS_QUERY
TEST_1767807105
TEST_1767807746
TEST_AUTO
TRACE_BATCH
TRACE_FULL
TRACE_PUBLIC
UI_EXCLUDE_SELECTED
USER_CREATE
USER_DELETE
USER_DISABLE
USER_ROLE_ASSIGN
USER_TODO_LIST
USER_UPDATE
WAREHOUSE_OUTBOUND
WORKER_ARRIVAL_CONFIRM
WORKER_IN_SHOP_REALTIME_COUNT
WORK_ORDER_UPDATE
financial_ratios"""

db_intents = set(x.strip() for x in db_intents_raw.strip().split('\n') if x.strip())

# --- Dataset 2: Phrase-mapped intents (extracted via grep) ---
phrase_mapped_raw = """ALERT_ACKNOWLEDGE
ALERT_ACTIVE
ALERT_BY_LEVEL
ALERT_DIAGNOSE
ALERT_LIST
ALERT_RESOLVE
ALERT_STATS
ATTENDANCE_ANOMALY
ATTENDANCE_HISTORY
ATTENDANCE_MONTHLY
ATTENDANCE_STATS
ATTENDANCE_STATS_BY_DEPT
ATTENDANCE_TODAY
BATCH_DELETE
CCP_MONITOR_DATA_DETECTION
CLOCK_IN
CLOCK_OUT
COLD_CHAIN_TEMPERATURE
CONFIG_RESET
CORRELATION_ANALYSIS
COST_QUERY
COST_TREND_ANALYSIS
CUSTOMER_ACTIVE
CUSTOMER_COMPARISON
CUSTOMER_DELETE
CUSTOMER_FEEDBACK
CUSTOMER_LIST
CUSTOMER_PURCHASE_HISTORY
CUSTOMER_QUERY
CUSTOMER_SEARCH
CUSTOMER_STATS
DATA_BATCH_DELETE
EQUIPMENT_ALERT_LIST
EQUIPMENT_ALERT_RESOLVE
EQUIPMENT_ALERT_STATS
EQUIPMENT_BREAKDOWN_REPORT
EQUIPMENT_CAMERA_START
EQUIPMENT_COMPARISON
EQUIPMENT_DETAIL
EQUIPMENT_HEALTH_DIAGNOSIS
EQUIPMENT_LIST
EQUIPMENT_MAINTENANCE
EQUIPMENT_RANKING
EQUIPMENT_START
EQUIPMENT_STATS
EQUIPMENT_STATUS
EQUIPMENT_STATUS_QUERY
EQUIPMENT_STATUS_UPDATE
EQUIPMENT_STOP
FACTORY_FEATURE_TOGGLE
FOOD_KNOWLEDGE_QUERY
HOME_LAYOUT_GENERATE
HOME_LAYOUT_SUGGEST
HOME_LAYOUT_UPDATE
HR_DELETE_EMPLOYEE
INVENTORY_CLEAR
INVENTORY_OUTBOUND
ISAPI_CONFIG_FIELD_DETECTION
ISAPI_CONFIG_LINE_DETECTION
ISAPI_QUERY_DETECTION_EVENTS
MATERIAL_ADJUST_QUANTITY
MATERIAL_BATCH_CONSUME
MATERIAL_BATCH_CREATE
MATERIAL_BATCH_DELETE
MATERIAL_BATCH_QUERY
MATERIAL_BATCH_RELEASE
MATERIAL_BATCH_RESERVE
MATERIAL_BATCH_USE
MATERIAL_COMPARISON
MATERIAL_EXCLUDE_LIST
MATERIAL_EXPIRED_QUERY
MATERIAL_EXPIRING_ALERT
MATERIAL_FIFO_RECOMMEND
MATERIAL_LOW_STOCK_ALERT
MATERIAL_MOM_ANALYSIS
MATERIAL_RANKING
MATERIAL_YOY_ANALYSIS
MRP_CALCULATION
NOTIFICATION_SEND_WECHAT
ORDER_APPROVAL
ORDER_CANCEL
ORDER_COMPARISON
ORDER_DELETE
ORDER_DETAIL
ORDER_EXCLUDE_LIST
ORDER_FILTER
ORDER_LIST
ORDER_MOM_ANALYSIS
ORDER_NEW
ORDER_RECENT
ORDER_STATS
ORDER_STATUS
ORDER_TIMEOUT_MONITOR
ORDER_TODAY
ORDER_UPDATE
ORDER_YOY_ANALYSIS
PAGE_COMPONENT_ADD
PAGE_DATA_BIND
PAGE_GENERATE
PAGE_STYLE_UPDATE
PAYMENT_STATUS_QUERY
PLAN_UPDATE
PROCESSING_BATCH_CANCEL
PROCESSING_BATCH_COMPLETE
PROCESSING_BATCH_CREATE
PROCESSING_BATCH_DETAIL
PROCESSING_BATCH_LIST
PROCESSING_BATCH_PAUSE
PROCESSING_BATCH_RESUME
PROCESSING_BATCH_START
PROCESSING_BATCH_TIMELINE
PROCESSING_BATCH_WORKERS
PROCESSING_COMPARISON
PROCESSING_MOM_ANALYSIS
PROCESSING_RANKING
PROCESSING_WORKER_ASSIGN
PROCESSING_WORKER_CHECKOUT
PROCESSING_YOY_ANALYSIS
PRODUCT_SALES_RANKING
PRODUCT_UPDATE
PRODUCTION_CONFIRM_WORKERS_PRESENT
PRODUCTION_LINE_START
PRODUCTION_STATUS_QUERY
QUALITY_BATCH_MARK_AS_INSPECTED
QUALITY_CHECK_CREATE
QUALITY_CHECK_EXECUTE
QUALITY_CHECK_QUERY
QUALITY_COMPARISON
QUALITY_CRITICAL_ITEMS
QUALITY_DISPOSITION_EXECUTE
QUALITY_MOM_ANALYSIS
QUALITY_RANKING
QUALITY_STATS
QUALITY_YOY_ANALYSIS
QUERY_APPROVAL_RECORD
QUERY_EMPLOYEE_PROFILE
QUERY_EQUIPMENT_STATUS_BY_NAME
QUERY_FINANCE_ROA
QUERY_FINANCE_ROE
QUERY_MATERIAL_REJECTION_REASON
QUERY_ONLINE_STAFF_COUNT
QUERY_ORDER_PENDING_MATERIAL_QUANTITY
QUERY_PROCESSING_BATCH_SUPERVISOR
QUERY_PROCESSING_CURRENT_STEP
QUERY_PROCESSING_STEP
QUERY_TRANSPORT_LINE
REPORT_AI_QUALITY
REPORT_ANOMALY
REPORT_BENEFIT_OVERVIEW
REPORT_CHECK
REPORT_DASHBOARD_OVERVIEW
REPORT_EFFICIENCY
REPORT_FINANCE
REPORT_INTELLIGENT_QUALITY
REPORT_INVENTORY
REPORT_KPI
REPORT_PRODUCTION
REPORT_QUALITY
REPORT_TRENDS
REPORT_WORKSHOP_DAILY
RULE_CONFIG
SALES_STATS
SCALE_ADD_DEVICE
SCALE_DELETE_DEVICE
SCALE_DEVICE_DETAIL
SCALE_LIST_DEVICES
SCALE_UPDATE_DEVICE
SCHEDULING_EXECUTE_FOR_DATE
SCHEDULING_LIST
SCHEDULING_SET_AUTO
SCHEDULING_SET_MANUAL
SHIPMENT_BY_CUSTOMER
SHIPMENT_BY_DATE
SHIPMENT_COMPARISON
SHIPMENT_CREATE
SHIPMENT_DELETE
SHIPMENT_NOTIFY_WAREHOUSE_PREPARE
SHIPMENT_QUERY
SHIPMENT_RANKING
SHIPMENT_STATS
SHIPMENT_STATUS_UPDATE
SHIPMENT_UPDATE
SUPPLIER_BY_CATEGORY
SUPPLIER_COMPARISON
SUPPLIER_CREATE
SUPPLIER_DELETE
SUPPLIER_EVALUATE
SUPPLIER_LIST
SUPPLIER_QUERY
SUPPLIER_RANKING
SUPPLIER_SEARCH
TASK_ASSIGN_BY_NAME
TASK_ASSIGN_WORKER
TRACE_BATCH
TRACE_FULL
TRACE_GENERATE
TRACE_PUBLIC
USER_CREATE
USER_DELETE
USER_DISABLE
USER_ROLE_ASSIGN
USER_TODO_LIST
WAREHOUSE_OUTBOUND
WORKER_ARRIVAL_CONFIRM
WORKER_IN_SHOP_REALTIME_COUNT"""

phrase_mapped = set(x.strip() for x in phrase_mapped_raw.strip().split('\n') if x.strip())

# --- Dataset 3: All intent codes from test expected lists ---
test_covered_raw = """FOOD_KNOWLEDGE_QUERY
MATERIAL_BATCH_QUERY
INBOUND_RECORD_QUERY
REPORT_INVENTORY
PROCESSING_BATCH_LIST
PROCESSING_BATCH_DETAIL
PRODUCTION_STATUS_QUERY
REPORT_PRODUCTION
ORDER_LIST
ORDER_DETAIL
LOGISTICS_TRACKING
ORDER_TODAY
ORDER_STATUS
ORDER_TIMEOUT_MONITOR
QUALITY_INSPECTION_LIST
QUALITY_BATCH_REPORT
QUALITY_CHECK_QUERY
QUALITY_STATS
QUALITY_CRITICAL_ITEMS
PROCUREMENT_LIST
PROCUREMENT_STATS
ATTENDANCE_STATS
ATTENDANCE_RECORD
ATTENDANCE_HISTORY
ATTENDANCE_TODAY
ATTENDANCE_ANOMALY
ATTENDANCE_DEPARTMENT
ATTENDANCE_MONTHLY
ATTENDANCE_STATS_BY_DEPT
HR_PERFORMANCE
EMPLOYEE_DETAIL
REPORT_KPI
CUSTOMER_STATS
SALES_STATS
SALES_RANKING
PRODUCT_SALES_RANKING
EQUIPMENT_STATUS_QUERY
EQUIPMENT_LIST
EQUIPMENT_STATS
EQUIPMENT_DETAIL
EQUIPMENT_MAINTENANCE
EQUIPMENT_ALERT_LIST
EQUIPMENT_ALERT_STATS
ALERT_LIST
ALERT_ACTIVE
ALERT_STATS
COLD_CHAIN_TEMPERATURE
SCHEDULING_QUERY
SCHEDULING_LIST
SCHEDULING_COVERAGE_QUERY
PRODUCTION_PLAN_LIST
FINANCE_STATS
COST_TREND_ANALYSIS
COST_QUERY
REPORT_FINANCE
PRODUCT_TYPE_QUERY
REPORT_TRENDS
REPORT_QUALITY
REPORT_DASHBOARD_OVERVIEW
REPORT_EXECUTIVE_DAILY
REPORT_PRODUCTION_WEEKLY_COMPARISON
SHIPMENT_QUERY
SHIPMENT_STATS
SHIPMENT_BY_DATE
SHIPMENT_BY_CUSTOMER
SUPPLIER_LIST
SUPPLIER_SEARCH
SUPPLIER_RANKING
SUPPLIER_EVALUATE
SUPPLIER_PRICE_COMPARISON
CUSTOMER_LIST
CUSTOMER_SEARCH
CUSTOMER_PURCHASE_HISTORY
CUSTOMER_ACTIVE
TRACE_BATCH
TRACE_FULL
TRACE_PUBLIC
WAREHOUSE_INVENTORY_CHECK
MATERIAL_LOW_STOCK_ALERT
MATERIAL_EXPIRED_QUERY
MATERIAL_EXPIRING_ALERT
INVENTORY_SUMMARY_QUERY
INVENTORY_TOTAL_QUERY
TASK_PROGRESS_QUERY
PROCESSING_BATCH_TIMELINE
SUPPLIER_ACTIVE
SUPPLIER_BY_CATEGORY
CUSTOMER_BY_TYPE
SCALE_LIST_DEVICES
SCALE_DEVICE_DETAIL
REPORT_EFFICIENCY
REPORT_ANOMALY
QUERY_INVENTORY_QUANTITY
QUERY_INVENTORY_TOTAL
QUERY_MATERIAL_STOCK_SUMMARY
QUERY_LIQUIDITY
QUERY_SOLVENCY
QUERY_DUPONT_ANALYSIS
ATTENDANCE_STATUS
PAYMENT_STATUS_QUERY
SHIPMENT_EXPEDITE
ALERT_BY_EQUIPMENT
ALERT_BY_LEVEL
ALERT_DIAGNOSE
ALERT_TRIAGE
EQUIPMENT_ALERT_ACKNOWLEDGE
SCHEDULING_QUERY_COVERAGE
MATERIAL_FIFO_RECOMMEND
QUALITY_DISPOSITION_EVALUATE
QUERY_FINANCE_ROA
QUERY_FINANCE_ROE
QUERY_EMPLOYEE_PROFILE
QUERY_ONLINE_STAFF_COUNT
REPORT_BENEFIT_OVERVIEW
USER_TODO_LIST
BATCH_AUTO_LOOKUP
BREAKDOWN_REPORT
ORDER_APPROVAL
SCHEDULING_RUN_TOMORROW
PROFIT_TREND_ANALYSIS
ANALYZE_EQUIPMENT
EQUIPMENT_BREAKDOWN_REPORT
EQUIPMENT_HEALTH_DIAGNOSIS
CCP_MONITOR_DATA_DETECTION
PROCESSING_BATCH_WORKERS
QUERY_PROCESSING_BATCH_SUPERVISOR
QUERY_PROCESSING_CURRENT_STEP
QUERY_PROCESSING_STEP
QUERY_APPROVAL_RECORD
QUERY_ORDER_PENDING_MATERIAL_QUANTITY
QUERY_MATERIAL_REJECTION_REASON
QUERY_EQUIPMENT_STATUS_BY_NAME
QUERY_TRANSPORT_LINE
REPORT_AI_QUALITY
REPORT_INTELLIGENT_QUALITY
REPORT_QUALITY_AI
REPORT_CHECK
REPORT_WORKSHOP_DAILY
WORKER_IN_SHOP_REALTIME_COUNT
WORKER_ARRIVAL_CONFIRM
INVENTORY_OUTBOUND
WAREHOUSE_OUTBOUND
APPROVAL_CONFIG_PURCHASE_ORDER
MRP_CALCULATION
MATERIAL_BATCH_CREATE
MATERIAL_BATCH_DELETE
MATERIAL_UPDATE
MATERIAL_ADJUST_QUANTITY
PROCESSING_BATCH_CREATE
PROCESSING_BATCH_START
PROCESSING_BATCH_PAUSE
PROCESSING_BATCH_RESUME
PROCESSING_BATCH_COMPLETE
PROCESSING_BATCH_CANCEL
ORDER_CREATE
ORDER_NEW
ORDER_UPDATE
ORDER_DELETE
ORDER_MODIFY
SHIPMENT_CREATE
SHIPMENT_STATUS_UPDATE
SHIPMENT_DELETE
SHIPMENT_UPDATE
CLOCK_IN
CLOCK_OUT
BATCH_UPDATE
QUALITY_CHECK_CREATE
QUALITY_CHECK_EXECUTE
ALERT_ACKNOWLEDGE
ALERT_RESOLVE
EQUIPMENT_STATUS_UPDATE
EQUIPMENT_START
EQUIPMENT_STOP
SUPPLIER_CREATE
SUPPLIER_DELETE
USER_CREATE
USER_UPDATE
USER_DELETE
SCHEDULING_SET_AUTO
SCHEDULING_SET_MANUAL
SCHEDULING_SET_DISABLED
PRODUCTION_LINE_START
SCALE_ADD_DEVICE
SCALE_DELETE_DEVICE
SCALE_UPDATE_DEVICE
INVENTORY_CLEAR
MATERIAL_BATCH_CONSUME
MATERIAL_BATCH_RELEASE
MATERIAL_BATCH_RESERVE
PRODUCT_UPDATE
PLAN_UPDATE
CONVERSION_RATE_UPDATE
PROCESSING_WORKER_ASSIGN
QUALITY_BATCH_MARK_AS_INSPECTED
QUALITY_DISPOSITION_EXECUTE
HR_DELETE_EMPLOYEE
TASK_ASSIGN_WORKER
SUPPLIER_EVALUATE
EQUIPMENT_CAMERA_START
EQUIPMENT_ALERT_RESOLVE
PROCESSING_WORKER_CHECKOUT
PRODUCTION_CONFIRM_WORKERS_PRESENT
SCHEDULING_EXECUTE_FOR_DATE
SHIPMENT_NOTIFY_WAREHOUSE_PREPARE
TASK_ASSIGN_BY_NAME
TASK_ASSIGN_EMPLOYEE
NOTIFICATION_SEND_WECHAT
SEND_WECHAT_MESSAGE
HR_EMPLOYEE_DELETE
HRM_DELETE_EMPLOYEE
CUSTOMER_RANKING
QUALITY_INSPECTION_LIST
OPEN_CAMERA
NOTIFICATION_WECHAT_SEND"""

test_covered = set(x.strip() for x in test_covered_raw.strip().split('\n') if x.strip())

# Exclude system/test/noise codes from DB analysis
system_noise = {
    'E2E_PLAT_1767519593', 'FACTORY_TEST_1767518251', 'PLATFORM_SHARED_1767519160',
    'TEST_1767807105', 'TEST_1767807746', 'TEST_AUTO', 'financial_ratios',
    'CONDITION_SWITCH', 'CONTINUE_LAST_OPERATION', 'EXCLUDE_SELECTED', 'EXECUTE_SWITCH',
    'FILTER_EXCLUDE_SELECTED', 'FORM_GENERATION', 'INTENT_ANALYZE', 'INTENT_CREATE', 'INTENT_UPDATE',
    'MEDIA_PLAY', 'MEDIA_PLAY_MUSIC', 'NAVIGATE_TO_CITY', 'NAVIGATE_TO_LOCATION',
    'NAVIGATION_NEXT_PAGE', 'NAVIGATION_TO_CITY', 'NAVIGATION_TO_LOCATION',
    'OPERATION_UNDO_OR_RECALL', 'PAGINATION_NEXT', 'QUERY_GENERIC_DETAIL', 'QUERY_RETRY_LAST',
    'RULE_CONFIG', 'SCALE_ADD_DEVICE_VISION', 'SHOPPING_CART_CLEAR',
    'SYSTEM_FILTER_EXCLUDE_SELECTED', 'SYSTEM_GO_BACK', 'SYSTEM_RESUME_LAST_ACTION',
    'UI_EXCLUDE_SELECTED', 'USER_DISABLE', 'USER_ROLE_ASSIGN', 'WORK_ORDER_UPDATE',
    'FACTORY_FEATURE_TOGGLE', 'FACTORY_NOTIFICATION_CONFIG', 'CONFIG_RESET',
    'ISAPI_CONFIG_FIELD_DETECTION', 'ISAPI_CONFIG_LINE_DETECTION', 'ISAPI_QUERY_CAPABILITIES',
    'CUSTOMER_DELETE', 'EQUIPMENT_DELETE', 'APPROVAL_SUBMIT',
}

business_db = db_intents - system_noise

print("=" * 70)
print("INTENT COVERAGE GAP ANALYSIS")
print("=" * 70)
print(f"Total DB intents: {len(db_intents)}")
print(f"  System/test noise excluded: {len(system_noise)}")
print(f"  Business-relevant DB intents: {len(business_db)}")
print(f"Phrase-mapped intent codes (unique): {len(phrase_mapped)}")
print(f"Test-covered intent codes (unique): {len(test_covered)}")

# ============================================================
# SECTION A: Business DB intents with ZERO test coverage
# ============================================================
section_a = business_db - test_covered
print(f"\n{'='*70}")
print(f"SECTION A: DB Intents with ZERO Test Coverage ({len(section_a)})")
print(f"{'='*70}")
for code in sorted(section_a):
    p = "[has phrase]" if code in phrase_mapped else "[NO phrase]"
    print(f"  {code:<45} {p}")

# ============================================================
# SECTION B: Phrase-mapped intents with ZERO test coverage
# ============================================================
section_b = phrase_mapped - test_covered
print(f"\n{'='*70}")
print(f"SECTION B: Phrase-Mapped Intents with ZERO Test Coverage ({len(section_b)})")
print(f"{'='*70}")
for code in sorted(section_b):
    db = "[in DB]" if code in db_intents else "[NOT in DB - phantom!]"
    print(f"  {code:<45} {db}")

# ============================================================
# SECTION C: Test-covered intents missing phrase mappings
# ============================================================
section_c = test_covered - phrase_mapped
print(f"\n{'='*70}")
print(f"SECTION C: Test-Covered Intents Missing Phrase Mappings ({len(section_c)})")
print(f"{'='*70}")
for code in sorted(section_c):
    db = "[in DB]" if code in db_intents else "[NOT in DB]"
    print(f"  {code:<45} {db}")

# ============================================================
# EXTRA: Test intents not in DB at all (invalid expectations)
# ============================================================
not_in_db = test_covered - db_intents
print(f"\n{'='*70}")
print(f"EXTRA: Test-Expected Intents NOT in DB ({len(not_in_db)})")
print(f"{'='*70}")
for code in sorted(not_in_db):
    phrase = "[has phrase]" if code in phrase_mapped else "[no phrase]"
    print(f"  {code:<45} {phrase}")

print(f"\n{'='*70}")
print("FINAL SUMMARY")
print(f"{'='*70}")
print(f"A: Uncovered DB intents:               {len(section_a)}")
print(f"B: Uncovered phrase-mapped intents:    {len(section_b)}")
print(f"C: Test intents missing phrase maps:   {len(section_c)}")
print(f"   of which NOT in DB (phantom):       {len(not_in_db)}")
