package com.cretas.aims.entity.sales;

import com.cretas.aims.entity.BaseEntity;
import com.cretas.aims.entity.enums.ServiceComplaintSeverity;
import com.cretas.aims.entity.enums.ServiceComplaintSource;
import com.cretas.aims.entity.enums.ServiceComplaintStatus;
import com.cretas.aims.entity.enums.ServiceComplaintType;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.*;
import org.hibernate.annotations.Where;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * P2 #74 S-COMPLAINT-1 — 售后服务投诉.
 *
 * <p>客户投诉登记 / 调查 / 处理跟踪. 12 字段 MVP:
 * factoryId / complaintNumber (CMP-YYYYMMDD-NNNN) / customerId / customerName
 * (denormalized) / orderId nullable / complaintType / severity / source /
 * status / description / handledBy / resolution / occurredAt / resolvedAt.
 *
 * <p>状态机:
 * <pre>
 * NEW --start--> INVESTIGATING --resolve--> RESOLVED --close--> CLOSED
 * </pre>
 *
 * <p>防呆 R4 — 同 customer + same description 5min 内重复 → 拒绝创建.
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "service_complaints",
        uniqueConstraints = {
                @UniqueConstraint(name = "uq_complaint_number",
                        columnNames = {"factory_id", "complaint_number"})
        },
        indexes = {
                @Index(name = "idx_sc_factory_status", columnList = "factory_id, status"),
                @Index(name = "idx_sc_factory_customer", columnList = "factory_id, customer_id"),
                @Index(name = "idx_sc_occurred", columnList = "factory_id, occurred_at")
        }
)
@Where(clause = "deleted_at IS NULL")
public class ServiceComplaint extends BaseEntity {

    @Id
    @Column(name = "id", nullable = false, length = 36)
    private String id;

    @PrePersist
    void assignUUID() {
        if (id == null) {
            id = UUID.randomUUID().toString();
        }
    }

    @NotBlank
    @Column(name = "factory_id", nullable = false, length = 191)
    private String factoryId;

    /** CMP-YYYYMMDD-NNNN, generated by ServiceImpl. */
    @NotBlank
    @Column(name = "complaint_number", nullable = false, length = 32)
    private String complaintNumber;

    @NotBlank
    @Column(name = "customer_id", nullable = false, length = 191)
    private String customerId;

    /** Denormalized from Customer.name at time of creation. */
    @Column(name = "customer_name", length = 200)
    private String customerName;

    /** Optional — link to a SalesOrder.id if complaint relates to a specific order. */
    @Column(name = "order_id", length = 191)
    private String orderId;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "complaint_type", nullable = false, length = 32)
    private ServiceComplaintType complaintType;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "severity", nullable = false, length = 16)
    private ServiceComplaintSeverity severity = ServiceComplaintSeverity.MEDIUM;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "source", nullable = false, length = 16)
    private ServiceComplaintSource source = ServiceComplaintSource.PHONE;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 16)
    private ServiceComplaintStatus status = ServiceComplaintStatus.NEW;

    @NotBlank
    @Column(name = "description", nullable = false, columnDefinition = "TEXT")
    private String description;

    /** Optional — user id of the person handling this complaint. */
    @Column(name = "handled_by")
    private Long handledBy;

    /** Filled in when transitioning to RESOLVED. */
    @Column(name = "resolution", columnDefinition = "TEXT")
    private String resolution;

    /** When the underlying incident actually happened (customer-reported). */
    @Column(name = "occurred_at")
    private LocalDateTime occurredAt;

    /** Set automatically when status → RESOLVED. */
    @Column(name = "resolved_at")
    private LocalDateTime resolvedAt;

    /** Creator user id. */
    @Column(name = "created_by")
    private Long createdBy;
}
