# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import embedding_pb2 as embedding__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embedding_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub(object):
    """Embedding Service - provides text embedding and similarity computation
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Encode = channel.unary_unary(
                '/embedding.EmbeddingService/Encode',
                request_serializer=embedding__pb2.EncodeRequest.SerializeToString,
                response_deserializer=embedding__pb2.EncodeResponse.FromString,
                _registered_method=True)
        self.EncodeBatch = channel.unary_unary(
                '/embedding.EmbeddingService/EncodeBatch',
                request_serializer=embedding__pb2.EncodeBatchRequest.SerializeToString,
                response_deserializer=embedding__pb2.EncodeBatchResponse.FromString,
                _registered_method=True)
        self.ComputeSimilarity = channel.unary_unary(
                '/embedding.EmbeddingService/ComputeSimilarity',
                request_serializer=embedding__pb2.SimilarityRequest.SerializeToString,
                response_deserializer=embedding__pb2.SimilarityResponse.FromString,
                _registered_method=True)
        self.FindSimilar = channel.unary_unary(
                '/embedding.EmbeddingService/FindSimilar',
                request_serializer=embedding__pb2.FindSimilarRequest.SerializeToString,
                response_deserializer=embedding__pb2.FindSimilarResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/embedding.EmbeddingService/HealthCheck',
                request_serializer=embedding__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=embedding__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/embedding.EmbeddingService/GetModelInfo',
                request_serializer=embedding__pb2.ModelInfoRequest.SerializeToString,
                response_deserializer=embedding__pb2.ModelInfoResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """Embedding Service - provides text embedding and similarity computation
    """

    def Encode(self, request, context):
        """Encode single text to embedding vector
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EncodeBatch(self, request, context):
        """Encode multiple texts in batch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ComputeSimilarity(self, request, context):
        """Compute similarity between two texts
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindSimilar(self, request, context):
        """Find similar texts from candidates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Get model info
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Encode': grpc.unary_unary_rpc_method_handler(
                    servicer.Encode,
                    request_deserializer=embedding__pb2.EncodeRequest.FromString,
                    response_serializer=embedding__pb2.EncodeResponse.SerializeToString,
            ),
            'EncodeBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EncodeBatch,
                    request_deserializer=embedding__pb2.EncodeBatchRequest.FromString,
                    response_serializer=embedding__pb2.EncodeBatchResponse.SerializeToString,
            ),
            'ComputeSimilarity': grpc.unary_unary_rpc_method_handler(
                    servicer.ComputeSimilarity,
                    request_deserializer=embedding__pb2.SimilarityRequest.FromString,
                    response_serializer=embedding__pb2.SimilarityResponse.SerializeToString,
            ),
            'FindSimilar': grpc.unary_unary_rpc_method_handler(
                    servicer.FindSimilar,
                    request_deserializer=embedding__pb2.FindSimilarRequest.FromString,
                    response_serializer=embedding__pb2.FindSimilarResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=embedding__pb2.HealthCheckRequest.FromString,
                    response_serializer=embedding__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=embedding__pb2.ModelInfoRequest.FromString,
                    response_serializer=embedding__pb2.ModelInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedding.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('embedding.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """Embedding Service - provides text embedding and similarity computation
    """

    @staticmethod
    def Encode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.EmbeddingService/Encode',
            embedding__pb2.EncodeRequest.SerializeToString,
            embedding__pb2.EncodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EncodeBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.EmbeddingService/EncodeBatch',
            embedding__pb2.EncodeBatchRequest.SerializeToString,
            embedding__pb2.EncodeBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ComputeSimilarity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.EmbeddingService/ComputeSimilarity',
            embedding__pb2.SimilarityRequest.SerializeToString,
            embedding__pb2.SimilarityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindSimilar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.EmbeddingService/FindSimilar',
            embedding__pb2.FindSimilarRequest.SerializeToString,
            embedding__pb2.FindSimilarResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.EmbeddingService/HealthCheck',
            embedding__pb2.HealthCheckRequest.SerializeToString,
            embedding__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/embedding.EmbeddingService/GetModelInfo',
            embedding__pb2.ModelInfoRequest.SerializeToString,
            embedding__pb2.ModelInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
