name: Mobile App Build & Deploy

on:
  push:
    branches: [main, develop]
    paths:
      - 'packages/mobile/**'
      - 'packages/core/**'
      - 'packages/ui-shared/**'
  pull_request:
    branches: [main]
    paths:
      - 'packages/mobile/**'
      - 'packages/core/**'
      - 'packages/ui-shared/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Type check
        run: pnpm run type-check

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

  build-preview:
    name: EAS Build - Preview
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Expo CLI
        run: npm install -g @expo/cli

      - name: Install dependencies
        run: pnpm install

      - name: Setup EAS CLI
        run: npm install -g eas-cli

      - name: EAS Login
        run: eas login --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Preview - Android
        run: |
          cd packages/mobile
          eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  build-production:
    name: EAS Build - Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        platform: [android, ios]
        profile: [production, production-huawei]
        exclude:
          - platform: ios
            profile: production-huawei
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Setup Expo CLI
        run: npm install -g @expo/cli

      - name: Install dependencies
        run: pnpm install

      - name: Setup EAS CLI
        run: npm install -g eas-cli

      - name: EAS Login
        run: eas login --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Build Production
        run: |
          cd packages/mobile
          eas build --platform ${{ matrix.platform }} --profile ${{ matrix.profile }} --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          HUAWEI_APP_ID: ${{ secrets.HUAWEI_APP_ID }}
          HUAWEI_CLIENT_ID: ${{ secrets.HUAWEI_CLIENT_ID }}
          HUAWEI_CLIENT_SECRET: ${{ secrets.HUAWEI_CLIENT_SECRET }}

      - name: Submit to App Store (iOS)
        if: matrix.platform == 'ios' && matrix.profile == 'production'
        run: |
          cd packages/mobile
          eas submit --platform ios --latest --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}

      - name: Submit to Google Play (Android)
        if: matrix.platform == 'android' && matrix.profile == 'production'
        run: |
          cd packages/mobile
          eas submit --platform android --latest --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Submit to Huawei AppGallery (Android Huawei)
        if: matrix.platform == 'android' && matrix.profile == 'production-huawei'
        run: |
          cd packages/mobile
          eas submit --platform android --latest --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Documentation
        run: pnpm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist