"""v2 conversation memory: server-side session storage for follow-up context.

Background (Apr 26 2026): S3 270-followup audit measured 3.21/5 vs main 3.94/5
(-18.5%). Root cause: no conversation memory. When a user asks "为什么"/"怎么办"
follow-ups, the LLM has no reference to the parent answer, so it either
hallucinates or 30s-times-out trying to re-derive context.

This service stores the latest (parent_query, parent_answer_summary) keyed by
session_id. The session_id is generated by the frontend (UUID v4) and persisted
in sessionStorage so it survives page reloads within the same tab.

Lookup happens at the start of /general-analysis-stream Phase 0; if found, the
parent context is injected into the LLM prompt. After the answer streams, we
truncate it to ~750 chars and write back as the new parent_answer_summary so
the next follow-up can reference it.

Tenant isolation: factory_id is part of the lookup. A session_id from tenant A
will NOT match if tenant B presents the same id (factory mismatch returns None).

TTL: 1 hour rolling. Each turn refreshes expires_at. Cron prunes expired rows.
"""
from __future__ import annotations

import logging
from typing import Any, Dict, Optional

import asyncpg

logger = logging.getLogger(__name__)

# Truncation budget: ~500 LLM tokens for Chinese-heavy text averages ~750 chars
# (1.5 chars/token). This is conservative — DashScope qwen-plus tokenizer treats
# Chinese as ~1 token per 1.5 chars. English averages ~4 chars/token, so 750 chars
# of English is ~190 tokens. We pick the conservative bound for Chinese.
SUMMARY_CHAR_BUDGET = 750

# Rolling TTL: each turn extends expires_at by this duration.
TTL_SECONDS = 3600  # 1 hour


def truncate_summary(text: str, budget: int = SUMMARY_CHAR_BUDGET) -> str:
    """Truncate a long answer to fit the parent_answer_summary budget.

    Strategy: keep the first 60% (key numbers + main finding) and the last 40%
    (recommendations + conclusion). Stitch with a "...[省略中段]..." marker so
    the LLM understands the gap.
    """
    if not text:
        return ""
    text = text.strip()
    if len(text) <= budget:
        return text
    head_chars = int(budget * 0.6)
    tail_chars = budget - head_chars - 12  # 12 chars for the marker
    if tail_chars < 50:
        return text[:budget].rstrip() + "..."
    return f"{text[:head_chars].rstrip()}...[省略中段]...{text[-tail_chars:].lstrip()}"


class ChatSessionService:
    """Async service for smart_bi_chat_session table."""

    def __init__(self, pool: asyncpg.Pool):
        self._pool = pool

    async def lookup(
        self, session_id: str, factory_id: str
    ) -> Optional[Dict[str, Any]]:
        """Fetch session for (session_id, factory_id) if not expired.

        Returns dict with keys: parent_query, parent_answer_summary,
        parent_template_code, parent_upload_id, turn_count.
        Returns None if session_id absent, factory mismatch, or expired.
        """
        if not session_id or not factory_id:
            return None
        try:
            async with self._pool.acquire() as conn:
                row = await conn.fetchrow(
                    """
                    SELECT parent_query, parent_answer_summary,
                           parent_template_code, parent_upload_id, turn_count
                    FROM smart_bi_chat_session
                    WHERE session_id = $1
                      AND factory_id = $2
                      AND expires_at > NOW()
                    """,
                    session_id, factory_id,
                )
                if not row:
                    return None
                return dict(row)
        except Exception as e:
            logger.warning(f"[chat-session] lookup failed (non-fatal): {e}")
            return None

    async def upsert(
        self,
        session_id: str,
        factory_id: str,
        parent_query: str,
        parent_answer_summary: str,
        parent_template_code: Optional[str] = None,
        parent_upload_id: Optional[int] = None,
        user_id: Optional[int] = None,
    ) -> None:
        """Write back the parent context after this turn finishes.

        On conflict (existing session_id), refreshes expires_at and increments
        turn_count. Truncates parent_answer_summary to SUMMARY_CHAR_BUDGET.
        """
        if not session_id or not factory_id:
            return
        summary = truncate_summary(parent_answer_summary)
        try:
            async with self._pool.acquire() as conn:
                await conn.execute(
                    """
                    INSERT INTO smart_bi_chat_session (
                        session_id, factory_id, user_id,
                        parent_query, parent_answer_summary,
                        parent_template_code, parent_upload_id,
                        turn_count, expires_at
                    )
                    VALUES (
                        $1, $2, $3, $4, $5, $6, $7, 1,
                        NOW() + INTERVAL '1 hour'
                    )
                    ON CONFLICT (session_id) DO UPDATE SET
                        parent_query          = EXCLUDED.parent_query,
                        parent_answer_summary = EXCLUDED.parent_answer_summary,
                        parent_template_code  = EXCLUDED.parent_template_code,
                        parent_upload_id      = EXCLUDED.parent_upload_id,
                        turn_count            = smart_bi_chat_session.turn_count + 1,
                        updated_at            = NOW(),
                        expires_at            = NOW() + INTERVAL '1 hour'
                    """,
                    session_id, factory_id, user_id,
                    parent_query, summary,
                    parent_template_code, parent_upload_id,
                )
        except Exception as e:
            logger.warning(f"[chat-session] upsert failed (non-fatal): {e}")

    async def prune_expired(self) -> int:
        """Delete expired sessions. Returns row count."""
        try:
            async with self._pool.acquire() as conn:
                result = await conn.execute(
                    "DELETE FROM smart_bi_chat_session WHERE expires_at < NOW()"
                )
                # asyncpg returns "DELETE N" — extract N
                if isinstance(result, str) and result.startswith("DELETE "):
                    return int(result.split()[1])
                return 0
        except Exception as e:
            logger.warning(f"[chat-session] prune failed: {e}")
            return 0


def build_context_block(parent: Dict[str, Any]) -> str:
    """Format parent context into a prompt block for LLM injection.

    Returns Chinese-formatted block to prepend to the user_prompt. Empty
    string if parent dict missing required fields.

    S4 audit P2 fix (Apr 26 2026): the prompt was too soft — only 4/270
    follow-up answers explicitly said "上一轮", most used inline entity refs
    which are harder to audit and weaker on Coherence (1-5). New prompt
    requires the LLM to explicitly anchor: "上一轮已回答: [parent fact]" then
    give the new analysis, so reviewers can verify continuity.
    """
    pq = (parent.get("parent_query") or "").strip()
    pa = (parent.get("parent_answer_summary") or "").strip()
    if not pq or not pa:
        return ""
    return (
        "## 上一轮对话 (本轮回答必须显式延续此处的实体和数字)\n"
        f"上一轮提问: {pq}\n\n"
        f"上一轮回答摘要: {pa}\n\n"
        "**本轮回答规则**:\n"
        "1. 开头第一句必须显式承上启下 — 例如 `基于上一轮 X 数据/Y 实体` 或 `上一轮已说明 X,本轮分析 Y`\n"
        "2. 复用上一轮的具体数字 (金额/百分比/Top N 实体名),不要重新计算或介绍\n"
        "3. 只回答本轮新问题,不要重复上一轮的全部内容\n"
        "4. 如果上一轮没提到本轮所需信息,明确说 `上一轮未涉及 X,基于当前数据补充分析`\n\n"
        "---\n\n"
    )
