package com.cretas.aims.dto.ai;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * 创建 AI Agent 规则请求 DTO (Rule 17.1 cleanup — Issue #384 batch 6 final).
 *
 * <p>替代 {@code @RequestBody AiAgentRule} 实体直绑模式. 隔离 wire contract
 * 与 {@link com.cretas.aims.entity.smartbi.AiAgentRule} 持久化模型 — 防止
 * {@code @Builder.Default} 字段 ({@code factoryId = "DEFAULT"},
 * {@code priority = 100}, {@code useLlmSelection = false}, {@code isActive = true})
 * 通过 {@code @NoArgsConstructor} 字段初始化器在 Jackson 反序列化时静默写入,
 * 进而隐式覆盖客户端意图.
 *
 * <p>Auto-managed by controller / service / DB:
 * <ul>
 *   <li>{@code id} — generated by Hibernate UUID2 strategy (never accepted from wire)</li>
 *   <li>{@code factoryId} — overridden by {@code @PathVariable} in controller</li>
 *   <li>{@code priority} default 100 — applied by controller when null</li>
 *   <li>{@code isActive} default true — applied by controller when null</li>
 *   <li>{@code useLlmSelection} default false — applied by controller when null</li>
 *   <li>{@code createdAt}, {@code updatedAt}, {@code deletedAt} — BaseEntity-managed</li>
 * </ul>
 *
 * @see com.cretas.aims.entity.smartbi.AiAgentRule
 * @see <a href="https://github.com/j4xie/my-prototype-logistics/issues/384">Issue #384 Rule 17.1 batch 6</a>
 * @since 2026-05-11
 */
@Data
@Schema(description = "创建 AI Agent 规则请求")
public class CreateAiAgentRuleRequest {

    @Schema(description = "触发类型 (SOP_UPLOAD, BATCH_COMPLETE, QUALITY_ALERT, SCHEDULE_CHANGE)",
            example = "SOP_UPLOAD", requiredMode = Schema.RequiredMode.REQUIRED)
    @NotBlank(message = "触发类型不能为空")
    @Size(max = 50, message = "触发类型长度不能超过50个字符")
    private String triggerType;

    @Schema(description = "触发实体 (SOP, SKU, ORDER, BATCH 等)", example = "SOP")
    @Size(max = 50, message = "触发实体长度不能超过50个字符")
    private String triggerEntity;

    @Schema(description = "规则名称", example = "SOP上传自动解析",
            requiredMode = Schema.RequiredMode.REQUIRED)
    @NotBlank(message = "规则名称不能为空")
    @Size(max = 100, message = "规则名称长度不能超过100个字符")
    private String ruleName;

    @Schema(description = "规则描述")
    private String ruleDescription;

    @Schema(description = "工具链配置 (JSON 字符串)",
            requiredMode = Schema.RequiredMode.REQUIRED,
            example = "{\"executionOrder\":\"SEQUENTIAL\",\"tools\":[...]}")
    @NotBlank(message = "工具链配置不能为空")
    private String toolChainConfig;

    @Schema(description = "是否使用 LLM 动态选择工具, 不传时由服务端默认 false", example = "false")
    private Boolean useLlmSelection;

    @Schema(description = "LLM 选择工具的 Prompt")
    private String llmSelectionPrompt;

    @Schema(description = "条件表达式 (SpEL)", example = "${sopType} == 'PRODUCTION'")
    @Size(max = 500, message = "条件表达式长度不能超过500个字符")
    private String conditionExpression;

    @Schema(description = "优先级 (数值越小越优先匹配), 不传时由服务端默认 100", example = "100")
    private Integer priority;

    @Schema(description = "是否启用, 不传时由服务端默认 true", example = "true")
    private Boolean isActive;
}
