"""Bit-exact parity tests for _java_string_hashcode + _JavaRandom.

These helpers mirror Java's ``java.lang.String.hashCode()`` (signed 32-bit
polynomial hash) and ``java.util.Random`` (48-bit LCG) so Python ports of
SmartBI mock-data generators (production / quality endpoints, T6.6 Phase B)
can produce byte-shape-identical JSON without spinning up a JVM.

Golden values come from ``tests/fixtures/java-random-reference.json``,
generated by ``tests/fixtures/JavaRandomReferenceDump.java`` running on
Azul JDK 21.0.10. Re-generate via:

    java backend/python/tests/fixtures/JavaRandomReferenceDump.java \\
      > backend/python/tests/fixtures/java-random-reference.json

The fixture stores ``next_double`` results as 16-char hex of
``Double.doubleToRawLongBits`` to preserve the full 53-bit mantissa across
JSON round-trips.
"""
from __future__ import annotations

import json
import struct
from pathlib import Path

import pytest

from smartbi_compat._java_compat import _JavaRandom, _java_string_hashcode

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "java-random-reference.json"


@pytest.fixture(scope="module")
def java_reference():
    with FIXTURE_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def _hex_bits_to_double(hex_bits: str) -> float:
    """Convert 16-char hex of doubleToRawLongBits back to Python float."""
    raw = struct.pack(">Q", int(hex_bits, 16))
    return struct.unpack(">d", raw)[0]


# ---------------------------------------------------------------------------
# _java_string_hashcode
# ---------------------------------------------------------------------------


class TestJavaStringHashcode:
    def test_empty_string(self):
        assert _java_string_hashcode("") == 0

    def test_single_char_ascii(self):
        # Java: h = 31*0 + 'a' = 97
        assert _java_string_hashcode("a") == 97

    def test_two_chars(self):
        # h = 31*0 + 'a' = 97;  h = 31*97 + 'b' = 3007 + 98 = 3105
        assert _java_string_hashcode("ab") == 3105

    def test_factory_id_f001(self):
        # Real Java JDK 21 reference value (PR #199 §3.3 quoted 2153483 —
        # that was a spec drift; actual is 2133035).
        assert _java_string_hashcode("F001") == 2133035

    def test_well_known_collision(self):
        # 'AaAa' and 'BBBB' both hash to 2031744 in Java — the canonical
        # textbook collision used to demonstrate the polynomial's weakness.
        assert _java_string_hashcode("AaAa") == 2031744
        assert _java_string_hashcode("BBBB") == 2031744

    def test_returns_signed_int32_negative(self):
        # FOOD_3101_001 / TEST_0000_001 hash to negative int32 in Java.
        assert _java_string_hashcode("FOOD_3101_001") == -1714125422
        assert _java_string_hashcode("TEST_0000_001") == -2086637953

    def test_chinese_bmp_chars(self):
        # 中=0x4E2D=20013, 文=0x6587=25991
        # h = 31*0 + 20013 = 20013
        # h = 31*20013 + 25991 = 620403 + 25991 = 646394
        assert _java_string_hashcode("中文") == 646394

    def test_chinese_three_chars(self):
        assert _java_string_hashcode("白垩纪") == 29878110

    def test_all_fixture_values(self, java_reference):
        """Sweep every golden value from the Java reference dump."""
        mismatches = []
        for s, expected in java_reference["hashcode"].items():
            actual = _java_string_hashcode(s)
            if actual != expected:
                mismatches.append((s, expected, actual))
        assert not mismatches, f"hashcode mismatches: {mismatches}"

    def test_signed_int32_bounds(self, java_reference):
        """Every output must fit in signed int32 [-2^31, 2^31-1]."""
        lo, hi = -(2**31), (2**31) - 1
        for s in java_reference["hashcode"]:
            h = _java_string_hashcode(s)
            assert lo <= h <= hi, f"{s!r} hashed to {h}, out of int32 range"


# ---------------------------------------------------------------------------
# _JavaRandom — initialization + invariants
# ---------------------------------------------------------------------------


class TestJavaRandomInit:
    def test_seed_xor_scramble(self):
        # JDK source: this.seed = (seed ^ 0x5DEECE66DL) & MASK
        rng = _JavaRandom(0)
        assert rng.seed == (0 ^ 0x5DEECE66D) & ((1 << 48) - 1)

    def test_seed_int_overflow_handled(self):
        # Negative seeds (e.g. hash codes for "RES_3101_001" = -126594128)
        # must not crash and must produce same output as Java new Random(-126594128).
        rng = _JavaRandom(-126594128)
        # next() should return some valid 31-bit int
        v = rng._next(31)
        assert 0 <= v < (1 << 31)


# ---------------------------------------------------------------------------
# _JavaRandom.next_int — power-of-2 fast path
# ---------------------------------------------------------------------------


class TestNextIntPowerOfTwo:
    @pytest.mark.parametrize("bound", [1, 2, 8, 16])
    def test_seed_zero_sequence(self, bound, java_reference):
        seq = java_reference["random_sequences"][0]  # seed=0
        assert seq["seed"] == 0
        expected = seq[f"next_int_{bound}"]
        rng = _JavaRandom(0)
        actual = [rng.next_int(bound) for _ in range(len(expected))]
        assert actual == expected

    def test_bound_one_always_zero(self):
        # JDK fast path: bound is power of 2 → (bound * _next(31)) >> 31
        # For bound=1, that's _next(31) >> 31, always 0 (31-bit value shifted right 31).
        rng = _JavaRandom(42)
        assert all(rng.next_int(1) == 0 for _ in range(20))


# ---------------------------------------------------------------------------
# _JavaRandom.next_int — rejection-sampling path (non-power-of-2)
# ---------------------------------------------------------------------------


class TestNextIntRejection:
    @pytest.mark.parametrize("bound", [3, 5, 7, 100, 1024])
    def test_seed_zero_sequence(self, bound, java_reference):
        seq = java_reference["random_sequences"][0]
        assert seq["seed"] == 0
        expected = seq[f"next_int_{bound}"]
        rng = _JavaRandom(0)
        actual = [rng.next_int(bound) for _ in range(len(expected))]
        assert actual == expected

    def test_all_seeds_all_bounds(self, java_reference):
        """Sweep every seed × every recorded bound. Catches LCG state drift."""
        bounds_to_check = [2, 3, 5, 7, 8, 16, 100, 1024]
        mismatches = []
        for seq in java_reference["random_sequences"]:
            seed = seq["seed"]
            for bound in bounds_to_check:
                expected = seq[f"next_int_{bound}"]
                rng = _JavaRandom(seed)
                actual = [rng.next_int(bound) for _ in range(len(expected))]
                if actual != expected:
                    mismatches.append({"seed": seed, "bound": bound,
                                       "expected": expected[:5],
                                       "actual": actual[:5]})
        assert not mismatches, f"next_int mismatches: {mismatches[:3]}"


# ---------------------------------------------------------------------------
# _JavaRandom.next_int — error paths
# ---------------------------------------------------------------------------


class TestNextIntInvalidBound:
    def test_zero_bound_raises(self):
        rng = _JavaRandom(0)
        with pytest.raises(ValueError):
            rng.next_int(0)

    def test_negative_bound_raises(self):
        rng = _JavaRandom(0)
        with pytest.raises(ValueError):
            rng.next_int(-1)


# ---------------------------------------------------------------------------
# _JavaRandom.next_double — bit-exact via raw bits
# ---------------------------------------------------------------------------


class TestNextDouble:
    def test_range_is_unit_interval(self):
        rng = _JavaRandom(123)
        for _ in range(100):
            d = rng.next_double()
            assert 0.0 <= d < 1.0

    def test_seed_zero_first_thirty_bit_exact(self, java_reference):
        seq = java_reference["random_sequences"][0]
        assert seq["seed"] == 0
        expected_hex = seq["next_double_30"]
        rng = _JavaRandom(0)
        for i, hex_bits in enumerate(expected_hex):
            expected = _hex_bits_to_double(hex_bits)
            actual = rng.next_double()
            # Bit-exact comparison via raw bits.
            ea = struct.pack(">d", expected)
            ab = struct.pack(">d", actual)
            assert ea == ab, (
                f"next_double[{i}] differs: expected={expected!r} (bits={hex_bits}) "
                f"actual={actual!r} (bits={ab.hex()})"
            )

    def test_all_seeds_bit_exact(self, java_reference):
        mismatches = []
        for seq in java_reference["random_sequences"]:
            seed = seq["seed"]
            rng = _JavaRandom(seed)
            for i, hex_bits in enumerate(seq["next_double_30"]):
                expected = _hex_bits_to_double(hex_bits)
                actual = rng.next_double()
                if struct.pack(">d", expected) != struct.pack(">d", actual):
                    mismatches.append({"seed": seed, "i": i,
                                       "expected_hex": hex_bits,
                                       "actual": actual})
                    break  # one fail per seed is enough to flag drift
        assert not mismatches, f"next_double mismatches: {mismatches[:3]}"


# ---------------------------------------------------------------------------
# Production / quality mock-generator usage pattern
# ---------------------------------------------------------------------------


class TestMockGeneratorPattern:
    """Verifies the 7-call-per-record consumption order used by Java's
    generateMockProductionData / generateMockQualityData. Order:

        1. nextInt(8)      — plannedRuntime offset
        2. nextDouble()    — downtime raw value
        3. nextInt(100)    — theoreticalOutput offset
        4. nextDouble()    — actualOutput multiplier
        5. nextDouble()    — goodUnits multiplier
        6. nextInt(3)      — failureCount
        7. nextInt(5)      — downtimeReason index
    """

    def test_seed_zero_five_records(self, java_reference):
        seq = java_reference["random_sequences"][0]
        assert seq["seed"] == 0
        rng = _JavaRandom(0)
        for i, expected in enumerate(seq["mixed_records_5"]):
            assert rng.next_int(8) == expected["plannedRuntime"], f"rec {i} plannedRuntime"
            d_actual = rng.next_double()
            d_expected = _hex_bits_to_double(expected["downtime"])
            assert struct.pack(">d", d_actual) == struct.pack(">d", d_expected), \
                f"rec {i} downtime"
            assert rng.next_int(100) == expected["theoreticalOutput"], f"rec {i} theoreticalOutput"
            am_actual = rng.next_double()
            am_expected = _hex_bits_to_double(expected["actualOutputMult"])
            assert struct.pack(">d", am_actual) == struct.pack(">d", am_expected), \
                f"rec {i} actualOutputMult"
            gm_actual = rng.next_double()
            gm_expected = _hex_bits_to_double(expected["goodUnitsMult"])
            assert struct.pack(">d", gm_actual) == struct.pack(">d", gm_expected), \
                f"rec {i} goodUnitsMult"
            assert rng.next_int(3) == expected["failureCount"], f"rec {i} failureCount"
            assert rng.next_int(5) == expected["downtimeReason"], f"rec {i} downtimeReason"

    def test_all_seeds_mixed_pattern(self, java_reference):
        """Every seed in the fixture must reproduce its 5-record mixed sequence."""
        mismatches = []
        for seq in java_reference["random_sequences"]:
            seed = seq["seed"]
            rng = _JavaRandom(seed)
            for i, expected in enumerate(seq["mixed_records_5"]):
                checks = [
                    ("plannedRuntime", rng.next_int(8), expected["plannedRuntime"], "int"),
                    ("downtime", rng.next_double(), expected["downtime"], "double"),
                    ("theoreticalOutput", rng.next_int(100), expected["theoreticalOutput"], "int"),
                    ("actualOutputMult", rng.next_double(), expected["actualOutputMult"], "double"),
                    ("goodUnitsMult", rng.next_double(), expected["goodUnitsMult"], "double"),
                    ("failureCount", rng.next_int(3), expected["failureCount"], "int"),
                    ("downtimeReason", rng.next_int(5), expected["downtimeReason"], "int"),
                ]
                for name, actual, exp, kind in checks:
                    if kind == "int":
                        if actual != exp:
                            mismatches.append({"seed": seed, "rec": i,
                                               "field": name,
                                               "expected": exp, "actual": actual})
                    else:  # double via hex bits
                        e = _hex_bits_to_double(exp)
                        if struct.pack(">d", actual) != struct.pack(">d", e):
                            mismatches.append({"seed": seed, "rec": i,
                                               "field": name,
                                               "expected_hex": exp, "actual": actual})
        assert not mismatches, f"mixed pattern mismatches: {mismatches[:3]}"


# ---------------------------------------------------------------------------
# Factory-id seed end-to-end (the actual production usage)
# ---------------------------------------------------------------------------


class TestFactoryIdSeed:
    """Real production usage: seed = factoryId.hashCode(). Verifies the
    composition of _java_string_hashcode + _JavaRandom matches Java behavior."""

    @pytest.mark.parametrize(
        "factory_id, expected_first_int_8",
        [
            # First nextInt(8) value for each factory_id, captured from the
            # fixture's random_sequences entries seeded by hashCode("F001"), etc.
            # Values verified via: jq '.random_sequences[] | select(.seed == HASH).next_int_8[0]'
            ("F001", 0),
            ("F002", 0),
            ("F999", 2),
            ("RES_3101_001", 2),
            ("RES_GML_001", 0),
        ],
    )
    def test_factory_seed_matches(self, factory_id, expected_first_int_8, java_reference):
        seed = _java_string_hashcode(factory_id)
        rng = _JavaRandom(seed)
        first = rng.next_int(8)
        # Cross-check against the fixture's recorded sequence for this seed.
        seq = next(s for s in java_reference["random_sequences"] if s["seed"] == seed)
        assert first == seq["next_int_8"][0]
        assert first == expected_first_int_8
