package com.cretas.aims.entity;

import lombok.*;

import javax.persistence.*;
import java.time.LocalDateTime;

/**
 * AI分析结果实体 - 存储多层级AI成本分析报告
 * 支持批次、周报、月报、历史综合报告
 *
 * 报告类型及保留期：
 * - batch: 批次成本分析（7天）
 * - weekly: 周报告（30天，每周一自动生成）
 * - monthly: 月报告（90天，每月1日自动生成）
 * - historical: 历史综合报告（90天，按需生成）
 *
 * @author Cretas Team
 * @version 2.0.0
 * @since 2025-11-04
 */
@Entity
@Table(name = "ai_analysis_results",
       indexes = {
           @Index(name = "idx_factory_type_expires", columnList = "factory_id,report_type,expires_at"),
           @Index(name = "idx_batch_id", columnList = "batch_id"),
           @Index(name = "idx_factory_batch", columnList = "factory_id,batch_id")
       })
@Data
@EqualsAndHashCode(callSuper = false)
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AIAnalysisResult extends BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * 工厂ID（必填）
     */
    @Column(name = "factory_id", nullable = false, length = 50)
    private String factoryId;

    /**
     * 批次ID（聚合报告时可为空）
     */
    @Column(name = "batch_id", length = 50)
    private String batchId;

    /**
     * 报告类型
     * - batch: 批次成本分析（7天）
     * - weekly: 周报告（30天）
     * - monthly: 月报告（90天）
     * - historical: 历史综合报告（90天）
     */
    @Builder.Default
    @Column(name = "report_type", nullable = false, length = 20)
    private String reportType = "batch";

    /**
     * AI分析结果文本（Markdown格式）
     */
    @Column(name = "analysis_text", columnDefinition = "TEXT")
    private String analysisText;

    /**
     * 生成时的Python Session ID（用于追溯）
     */
    @Column(name = "session_id", length = 100)
    private String sessionId;

    /**
     * 报告期间开始时间（周报/月报使用）
     */
    @Column(name = "period_start")
    private LocalDateTime periodStart;

    /**
     * 报告期间结束时间（周报/月报使用）
     */
    @Column(name = "period_end")
    private LocalDateTime periodEnd;

    /**
     * 过期时间（根据报告类型自动计算）
     * batch: +7天, weekly: +30天, monthly/historical: +90天
     */
    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    /**
     * 是否由定时任务自动生成
     */
    @Builder.Default
    @Column(name = "is_auto_generated", nullable = false)
    private Boolean isAutoGenerated = false;
}
