package com.cretas.aims.entity.bom;

import com.cretas.aims.entity.BaseEntity;
import com.cretas.aims.security.PriceSensitive;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;
import org.hibernate.annotations.Where;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * M-BOM-1 BOM 配方头 (主表).
 *
 * <p>取代 {@link BomItem} 单表设计 (后者兼容期保留 30 天).
 *
 * <p>核心字段:
 * <ul>
 *   <li>{@code id} — VARCHAR(191) UUID, by {@link #assignUUID()} on persist</li>
 *   <li>{@code recipeCode} — {@code BOM-YYYYMMDD-NNN} 自动生成 (Service 层)</li>
 *   <li>{@code version} + {@code isCurrent} — 同产品多版本支持, partial unique index 保证</li>
 *   <li>{@code overallYieldRate} — 整产品级出成率 (vs item-level)</li>
 *   <li>{@code outputQuantityPerUnit} — 单份成品克数/件数 (客户: "成品 200g")</li>
 *   <li>5 个 @PriceSensitive 成本字段 (RBAC strip by PriceFieldResponseAdvice)</li>
 *   <li>{@code status} — DRAFT/ACTIVE/ARCHIVED 状态机</li>
 *   <li>{@code sourceType} — MANUAL/SAMPLE_AUTOGEN/AI_GENERATED/IMPORTED</li>
 * </ul>
 *
 * <p>关联: 1:N {@link BomRecipeItem} (LAZY + orphanRemoval).
 *
 * @author Cretas Team / Track D1
 * @since 2026-05-14
 */
@Entity
@Table(name = "bom_recipes", indexes = {
    @Index(name = "idx_br_factory_product", columnList = "factory_id, product_type_id"),
    @Index(name = "idx_br_status",          columnList = "factory_id, status")
})
@Data
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Where(clause = "deleted_at IS NULL")
public class BomRecipe extends BaseEntity {

    @Id
    @Column(name = "id", nullable = false, length = 191)
    private String id;

    @PrePersist
    void assignUUID() {
        if (id == null) {
            id = UUID.randomUUID().toString();
        }
    }

    @Column(name = "factory_id", nullable = false, length = 50)
    private String factoryId;

    /** {@code BOM-YYYYMMDD-NNN}, generated by service on create. */
    @Column(name = "recipe_code", nullable = false, length = 50)
    private String recipeCode;

    @Column(name = "product_type_id", nullable = false, length = 50)
    private String productTypeId;

    @Column(name = "product_name", nullable = false, length = 200)
    private String productName;

    @Column(name = "version", nullable = false)
    @Builder.Default
    private Integer version = 1;

    @Column(name = "is_current", nullable = false)
    @Builder.Default
    private Boolean isCurrent = true;

    /** 整产品级出成率 0-100%. */
    @Column(name = "overall_yield_rate", precision = 6, scale = 2)
    @Builder.Default
    private BigDecimal overallYieldRate = new BigDecimal("100.00");

    /** 单份成品克数/件数 (200g/份, 1个/份). */
    @Column(name = "output_quantity_per_unit", nullable = false, precision = 15, scale = 4)
    private BigDecimal outputQuantityPerUnit;

    @Column(name = "output_unit", nullable = false, length = 20)
    @Builder.Default
    private String outputUnit = "g";

    /** Sum of bom_recipe_items.itemCost. @PriceSensitive: stripped for non-procurement-price roles. */
    @PriceSensitive
    @Column(name = "total_material_cost", precision = 15, scale = 4)
    private BigDecimal totalMaterialCost;

    @PriceSensitive
    @Column(name = "total_labor_cost", precision = 15, scale = 4)
    private BigDecimal totalLaborCost;

    @PriceSensitive
    @Column(name = "total_overhead_cost", precision = 15, scale = 4)
    private BigDecimal totalOverheadCost;

    @PriceSensitive
    @Column(name = "total_cost", precision = 15, scale = 4)
    private BigDecimal totalCost;

    @PriceSensitive
    @Column(name = "standard_sale_price", precision = 15, scale = 2)
    private BigDecimal standardSalePrice;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 32)
    @Builder.Default
    private Status status = Status.DRAFT;

    @Column(name = "activated_at")
    private LocalDateTime activatedAt;

    @Column(name = "activated_by")
    private Long activatedBy;

    @Enumerated(EnumType.STRING)
    @Column(name = "source_type", nullable = false, length = 20)
    @Builder.Default
    private SourceType sourceType = SourceType.MANUAL;

    @Column(name = "source_sample_id", length = 191)
    private String sourceSampleId;

    @Column(name = "notes", length = 500)
    private String notes;

    @OneToMany(mappedBy = "recipe", cascade = CascadeType.ALL, fetch = FetchType.LAZY, orphanRemoval = true)
    @OrderBy("sortOrder ASC")
    @Builder.Default
    private List<BomRecipeItem> items = new ArrayList<>();

    public enum Status { DRAFT, ACTIVE, ARCHIVED }

    public enum SourceType { MANUAL, SAMPLE_AUTOGEN, AI_GENERATED, IMPORTED }
}
