package com.cretas.aims.entity.bom;

import com.cretas.aims.entity.BaseEntity;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import io.hypersistence.utils.hibernate.type.json.JsonBinaryType;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;
import org.hibernate.annotations.Type;
import org.hibernate.annotations.Where;

import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * M-BOM-VER-1 工程变更通知 (ECN, Sprint 3 Track-H).
 *
 * <p>BOM 配方变更必填变更原因 (5 类) + 影响范围 + 通知列表 + 审批链路. ECN 审批通过后
 * cascade trigger 关联 {@link BomVersion} 由 PENDING_APPROVAL → APPROVED.
 *
 * <p>5 reason 来源 (宏见 deep-audit Round 5 实测):
 * <ul>
 *   <li>{@link EcnReason#CUSTOMER_REQUEST} — 客户要求 (规格变更 / 包装变更)</li>
 *   <li>{@link EcnReason#MATERIAL_DISCONTINUED} — 物料停产 / 供应商断货</li>
 *   <li>{@link EcnReason#COST_OPTIMIZATION} — 成本优化 (替换为低价等效物料)</li>
 *   <li>{@link EcnReason#QUALITY_DEFECT} — 质量缺陷 (现行 BOM 引发品质问题需调整)</li>
 *   <li>{@link EcnReason#PROCESS_IMPROVEMENT} — 工艺改进 (出成率优化 / 流程精简)</li>
 * </ul>
 *
 * <p>状态机:
 * <pre>
 *   DRAFT ─ submit ─→ SUBMITTED ─ approve ──→ APPROVED ─(effective_date 到期)─→ EFFECTIVE
 *                                  │
 *                                  └── reject ─→ REJECTED (terminal)
 * </pre>
 *
 * <p>审批链路: {@link #approvalChainId} 可选指向 {@code approval_chain_configs.id}. null 时
 * {@code ECNService} 走 hardcoded 默认 chain (role list: factory_super_admin / production_admin).
 * Track-I C-APPROVAL-EDITOR ship 后用户可视化编辑.
 *
 * <p>历史 BOM 追溯: {@link #effectiveDate} 生效日期之前的历史订单仍走旧 BOM 版本,
 * {@code BomVersionService.getEffectiveAt(bomRecipeId, date)} 走此规则.
 *
 * @author Cretas Team / Sprint 3 Track-H
 * @since 2026-05-16
 */
@Entity
@Table(name = "engineering_change_notices", indexes = {
    @Index(name = "idx_ecn_factory_number",   columnList = "factory_id, ecn_number", unique = true),
    @Index(name = "idx_ecn_recipe",           columnList = "bom_recipe_id"),
    @Index(name = "idx_ecn_factory_status",   columnList = "factory_id, status"),
    @Index(name = "idx_ecn_effective_date",   columnList = "factory_id, effective_date")
})
@Data
@SuperBuilder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Where(clause = "deleted_at IS NULL")
public class EngineeringChangeNotice extends BaseEntity {

    @Id
    @Column(name = "id", nullable = false, length = 191)
    private String id;

    @PrePersist
    void assignUUID() {
        if (id == null) {
            id = UUID.randomUUID().toString();
        }
    }

    @Column(name = "factory_id", nullable = false, length = 50)
    private String factoryId;

    /** {@code ECN-YYYY-NNNN}, auto-generated by ECNService. Unique per factory. */
    @Column(name = "ecn_number", nullable = false, length = 50)
    private String ecnNumber;

    /** Logical FK to {@code bom_recipes.id}. */
    @Column(name = "bom_recipe_id", nullable = false, length = 191)
    private String bomRecipeId;

    /** From version (null = first version creation, no prior). */
    @Column(name = "from_version")
    private Integer fromVersion;

    /** Target version after this ECN takes effect. */
    @Column(name = "to_version", nullable = false)
    private Integer toVersion;

    @Enumerated(EnumType.STRING)
    @Column(name = "reason", nullable = false, length = 32)
    private EcnReason reason;

    @Column(name = "reason_detail", columnDefinition = "TEXT")
    private String reasonDetail;

    /**
     * Impact scope JSON. Computed by {@code ECNService.calculateImpact()}.
     *
     * <p>Shape: {@code {"affectedSkus": ["SKU-201", ...], "affectedCustomers": ["CUST-007", ...],
     *                   "openOrderCount": 12, "openOrderSummary": [...]} }
     */
    @Type(JsonBinaryType.class)
    @Column(name = "impact_scope", columnDefinition = "jsonb")
    private Map<String, Object> impactScope;

    /**
     * Role codes to notify on ECN events. Default: {@code ["production","procurement","quality","sales"]}.
     */
    @Type(JsonBinaryType.class)
    @Column(name = "notify_roles", columnDefinition = "jsonb")
    private List<String> notifyRoles;

    /**
     * Effective date — historical orders before this still use prior BOM version.
     * Required when status=APPROVED.
     */
    @Column(name = "effective_date")
    private LocalDate effectiveDate;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 32)
    @Builder.Default
    private EcnStatus status = EcnStatus.DRAFT;

    /**
     * Logical FK to {@code approval_chain_configs.id}.
     * null = use hardcoded default chain in ECNService until Track-I editor ships.
     */
    @Column(name = "approval_chain_id", length = 191)
    private String approvalChainId;

    @Column(name = "created_by")
    private Long createdBy;

    @Column(name = "approved_by")
    private Long approvedBy;

    @Column(name = "approved_at")
    private Instant approvedAt;

    /** Rejection reason (only set when status=REJECTED). */
    @Column(name = "rejection_reason", columnDefinition = "TEXT")
    private String rejectionReason;

    /** ECN 5 reason categories per brief / 宏见 deep-audit Round 5. */
    public enum EcnReason {
        CUSTOMER_REQUEST,
        MATERIAL_DISCONTINUED,
        COST_OPTIMIZATION,
        QUALITY_DEFECT,
        PROCESS_IMPROVEMENT
    }

    /**
     * ECN state machine. {@code EFFECTIVE} represents the post-effective_date state where
     * the new BOM version is now in active production use.
     */
    public enum EcnStatus {
        DRAFT,
        SUBMITTED,
        APPROVED,
        REJECTED,
        EFFECTIVE
    }
}
