package com.cretas.aims.service.impl;

import com.cretas.aims.dto.common.PageRequest;
import com.cretas.aims.dto.common.PageResponse;
import com.cretas.aims.entity.*;
import com.cretas.aims.entity.enums.*;
import com.cretas.aims.exception.BusinessException;
import com.cretas.aims.exception.ResourceNotFoundException;
import com.cretas.aims.repository.*;
import com.cretas.aims.service.ProcessingService;
import com.cretas.aims.service.ProcessingStageRecordService;
import com.cretas.aims.service.AIAnalysisService;
import com.cretas.aims.service.CacheService;
import com.cretas.aims.dto.processing.ProcessingStageRecordDTO;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.HashSet;
import java.util.Set;
import java.util.stream.Collectors;
/**
 * 生产加工服务实现类
 *
 * @author Cretas Team
 * @version 1.0.0
 * @since 2025-01-09
 */
@Service
@RequiredArgsConstructor
public class ProcessingServiceImpl implements ProcessingService {
    private static final Logger log = LoggerFactory.getLogger(ProcessingServiceImpl.class);

    private final ProductionBatchRepository productionBatchRepository;
    private final MaterialBatchRepository materialBatchRepository;
    private final MaterialConsumptionRepository materialConsumptionRepository;
    private final QualityInspectionRepository qualityInspectionRepository;
    private final EquipmentRepository equipmentRepository;
    private final EquipmentAlertRepository equipmentAlertRepository;
    private final BatchEquipmentUsageRepository batchEquipmentUsageRepository;
    private final ProductionPlanRepository productionPlanRepository;
    private final SystemLogRepository systemLogRepository;
    private final RawMaterialTypeRepository rawMaterialTypeRepository;
    private final BatchWorkSessionRepository batchWorkSessionRepository;
    private final UserRepository userRepository;
    private final SupplierRepository supplierRepository;
    private final AIAnalysisService aiAnalysisService;
    private final CacheService cacheService;
    private final ProcessingStageRecordService processingStageRecordService;
    // ========== 批次管理 ==========
    @Override
    @Transactional
    public ProductionBatch createBatch(String factoryId, ProductionBatch batch) {
        log.info("创建生产批次: factoryId={}, batchNumber={}", factoryId, batch.getBatchNumber());
        // 验证批次号唯一性
        if (productionBatchRepository.existsByFactoryIdAndBatchNumber(factoryId, batch.getBatchNumber())) {
            throw new BusinessException("批次号已存在: " + batch.getBatchNumber());
        }

        // ID is auto-generated by database (IDENTITY strategy), no need to set manually
        batch.setFactoryId(factoryId);
        batch.setStatus(ProductionBatchStatus.PLANNED);
        batch.setCreatedAt(LocalDateTime.now());

        // 设置必填字段的默认值
        if (batch.getProductName() == null || batch.getProductName().isEmpty()) {
            batch.setProductName("待设置产品名称");
        }
        if (batch.getQuantity() == null) {
            batch.setQuantity(batch.getPlannedQuantity() != null ? batch.getPlannedQuantity() : BigDecimal.ZERO);
        }
        if (batch.getUnit() == null || batch.getUnit().isEmpty()) {
            batch.setUnit("kg");
        }

        return productionBatchRepository.save(batch);
    }
    public ProductionBatch startProduction(String factoryId, String batchId, Integer supervisorId) {
        log.info("开始生产: factoryId={}, batchId={}, supervisorId={}", factoryId, batchId, supervisorId);
        Long id = Long.parseLong(batchId);
        ProductionBatch batch = productionBatchRepository.findByIdAndFactoryId(id, factoryId)
                .orElseThrow(() -> new ResourceNotFoundException("批次不存在"));
        if (ProductionBatchStatus.PLANNED != batch.getStatus()) {
            throw new BusinessException("批次状态不允许开始生产: " + batch.getStatus());
        }
        batch.setStatus(ProductionBatchStatus.IN_PROGRESS);
        batch.setStartTime(LocalDateTime.now());
        batch.setSupervisorId(supervisorId != null ? supervisorId.longValue() : null);
        return productionBatchRepository.save(batch);
    }
    public ProductionBatch pauseProduction(String factoryId, String batchId, String reason) {
        log.info("暂停生产: factoryId={}, batchId={}, reason={}", factoryId, batchId, reason);
        Long id = Long.parseLong(batchId);
        ProductionBatch batch = productionBatchRepository.findByIdAndFactoryId(id, factoryId)
                .orElseThrow(() -> new ResourceNotFoundException("批次不存在"));
        if (ProductionBatchStatus.IN_PROGRESS != batch.getStatus()) {
            throw new BusinessException("只有进行中的批次可以暂停");
        }
        batch.setStatus(ProductionBatchStatus.PAUSED);
        batch.setNotes(batch.getNotes() != null ? batch.getNotes() + "\n暂停原因: " + reason : "暂停原因: " + reason);
        return productionBatchRepository.save(batch);
    }
    public ProductionBatch completeProduction(String factoryId, String batchId, BigDecimal actualQuantity,
                                             BigDecimal goodQuantity, BigDecimal defectQuantity) {
        log.info("完成生产: factoryId={}, batchId={}, actualQuantity={}", factoryId, batchId, actualQuantity);
        Long id = Long.parseLong(batchId);
        ProductionBatch batch = productionBatchRepository.findByIdAndFactoryId(id, factoryId)
                .orElseThrow(() -> new ResourceNotFoundException("批次不存在"));
        if (ProductionBatchStatus.IN_PROGRESS != batch.getStatus() &&
            ProductionBatchStatus.PAUSED != batch.getStatus()) {
            throw new BusinessException("批次状态不允许完成生产: " + batch.getStatus());
        }
        batch.setStatus(ProductionBatchStatus.COMPLETED);
        batch.setEndTime(LocalDateTime.now());
        batch.setActualQuantity(actualQuantity);
        batch.setGoodQuantity(goodQuantity);
        batch.setDefectQuantity(defectQuantity);
        // 计算指标
        batch.calculateMetrics();
        return productionBatchRepository.save(batch);
    }
    public ProductionBatch cancelProduction(String factoryId, String batchId, String reason) {
        log.info("取消生产: factoryId={}, batchId={}, reason={}", factoryId, batchId, reason);
        Long id = Long.parseLong(batchId);
        ProductionBatch batch = productionBatchRepository.findByIdAndFactoryId(id, factoryId)
                .orElseThrow(() -> new ResourceNotFoundException("批次不存在"));
        if (ProductionBatchStatus.COMPLETED == batch.getStatus()) {
            throw new BusinessException("已完成的批次不能取消");
        }
        batch.setStatus(ProductionBatchStatus.CANCELLED);
        batch.setNotes(batch.getNotes() != null ? batch.getNotes() + "\n取消原因: " + reason : "取消原因: " + reason);
        return productionBatchRepository.save(batch);
    }
    public ProductionBatch getBatchById(String factoryId, String batchId) {
        Long id = Long.parseLong(batchId);
        return productionBatchRepository.findByIdAndFactoryId(id, factoryId)
                .orElseThrow(() -> new ResourceNotFoundException("批次不存在"));
    }
    public PageResponse<ProductionBatch> getBatches(String factoryId, String status, PageRequest pageRequest) {
        org.springframework.data.domain.PageRequest pageable = org.springframework.data.domain.PageRequest.of(
                pageRequest.getPage() - 1,
                pageRequest.getSize(),
                Sort.by(Sort.Direction.DESC, "createdAt")
        );
        Page<ProductionBatch> page;
        if (status != null && !status.isEmpty()) {
            // 将字符串状态转换为枚举
            ProductionBatchStatus statusEnum = ProductionBatchStatus.valueOf(status.toUpperCase());
            page = productionBatchRepository.findByFactoryIdAndStatus(factoryId, statusEnum, pageable);
        } else {
            page = productionBatchRepository.findByFactoryId(factoryId, pageable);
        }
        return PageResponse.of(
                page.getContent(),
                pageRequest.getPage(),
                pageRequest.getSize(),
                page.getTotalElements()
        );
    }
    public List<Map<String, Object>> getBatchTimeline(String factoryId, String batchId) {
        ProductionBatch batch = getBatchById(factoryId, batchId);
        List<Map<String, Object>> timeline = new ArrayList<>();
        // 创建时间点
        Map<String, Object> created = new HashMap<>();
        created.put("time", batch.getCreatedAt());
        created.put("event", "批次创建");
        created.put("status", "PLANNED");
        timeline.add(created);
        // 开始生产时间点
        if (batch.getStartTime() != null) {
            Map<String, Object> started = new HashMap<>();
            started.put("time", batch.getStartTime());
            started.put("event", "开始生产");
            started.put("status", "IN_PROGRESS");
            timeline.add(started);
        }
        // 结束时间点
        if (batch.getEndTime() != null) {
            Map<String, Object> ended = new HashMap<>();
            ended.put("time", batch.getEndTime());
            ended.put("event", "COMPLETED".equals(batch.getStatus()) ? "生产完成" : "生产取消");
            ended.put("status", batch.getStatus());
            timeline.add(ended);
        }
        return timeline;
    }
    // ========== 原材料管理 ==========
    public MaterialBatch createMaterialReceipt(String factoryId, MaterialBatch materialBatch) {
        log.info("创建原材料接收记录: factoryId={}, batchNumber={}", factoryId, materialBatch.getBatchNumber());
        if (materialBatchRepository.existsByFactoryIdAndBatchNumber(factoryId, materialBatch.getBatchNumber())) {
            throw new BusinessException("原材料批次号已存在: " + materialBatch.getBatchNumber());
        }

        // 获取初始数量（支持多种字段名）
        BigDecimal initialQty = materialBatch.getInitialQuantity();
        if (initialQty == null) {
            throw new BusinessException("原材料数量不能为空");
        }

        // 从原材料类型获取单位
        if (materialBatch.getMaterialType() != null && materialBatch.getMaterialType().getId() != null) {
            RawMaterialType materialType = rawMaterialTypeRepository.findById(materialBatch.getMaterialType().getId())
                    .orElseThrow(() -> new ResourceNotFoundException("原材料类型不存在"));
            materialBatch.setQuantityUnit(materialType.getUnit());  // 设置数量单位
        } else if (materialBatch.getQuantityUnit() == null) {
            // 如果没有原材料类型且没有单位，使用默认值
            materialBatch.setQuantityUnit("公斤");
        }

        materialBatch.setFactoryId(factoryId);
        materialBatch.setStatus(MaterialBatchStatus.AVAILABLE);
        // 注意: initialQuantity, remainingQuantity, currentQuantity, totalQuantity 都是计算属性
        // 只需设置核心字段: receiptQuantity, usedQuantity, reservedQuantity
        materialBatch.setReceiptQuantity(initialQty);  // receiptQuantity 是核心字段
        materialBatch.setUsedQuantity(BigDecimal.ZERO);
        materialBatch.setReservedQuantity(BigDecimal.ZERO);

        // 同步purchase_date遗留字段
        if (materialBatch.getPurchaseDate() == null && materialBatch.getReceiptDate() != null) {
            materialBatch.setPurchaseDate(materialBatch.getReceiptDate());
        }

        // 注意: totalWeight 是计算属性 (weightPerUnit × receiptQuantity)
        // 如果没有提供 weightPerUnit，使用默认值1.0 (表示1kg/单位)
        if (materialBatch.getWeightPerUnit() == null) {
            materialBatch.setWeightPerUnit(BigDecimal.ONE);
        }

        // 注意: totalPrice 和 totalValue 都是计算属性
        // totalPrice = unitPrice × receiptQuantity，会自动计算
        // 只需确保设置了 unitPrice 即可
        if (materialBatch.getUnitPrice() == null) {
            // 如果没有单价，设置默认值0
            materialBatch.setUnitPrice(BigDecimal.ZERO);
        }

        return materialBatchRepository.save(materialBatch);
    }
    public PageResponse<MaterialBatch> getMaterialReceipts(String factoryId, PageRequest pageRequest) {
        org.springframework.data.domain.PageRequest pageable = org.springframework.data.domain.PageRequest.of(
                pageRequest.getPage() - 1,
                pageRequest.getSize(),
                Sort.by(Sort.Direction.DESC, "purchaseDate")
        );
        Page<MaterialBatch> page = materialBatchRepository.findByFactoryId(factoryId, pageable);
        return PageResponse.of(
                page.getContent(),
                pageRequest.getPage(),
                pageRequest.getSize(),
                page.getTotalElements()
        );
    }
    public MaterialBatch updateMaterialReceipt(String factoryId, String batchId, MaterialBatch updates) {
        MaterialBatch batch = materialBatchRepository.findById(batchId)
                .orElseThrow(() -> new ResourceNotFoundException("原材料批次不存在"));
        if (!batch.getFactoryId().equals(factoryId)) {
            throw new BusinessException("无权操作此批次");
        }
        // 更新允许修改的字段
        if (updates.getStorageLocation() != null) {
            batch.setStorageLocation(updates.getStorageLocation());
        }
        if (updates.getQualityCertificate() != null) {
            batch.setQualityCertificate(updates.getQualityCertificate());
        }
        if (updates.getNotes() != null) {
            batch.setNotes(updates.getNotes());
        }
        return materialBatchRepository.save(batch);
    }
    public void recordMaterialConsumption(String factoryId, String productionBatchId,
                                         List<Map<String, Object>> consumptions) {
        log.info("记录原材料消耗: factoryId={}, productionBatchId={}", factoryId, productionBatchId);
        ProductionBatch productionBatch = getBatchById(factoryId, productionBatchId);
        for (Map<String, Object> consumption : consumptions) {
            String materialBatchId = (String) consumption.get("materialBatchId");
            BigDecimal quantity = new BigDecimal(consumption.get("quantity").toString());
            MaterialBatch materialBatch = materialBatchRepository.findById(materialBatchId)
                    .orElseThrow(() -> new ResourceNotFoundException("原材料批次不存在"));
            // 检查库存
            if (materialBatch.getRemainingQuantity().compareTo(quantity) < 0) {
                throw new BusinessException("原材料库存不足: " + materialBatch.getBatchNumber());
            }
            // 更新库存
            // 注意: remainingQuantity 和 currentQuantity 是计算属性，会自动重新计算
            materialBatch.setUsedQuantity(materialBatch.getUsedQuantity().add(quantity));
            materialBatch.setLastUsedAt(LocalDateTime.now());
            // 创建消耗记录
            MaterialConsumption consumptionRecord = new MaterialConsumption();
            // ID使用自动生成策略，不需要手动设置
            consumptionRecord.setFactoryId(factoryId);  // 设置工厂ID (必填字段)
            consumptionRecord.setBatch(materialBatch);
            consumptionRecord.setBatchId(materialBatchId);  // 设置原料批次ID
            // 设置生产计划ID (从生产批次获取，如果没有则使用productionBatchId作为planId)
            String planId = productionBatch.getProductionPlanId() != null
                ? productionBatch.getProductionPlanId().toString()
                : "PLAN-" + productionBatchId;  // 如果没有计划ID，生成一个临时ID
            consumptionRecord.setProductionPlanId(planId);  // 设置生产计划ID (必填字段)
            consumptionRecord.setProductionBatchId(Long.parseLong(productionBatchId));
            consumptionRecord.setQuantity(quantity);
            consumptionRecord.setUnitPrice(materialBatch.getUnitPrice());  // 从原料批次获取单价 (必填字段)
            consumptionRecord.setTotalCost(quantity.multiply(materialBatch.getUnitPrice()));  // 计算总成本 (必填字段)
            consumptionRecord.setConsumptionTime(LocalDateTime.now());  // 设置消耗时间 (必填字段)
            consumptionRecord.setConsumedAt(LocalDateTime.now());
            consumptionRecord.setRecordedBy(productionBatch.getSupervisorId() != null ? productionBatch.getSupervisorId() : 1L);  // 设置记录人 (必填字段，默认使用督导或系统用户)
            materialBatchRepository.save(materialBatch);
            materialConsumptionRepository.save(consumptionRecord);
        }
        // 更新生产批次的原材料成本
        BigDecimal totalMaterialCost = BigDecimal.ZERO;
        for (Map<String, Object> consumption : consumptions) {
            String materialBatchId = (String) consumption.get("materialBatchId");
            BigDecimal quantity = new BigDecimal(consumption.get("quantity").toString());
            MaterialBatch materialBatch = materialBatchRepository.findById(materialBatchId).get();
            BigDecimal cost = quantity.multiply(materialBatch.getUnitPrice());
            totalMaterialCost = totalMaterialCost.add(cost);
        }
        productionBatch.setMaterialCost(totalMaterialCost);
        productionBatchRepository.save(productionBatch);
    }
    // ========== 质量检验 ==========
    public Map<String, Object> submitInspection(String factoryId, String batchId, Map<String, Object> inspection) {
        log.info("提交质检记录: factoryId={}, batchId={}", factoryId, batchId);
        QualityInspection qualityInspection = new QualityInspection();
        qualityInspection.setFactoryId(factoryId);
        qualityInspection.setProductionBatchId(Long.parseLong(batchId));
        qualityInspection.setInspectorId(inspection.get("inspectorId") != null ?
                Long.valueOf(inspection.get("inspectorId").toString()) : null);
        qualityInspection.setInspectionDate(LocalDate.now());
        qualityInspection.setSampleSize(new BigDecimal(inspection.get("sampleSize").toString()));
        qualityInspection.setPassCount(new BigDecimal(inspection.get("passCount").toString()));
        qualityInspection.setFailCount(new BigDecimal(inspection.get("failCount").toString()));
        BigDecimal passRate = qualityInspection.getPassCount()
                .divide(qualityInspection.getSampleSize(), 2, RoundingMode.HALF_UP)
                .multiply(new BigDecimal(100));
        qualityInspection.setPassRate(passRate);
        qualityInspection.setResult((String) inspection.get("result"));
        qualityInspection.setNotes((String) inspection.get("notes"));
        QualityInspection saved = qualityInspectionRepository.save(qualityInspection);
        Map<String, Object> result = new HashMap<>();
        result.put("inspection", saved);
        result.put("passRate", passRate);
        return result;
    }
    public PageResponse<Map<String, Object>> getInspections(String factoryId, String batchId, PageRequest pageRequest) {
        org.springframework.data.domain.PageRequest pageable = org.springframework.data.domain.PageRequest.of(
                pageRequest.getPage() - 1,
                pageRequest.getSize(),
                Sort.by(Sort.Direction.DESC, "inspectionDate")
        );
        Page<QualityInspection> page;
        if (batchId != null) {
            page = qualityInspectionRepository.findByFactoryIdAndProductionBatchId(factoryId, Long.parseLong(batchId), pageable);
        } else {
            page = qualityInspectionRepository.findByFactoryId(factoryId, pageable);
        }
        List<Map<String, Object>> inspectionMaps = page.getContent().stream()
                .map(this::convertInspectionToMap)
                .collect(Collectors.toList());
        return PageResponse.of(
                inspectionMaps,
                pageRequest.getPage(),
                pageRequest.getSize(),
                page.getTotalElements()
        );
    }

    /**
     * 获取质检详情
     */
    public Map<String, Object> getInspectionById(String factoryId, String inspectionId) {
        QualityInspection inspection = qualityInspectionRepository.findById(inspectionId)
                .filter(i -> factoryId.equals(i.getFactoryId()))
                .orElseThrow(() -> new RuntimeException("质检记录不存在: " + inspectionId));
        return convertInspectionToMap(inspection);
    }

    public Map<String, Object> getQualityStatistics(String factoryId, LocalDate startDate, LocalDate endDate) {
        List<QualityInspection> inspections = qualityInspectionRepository.findByFactoryIdAndDateRange(
                factoryId, startDate, endDate);
        Map<String, Object> statistics = new HashMap<>();
        statistics.put("totalInspections", inspections.size());
        if (!inspections.isEmpty()) {
            // 过滤掉 passRate 为 null 的记录（如 pending 状态）
            List<BigDecimal> validPassRates = inspections.stream()
                    .map(QualityInspection::getPassRate)
                    .filter(rate -> rate != null)
                    .collect(Collectors.toList());

            BigDecimal averagePassRate = BigDecimal.ZERO;
            if (!validPassRates.isEmpty()) {
                averagePassRate = validPassRates.stream()
                        .reduce(BigDecimal.ZERO, BigDecimal::add)
                        .divide(new BigDecimal(validPassRates.size()), 2, RoundingMode.HALF_UP);
            }
            statistics.put("averagePassRate", averagePassRate);
            long passedCount = inspections.stream()
                    .filter(i -> "PASS".equalsIgnoreCase(i.getResult()))
                    .count();
            statistics.put("passedBatches", passedCount);
            statistics.put("failedBatches", inspections.size() - passedCount);
        }
        return statistics;
    }
    public List<Map<String, Object>> getQualityTrends(String factoryId, Integer days) {
        LocalDate endDate = LocalDate.now();
        LocalDate startDate = endDate.minusDays(days);
        List<QualityInspection> inspections = qualityInspectionRepository.findByFactoryIdAndDateRange(
                factoryId, startDate, endDate);
        Map<LocalDate, List<QualityInspection>> groupedByDate = inspections.stream()
                .collect(Collectors.groupingBy(QualityInspection::getInspectionDate));
        List<Map<String, Object>> trends = new ArrayList<>();
        for (LocalDate date = startDate; !date.isAfter(endDate); date = date.plusDays(1)) {
            Map<String, Object> dayTrend = new HashMap<>();
            dayTrend.put("date", date);
            List<QualityInspection> dayInspections = groupedByDate.getOrDefault(date, new ArrayList<>());
            if (!dayInspections.isEmpty()) {
                // 过滤掉 passRate 为 null 的记录
                List<BigDecimal> validRates = dayInspections.stream()
                        .map(QualityInspection::getPassRate)
                        .filter(rate -> rate != null)
                        .collect(Collectors.toList());

                BigDecimal avgPassRate = BigDecimal.ZERO;
                if (!validRates.isEmpty()) {
                    avgPassRate = validRates.stream()
                            .reduce(BigDecimal.ZERO, BigDecimal::add)
                            .divide(new BigDecimal(validRates.size()), 2, RoundingMode.HALF_UP);
                }
                dayTrend.put("passRate", avgPassRate);
                dayTrend.put("inspectionCount", dayInspections.size());
            } else {
                dayTrend.put("passRate", BigDecimal.ZERO);
                dayTrend.put("inspectionCount", 0);
            }
            trends.add(dayTrend);
        }
        return trends;
    }
    // ========== 设备监控 ==========
    public void recordEquipmentUsage(String factoryId, String batchId, Long equipmentId,
                                    LocalDate startTime, LocalDate endTime) {
        // equipmentId 现在是 Long 类型，与 FactoryEquipment.id 一致
        FactoryEquipment equipment = equipmentRepository.findById(equipmentId)
                .orElseThrow(() -> new ResourceNotFoundException("设备不存在"));
        // 使用 BatchEquipmentUsage 替代 EquipmentUsage
        BatchEquipmentUsage usage = new BatchEquipmentUsage();
        usage.setEquipmentId(equipmentId);
        usage.setBatchId(Long.parseLong(batchId));  // 转换为Long类型
        usage.setStartTime(startTime.atStartOfDay());
        usage.setEndTime(endTime.atTime(23, 59, 59));
        long hours = ChronoUnit.HOURS.between(usage.getStartTime(), usage.getEndTime());
        usage.setUsageHours(new BigDecimal(hours));
        // 使用设备的实际小时成本，如果没有则使用默认值50元/小时
        BigDecimal hourlyCost = equipment.getHourlyCost() != null ? equipment.getHourlyCost() : new BigDecimal("50");
        usage.setEquipmentCost(new BigDecimal(hours).multiply(hourlyCost));
        batchEquipmentUsageRepository.save(usage);
        // 更新设备使用时长
        equipment.setTotalRunningHours(
                (equipment.getTotalRunningHours() != null ? equipment.getTotalRunningHours() : 0) + (int) hours
        );
        equipment.setLastMaintenanceDate(LocalDate.now());
        equipmentRepository.save(equipment);
    }
    public List<Map<String, Object>> getEquipmentMonitoring(String factoryId) {
        List<FactoryEquipment> equipments = equipmentRepository.findByFactoryId(factoryId,
                org.springframework.data.domain.PageRequest.of(0, 1000)).getContent();
        return equipments.stream().map(equipment -> {
            Map<String, Object> monitoring = new HashMap<>();
            monitoring.put("equipmentId", equipment.getId());
            monitoring.put("name", equipment.getEquipmentName());
            monitoring.put("status", equipment.getStatus());
            monitoring.put("totalOperatingHours", equipment.getTotalRunningHours());
            monitoring.put("lastMaintenanceDate", equipment.getLastMaintenanceDate());
            // 计算利用率 - 使用 BatchEquipmentUsage
            LocalDateTime weekAgo = LocalDateTime.now().minusDays(7);
            List<BatchEquipmentUsage> recentUsages = batchEquipmentUsageRepository.findByEquipmentIdAndStartTimeAfter(
                    equipment.getId(), weekAgo);
            BigDecimal totalUsageHours = recentUsages.stream()
                    .map(BatchEquipmentUsage::getUsageHours)
                    .filter(h -> h != null)
                    .reduce(BigDecimal.ZERO, BigDecimal::add);
            double utilizationRate = (totalUsageHours.doubleValue() / 168.0) * 100; // 168 = 7天 * 24小时
            monitoring.put("weeklyUtilizationRate", utilizationRate);
            return monitoring;
        }).collect(Collectors.toList());
    }
    public Map<String, Object> getEquipmentMetrics(String factoryId, Long equipmentId, Integer days) {
        // equipmentId 现在是 Long 类型，与 FactoryEquipment.id 一致
        FactoryEquipment equipment = equipmentRepository.findById(equipmentId)
                .orElseThrow(() -> new ResourceNotFoundException("设备不存在"));
        LocalDateTime startDate = LocalDateTime.now().minusDays(days);
        // 使用 BatchEquipmentUsage 替代 EquipmentUsage
        List<BatchEquipmentUsage> usages = batchEquipmentUsageRepository.findByEquipmentIdAndStartTimeAfter(
                equipmentId, startDate);
        Map<String, Object> metrics = new HashMap<>();
        metrics.put("equipment", equipment);
        BigDecimal totalUsageHours = usages.stream()
                .map(BatchEquipmentUsage::getUsageHours)
                .filter(h -> h != null)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        metrics.put("totalUsageHours", totalUsageHours);
        metrics.put("usageCount", usages.size());
        BigDecimal avgUsageHours = usages.isEmpty() ? BigDecimal.ZERO :
                totalUsageHours.divide(new BigDecimal(usages.size()), 2, RoundingMode.HALF_UP);
        metrics.put("averageUsageHours", avgUsageHours);
        return metrics;
    }
    public void recordEquipmentMaintenance(String factoryId, Long equipmentId, Map<String, Object> maintenance) {
        // equipmentId 现在是 Long 类型，与 FactoryEquipment.id 一致
        FactoryEquipment equipment = equipmentRepository.findById(equipmentId)
                .orElseThrow(() -> new ResourceNotFoundException("设备不存在"));
        equipment.setLastMaintenanceDate(LocalDate.now());
        equipment.setStatus("running");
        equipment.setNotes((String) maintenance.get("notes"));
        equipmentRepository.save(equipment);
    }
    // ========== 成本分析 ==========
    public Map<String, Object> getBatchCostAnalysis(String factoryId, String batchId) {
        ProductionBatch batch = getBatchById(factoryId, batchId);
        Map<String, Object> analysis = new HashMap<>();

        // 添加batch基本信息（作为Map而不是对象）
        Map<String, Object> batchInfo = new HashMap<>();
        batchInfo.put("batchNumber", batch.getBatchNumber());
        batchInfo.put("productName", batch.getProductName());
        batchInfo.put("actualQuantity", batch.getActualQuantity());
        batchInfo.put("goodQuantity", batch.getGoodQuantity());
        batchInfo.put("defectQuantity", batch.getDefectQuantity());
        batchInfo.put("yieldRate", batch.getYieldRate());
        batchInfo.put("startTime", batch.getStartTime());
        batchInfo.put("endTime", batch.getEndTime());
        analysis.put("batch", batchInfo);

        analysis.put("materialCost", batch.getMaterialCost());
        analysis.put("laborCost", batch.getLaborCost());
        analysis.put("equipmentCost", batch.getEquipmentCost());
        analysis.put("otherCost", batch.getOtherCost());
        analysis.put("totalCost", batch.getTotalCost());
        analysis.put("unitCost", batch.getUnitCost());
        // 成本构成比例
        if (batch.getTotalCost() != null && batch.getTotalCost().compareTo(BigDecimal.ZERO) > 0) {
            analysis.put("materialCostRatio",
                    batch.getMaterialCost().divide(batch.getTotalCost(), 2, RoundingMode.HALF_UP).multiply(new BigDecimal(100)));
            analysis.put("laborCostRatio",
                    batch.getLaborCost().divide(batch.getTotalCost(), 2, RoundingMode.HALF_UP).multiply(new BigDecimal(100)));
            analysis.put("equipmentCostRatio",
                    batch.getEquipmentCost().divide(batch.getTotalCost(), 2, RoundingMode.HALF_UP).multiply(new BigDecimal(100)));
            analysis.put("otherCostRatio",
                    batch.getOtherCost().divide(batch.getTotalCost(), 2, RoundingMode.HALF_UP).multiply(new BigDecimal(100)));
        }
        return analysis;
    }

    /**
     * 获取增强的批次成本分析（包含完整业务链数据）
     * 整合原材料、设备、人工、质检等全维度信息
     */
    public Map<String, Object> getEnhancedBatchCostAnalysis(String factoryId, String batchId) {
        log.info("获取增强的批次成本分析: factoryId={}, batchId={}", factoryId, batchId);

        ProductionBatch batch = getBatchById(factoryId, batchId);
        Map<String, Object> analysis = new HashMap<>();

        // ========== 1. 基本信息 ==========
        Map<String, Object> batchInfo = new HashMap<>();
        batchInfo.put("batchNumber", batch.getBatchNumber());
        batchInfo.put("productName", batch.getProductName());
        batchInfo.put("plannedQuantity", batch.getPlannedQuantity());
        batchInfo.put("actualQuantity", batch.getActualQuantity());
        batchInfo.put("goodQuantity", batch.getGoodQuantity());
        batchInfo.put("defectQuantity", batch.getDefectQuantity());
        batchInfo.put("yieldRate", batch.getYieldRate());
        batchInfo.put("efficiency", batch.getEfficiency());
        batchInfo.put("status", batch.getStatus());
        batchInfo.put("startTime", batch.getStartTime());
        batchInfo.put("endTime", batch.getEndTime());

        // 计算生产时长
        if (batch.getStartTime() != null && batch.getEndTime() != null) {
            long hours = ChronoUnit.HOURS.between(batch.getStartTime(), batch.getEndTime());
            batchInfo.put("productionHours", hours);
        }
        analysis.put("batchInfo", batchInfo);

        // ========== 2. 生产计划对比 ==========
        if (batch.getProductionPlanId() != null) {
            productionPlanRepository.findById(batch.getProductionPlanId().toString()).ifPresent(plan -> {
                Map<String, Object> planComparison = new HashMap<>();
                planComparison.put("planId", plan.getId());
                planComparison.put("planNumber", plan.getPlanNumber());
                // planComparison.put("plannedDate", plan.getPlannedDate());  // 暂时注释 - 数据库表中没有此字段
                planComparison.put("plannedQuantity", plan.getPlannedQuantity());
                planComparison.put("actualQuantity", batch.getActualQuantity());

                if (plan.getPlannedQuantity() != null && batch.getActualQuantity() != null) {
                    BigDecimal completionRate = batch.getActualQuantity()
                        .divide(plan.getPlannedQuantity(), 4, RoundingMode.HALF_UP)
                        .multiply(new BigDecimal(100));
                    planComparison.put("completionRate", completionRate);
                }

                planComparison.put("planStartTime", plan.getStartTime());
                planComparison.put("planEndTime", plan.getEndTime());
                planComparison.put("actualStartTime", batch.getStartTime());
                planComparison.put("actualEndTime", batch.getEndTime());
                planComparison.put("status", plan.getStatus());

                analysis.put("productionPlanComparison", planComparison);
            });
        }

        // ========== 3. 原材料消耗详情 ==========
        Long batchIdLong = Long.parseLong(batchId);
        List<MaterialConsumption> consumptions = materialConsumptionRepository.findByProductionBatchId(batchIdLong);
        List<Map<String, Object>> materialDetails = new ArrayList<>();
        BigDecimal totalMaterialCost = BigDecimal.ZERO;

        for (MaterialConsumption consumption : consumptions) {
            Map<String, Object> materialDetail = new HashMap<>();
            MaterialBatch materialBatch = consumption.getBatch();

            materialDetail.put("consumptionId", consumption.getId());
            materialDetail.put("batchNumber", materialBatch.getBatchNumber());

            // 获取原材料名称（通过materialType关联）
            String materialName = materialBatch.getMaterialType() != null ?
                materialBatch.getMaterialType().getName() : "未知原材料";
            materialDetail.put("materialName", materialName);

            materialDetail.put("quantity", consumption.getQuantity());
            materialDetail.put("unit", materialBatch.getQuantityUnit());
            materialDetail.put("unitPrice", materialBatch.getUnitPrice());

            // 计算此次消耗成本
            BigDecimal cost = consumption.getQuantity().multiply(materialBatch.getUnitPrice());
            materialDetail.put("cost", cost);
            totalMaterialCost = totalMaterialCost.add(cost);

            // 供应商信息
            if (materialBatch.getSupplier() != null) {
                Map<String, Object> supplierInfo = new HashMap<>();
                supplierInfo.put("id", materialBatch.getSupplier().getId());
                supplierInfo.put("name", materialBatch.getSupplier().getName());
                supplierInfo.put("contactPerson", materialBatch.getSupplier().getContactPerson());
                materialDetail.put("supplier", supplierInfo);
            }

            // FIFO信息
            materialDetail.put("receiptDate", materialBatch.getReceiptDate());
            materialDetail.put("expireDate", materialBatch.getExpireDate());

            // 库存状态
            materialDetail.put("initialQuantity", materialBatch.getInitialQuantity());
            materialDetail.put("remainingQuantity", materialBatch.getRemainingQuantity());

            materialDetail.put("consumedAt", consumption.getConsumedAt());

            materialDetails.add(materialDetail);
        }

        analysis.put("materialConsumptions", materialDetails);
        analysis.put("materialConsumptionCount", materialDetails.size());
        analysis.put("totalMaterialCost", totalMaterialCost);

        // ========== 4. 设备使用详情 ==========
        // 使用 BatchEquipmentUsage 替代 EquipmentUsage (batchId 是 Long 类型)
        // 注: batchIdLong 已在上面定义
        List<BatchEquipmentUsage> usages = batchEquipmentUsageRepository.findByBatchId(batchIdLong);
        List<Map<String, Object>> equipmentDetails = new ArrayList<>();
        BigDecimal totalEquipmentCost = BigDecimal.ZERO;
        BigDecimal totalEquipmentHours = BigDecimal.ZERO;

        for (BatchEquipmentUsage usage : usages) {
            Map<String, Object> equipmentDetail = new HashMap<>();

            // equipmentId 是 Long 类型
            Long equipmentIdLong = usage.getEquipmentId();
            final BigDecimal[] hourlyCostHolder = {new BigDecimal("50")}; // 默认值
            equipmentRepository.findById(equipmentIdLong).ifPresent(equipment -> {
                equipmentDetail.put("equipmentId", equipment.getId());
                equipmentDetail.put("equipmentName", equipment.getEquipmentName());
                equipmentDetail.put("equipmentCode", equipment.getEquipmentCode());
                equipmentDetail.put("model", equipment.getModel());
                equipmentDetail.put("status", equipment.getStatus());
                equipmentDetail.put("hourlyCost", equipment.getHourlyCost());
                // 获取设备的实际小时成本
                if (equipment.getHourlyCost() != null) {
                    hourlyCostHolder[0] = equipment.getHourlyCost();
                }
            });

            equipmentDetail.put("usageId", usage.getId());
            equipmentDetail.put("startTime", usage.getStartTime());
            equipmentDetail.put("endTime", usage.getEndTime());
            equipmentDetail.put("usageHours", usage.getUsageHours());

            // 使用记录中已存储的设备成本，如果没有则按设备实际小时成本计算
            BigDecimal equipmentCost = usage.getEquipmentCost() != null ? usage.getEquipmentCost() :
                    (usage.getUsageHours() != null ? usage.getUsageHours().multiply(hourlyCostHolder[0]) : BigDecimal.ZERO);
            equipmentDetail.put("cost", equipmentCost);

            totalEquipmentCost = totalEquipmentCost.add(equipmentCost);
            if (usage.getUsageHours() != null) {
                totalEquipmentHours = totalEquipmentHours.add(usage.getUsageHours());
            }

            equipmentDetails.add(equipmentDetail);
        }

        analysis.put("equipmentUsages", equipmentDetails);
        analysis.put("equipmentUsageCount", equipmentDetails.size());
        analysis.put("totalEquipmentHours", totalEquipmentHours);
        analysis.put("totalEquipmentCost", totalEquipmentCost);

        // ========== 5. 人工工时详情 ==========
        // 查询 BatchWorkSession 获取详细的工时数据
        List<BatchWorkSession> workSessions = batchWorkSessionRepository.findByBatchId(batchIdLong);
        List<Map<String, Object>> laborDetails = new ArrayList<>();
        BigDecimal totalLaborCost = BigDecimal.ZERO;
        int totalWorkMinutes = 0;
        Set<Long> uniqueEmployeeIds = new HashSet<>();

        for (BatchWorkSession session : workSessions) {
            Map<String, Object> laborDetail = new HashMap<>();
            laborDetail.put("sessionId", session.getId());
            laborDetail.put("workMinutes", session.getWorkMinutes());
            laborDetail.put("laborCost", session.getLaborCost());
            laborDetail.put("employeeId", session.getEmployeeId());

            // 获取员工信息
            if (session.getEmployeeId() != null) {
                userRepository.findById(session.getEmployeeId()).ifPresent(employee -> {
                    laborDetail.put("employeeName", employee.getFullName());
                    laborDetail.put("employeeRole", employee.getRole());
                });
                uniqueEmployeeIds.add(session.getEmployeeId());
            }

            // 获取工作会话详情
            if (session.getWorkSession() != null) {
                EmployeeWorkSession ws = session.getWorkSession();
                // 从startTime提取日期
                laborDetail.put("workDate", ws.getStartTime() != null ? ws.getStartTime().toLocalDate() : null);
                laborDetail.put("startTime", ws.getStartTime());
                laborDetail.put("endTime", ws.getEndTime());
            }

            laborDetails.add(laborDetail);

            // 累加总计
            if (session.getLaborCost() != null) {
                totalLaborCost = totalLaborCost.add(session.getLaborCost());
            }
            if (session.getWorkMinutes() != null) {
                totalWorkMinutes += session.getWorkMinutes();
            }
        }

        // 如果没有 BatchWorkSession 数据，使用 ProductionBatch 中的汇总数据作为兜底
        if (workSessions.isEmpty()) {
            totalLaborCost = batch.getLaborCost() != null ? batch.getLaborCost() : BigDecimal.ZERO;
            totalWorkMinutes = batch.getWorkDurationMinutes() != null ? batch.getWorkDurationMinutes() : 0;

            if (totalLaborCost.compareTo(BigDecimal.ZERO) > 0 || totalWorkMinutes > 0) {
                Map<String, Object> laborSummary = new HashMap<>();
                laborSummary.put("workMinutes", totalWorkMinutes);
                laborSummary.put("laborCost", totalLaborCost);
                laborSummary.put("workerCount", batch.getWorkerCount());
                laborSummary.put("note", "来自批次汇总数据");
                laborDetails.add(laborSummary);
            }
        }

        analysis.put("laborSessions", laborDetails);
        analysis.put("laborSessionCount", laborDetails.size());
        analysis.put("totalWorkMinutes", totalWorkMinutes);
        analysis.put("totalWorkHours", totalWorkMinutes / 60.0);
        analysis.put("totalLaborCost", totalLaborCost);
        analysis.put("uniqueWorkerCount", workSessions.isEmpty() ?
            (batch.getWorkerCount() != null ? batch.getWorkerCount() : 0) : uniqueEmployeeIds.size());

        // ========== 6. 质量检验详情 ==========
        List<QualityInspection> inspections = qualityInspectionRepository.findByFactoryIdAndProductionBatchId(
            factoryId, batchIdLong, org.springframework.data.domain.PageRequest.of(0, 100)).getContent();

        List<Map<String, Object>> qualityDetails = new ArrayList<>();

        for (QualityInspection inspection : inspections) {
            Map<String, Object> qualityDetail = new HashMap<>();

            qualityDetail.put("inspectionId", inspection.getId());
            qualityDetail.put("inspectionDate", inspection.getInspectionDate());
            qualityDetail.put("sampleSize", inspection.getSampleSize());
            qualityDetail.put("passCount", inspection.getPassCount());
            qualityDetail.put("failCount", inspection.getFailCount());
            qualityDetail.put("passRate", inspection.getPassRate());
            qualityDetail.put("result", inspection.getResult());
            qualityDetail.put("notes", inspection.getNotes());

            // 检验员信息
            if (inspection.getInspectorId() != null) {
                userRepository.findById(inspection.getInspectorId()).ifPresent(inspector -> {
                    Map<String, Object> inspectorInfo = new HashMap<>();
                    inspectorInfo.put("id", inspector.getId());
                    inspectorInfo.put("fullName", inspector.getFullName());
                    qualityDetail.put("inspector", inspectorInfo);
                });
            }

            qualityDetails.add(qualityDetail);
        }

        analysis.put("qualityInspections", qualityDetails);
        analysis.put("qualityInspectionCount", qualityDetails.size());

        // 计算平均合格率
        if (!inspections.isEmpty()) {
            BigDecimal avgPassRate = inspections.stream()
                .map(QualityInspection::getPassRate)
                .reduce(BigDecimal.ZERO, BigDecimal::add)
                .divide(new BigDecimal(inspections.size()), 2, RoundingMode.HALF_UP);
            analysis.put("averagePassRate", avgPassRate);
        }

        // ========== 7. 加工环节详情 ==========
        try {
            List<ProcessingStageRecordDTO> stageRecords = processingStageRecordService
                .getByBatchIdWithComparison(factoryId, batchIdLong);

            List<Map<String, Object>> stageDetails = new ArrayList<>();

            for (ProcessingStageRecordDTO stage : stageRecords) {
                Map<String, Object> stageDetail = new HashMap<>();

                // 基本信息
                stageDetail.put("id", stage.getId());
                stageDetail.put("stageType", stage.getStageType());
                stageDetail.put("stageName", stage.getStageName());
                stageDetail.put("stageOrder", stage.getStageOrder());

                // 时间数据
                stageDetail.put("startTime", stage.getStartTime());
                stageDetail.put("endTime", stage.getEndTime());
                stageDetail.put("durationMinutes", stage.getDurationMinutes());
                stageDetail.put("avgDuration", stage.getAvgDuration());

                // 重量/数量数据
                stageDetail.put("inputWeight", stage.getInputWeight());
                stageDetail.put("outputWeight", stage.getOutputWeight());
                stageDetail.put("lossWeight", stage.getLossWeight());
                stageDetail.put("lossRate", stage.getLossRate());
                stageDetail.put("avgLossRate", stage.getAvgLossRate());

                // 温度数据
                stageDetail.put("ambientTemperature", stage.getAmbientTemperature());
                stageDetail.put("productTemperature", stage.getProductTemperature());
                stageDetail.put("targetTemperature", stage.getTargetTemperature());

                // 质量数据
                stageDetail.put("passCount", stage.getPassCount());
                stageDetail.put("failCount", stage.getFailCount());
                stageDetail.put("passRate", stage.getPassRate());
                stageDetail.put("avgPassRate", stage.getAvgPassRate());
                stageDetail.put("reworkCount", stage.getReworkCount());

                // 设备数据
                stageDetail.put("equipmentId", stage.getEquipmentId());
                stageDetail.put("equipmentName", stage.getEquipmentName());
                stageDetail.put("equipmentRunTime", stage.getEquipmentRunTime());
                stageDetail.put("equipmentDowntime", stage.getEquipmentDowntime());
                stageDetail.put("equipmentOee", stage.getEquipmentOee());

                // 资源消耗数据
                stageDetail.put("waterUsage", stage.getWaterUsage());
                stageDetail.put("powerUsage", stage.getPowerUsage());
                stageDetail.put("auxiliaryUsage", stage.getAuxiliaryUsage());
                stageDetail.put("auxiliaryName", stage.getAuxiliaryName());

                // 特殊环节数据
                stageDetail.put("dripLoss", stage.getDripLoss());
                stageDetail.put("thicknessSd", stage.getThicknessSd());
                stageDetail.put("marinadeAbsorption", stage.getMarinadeAbsorption());
                stageDetail.put("phValue", stage.getPhValue());
                stageDetail.put("salinity", stage.getSalinity());
                stageDetail.put("atpResult", stage.getAtpResult());
                stageDetail.put("microPassRate", stage.getMicroPassRate());
                stageDetail.put("ccpPassRate", stage.getCcpPassRate());

                // 操作员信息
                stageDetail.put("operatorId", stage.getOperatorId());
                stageDetail.put("operatorName", stage.getOperatorName());
                stageDetail.put("workerCount", stage.getWorkerCount());

                // 其他
                stageDetail.put("notes", stage.getNotes());

                stageDetails.add(stageDetail);
            }

            analysis.put("processingStages", stageDetails);
            analysis.put("processingStageCount", stageDetails.size());

            // 添加AI分析格式化的环节数据
            if (!stageRecords.isEmpty()) {
                Map<String, String> aiFormatData = processingStageRecordService
                    .formatForAIAnalysis(factoryId, batchIdLong);
                analysis.put("processingStageAIFormat", aiFormatData);
            }
        } catch (Exception e) {
            log.warn("获取加工环节数据失败: {}", e.getMessage());
            analysis.put("processingStages", new ArrayList<>());
            analysis.put("processingStageCount", 0);
        }

        // ========== 8. 成本汇总 ==========
        Map<String, Object> costSummary = new HashMap<>();
        costSummary.put("materialCost", totalMaterialCost);
        costSummary.put("laborCost", totalLaborCost);
        costSummary.put("equipmentCost", totalEquipmentCost);
        costSummary.put("otherCost", batch.getOtherCost() != null ? batch.getOtherCost() : BigDecimal.ZERO);

        BigDecimal totalCost = totalMaterialCost.add(totalLaborCost).add(totalEquipmentCost)
            .add(batch.getOtherCost() != null ? batch.getOtherCost() : BigDecimal.ZERO);
        costSummary.put("totalCost", totalCost);

        // 单位成本 - 优先使用良品数量
        BigDecimal quantityForUnitCost = batch.getGoodQuantity() != null && batch.getGoodQuantity().compareTo(BigDecimal.ZERO) > 0
                ? batch.getGoodQuantity() : batch.getActualQuantity();
        if (quantityForUnitCost != null && quantityForUnitCost.compareTo(BigDecimal.ZERO) > 0) {
            BigDecimal unitCost = totalCost.divide(quantityForUnitCost, 4, RoundingMode.HALF_UP);
            costSummary.put("unitCost", unitCost);
            costSummary.put("unitCostBasis", batch.getGoodQuantity() != null && batch.getGoodQuantity().compareTo(BigDecimal.ZERO) > 0
                    ? "goodQuantity" : "actualQuantity");
        }

        // 成本占比
        if (totalCost.compareTo(BigDecimal.ZERO) > 0) {
            costSummary.put("materialCostRatio",
                totalMaterialCost.divide(totalCost, 4, RoundingMode.HALF_UP).multiply(new BigDecimal(100)));
            costSummary.put("laborCostRatio",
                totalLaborCost.divide(totalCost, 4, RoundingMode.HALF_UP).multiply(new BigDecimal(100)));
            costSummary.put("equipmentCostRatio",
                totalEquipmentCost.divide(totalCost, 4, RoundingMode.HALF_UP).multiply(new BigDecimal(100)));
        }

        analysis.put("costSummary", costSummary);

        // ========== 8.1 前端兼容的costBreakdown结构（CostAnalysisDashboard使用） ==========
        Map<String, Object> costBreakdown = new HashMap<>();
        costBreakdown.put("rawMaterialCost", totalMaterialCost);
        costBreakdown.put("laborCost", totalLaborCost);
        costBreakdown.put("equipmentCost", totalEquipmentCost);
        costBreakdown.put("totalCost", totalCost);

        // 百分比计算
        if (totalCost.compareTo(BigDecimal.ZERO) > 0) {
            BigDecimal rawMaterialPct = totalMaterialCost.divide(totalCost, 4, RoundingMode.HALF_UP).multiply(new BigDecimal(100));
            BigDecimal laborPct = totalLaborCost.divide(totalCost, 4, RoundingMode.HALF_UP).multiply(new BigDecimal(100));
            BigDecimal equipmentPct = totalEquipmentCost.divide(totalCost, 4, RoundingMode.HALF_UP).multiply(new BigDecimal(100));
            costBreakdown.put("rawMaterialPercentage", rawMaterialPct.setScale(1, RoundingMode.HALF_UP));
            costBreakdown.put("laborPercentage", laborPct.setScale(1, RoundingMode.HALF_UP));
            costBreakdown.put("equipmentPercentage", equipmentPct.setScale(1, RoundingMode.HALF_UP));
        } else {
            costBreakdown.put("rawMaterialPercentage", 0);
            costBreakdown.put("laborPercentage", 0);
            costBreakdown.put("equipmentPercentage", 0);
        }
        analysis.put("costBreakdown", costBreakdown);

        // ========== 9. 风险预警 ==========
        List<String> risks = new ArrayList<>();

        // 原材料过期风险
        for (MaterialConsumption consumption : consumptions) {
            MaterialBatch mb = consumption.getBatch();
            if (mb.getExpireDate() != null && mb.getExpireDate().isBefore(LocalDate.now().plusDays(7))) {
                String matName = mb.getMaterialType() != null ?
                    mb.getMaterialType().getName() : "未知原材料";
                risks.add("原材料 " + matName + " 批次 " + mb.getBatchNumber() + " 即将过期");
            }
        }

        // 良品率风险
        if (batch.getYieldRate() != null && batch.getYieldRate().compareTo(new BigDecimal("90")) < 0) {
            risks.add("良品率偏低（" + batch.getYieldRate() + "%），建议加强质量控制");
        }

        // 成本占比风险
        if (totalCost.compareTo(BigDecimal.ZERO) > 0) {
            BigDecimal materialRatio = totalMaterialCost.divide(totalCost, 4, RoundingMode.HALF_UP);
            if (materialRatio.compareTo(new BigDecimal("0.65")) > 0) {
                risks.add("原材料成本占比过高（" + materialRatio.multiply(new BigDecimal(100)) + "%），建议优化采购");
            }
        }

        analysis.put("risks", risks);
        analysis.put("riskCount", risks.size());

        log.info("增强的批次成本分析完成: batchId={}, 原材料{}种, 设备{}台, 人工{}人次, 质检{}次, 加工环节{}个",
                 batchId, materialDetails.size(), equipmentDetails.size(), laborDetails.size(), qualityDetails.size(),
                 analysis.get("processingStageCount"));

        return analysis;
    }
    public ProductionBatch recalculateBatchCost(String factoryId, String batchId) {
        ProductionBatch batch = getBatchById(factoryId, batchId);
        Long batchIdLong = Long.parseLong(batchId);

        // 重新计算原材料成本
        List<MaterialConsumption> consumptions = materialConsumptionRepository.findByProductionBatchId(batchIdLong);
        BigDecimal materialCost = consumptions.stream()
                .map(c -> c.getQuantity().multiply(c.getBatch().getUnitPrice()))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        batch.setMaterialCost(materialCost);

        // 重新计算设备成本 - 使用 BatchEquipmentUsage
        List<BatchEquipmentUsage> usages = batchEquipmentUsageRepository.findByBatchId(batchIdLong);
        // 优先使用记录中已存储的成本，如果没有则按设备实际小时成本计算
        BigDecimal equipmentCost = BigDecimal.ZERO;
        for (BatchEquipmentUsage usage : usages) {
            if (usage.getEquipmentCost() != null) {
                equipmentCost = equipmentCost.add(usage.getEquipmentCost());
            } else if (usage.getUsageHours() != null) {
                // 获取设备的实际小时成本
                BigDecimal hourlyCost = new BigDecimal("50"); // 默认值
                Long equipmentId = usage.getEquipmentId();
                if (equipmentId != null) {
                    FactoryEquipment equipment = equipmentRepository.findById(equipmentId).orElse(null);
                    if (equipment != null && equipment.getHourlyCost() != null) {
                        hourlyCost = equipment.getHourlyCost();
                    }
                }
                equipmentCost = equipmentCost.add(usage.getUsageHours().multiply(hourlyCost));
            }
        }
        batch.setEquipmentCost(equipmentCost);

        // 重新计算人工成本 - 使用 BatchWorkSession
        List<BatchWorkSession> workSessions = batchWorkSessionRepository.findByBatchId(batchIdLong);
        BigDecimal laborCost = workSessions.stream()
                .map(s -> s.getLaborCost() != null ? s.getLaborCost() : BigDecimal.ZERO)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        if (laborCost.compareTo(BigDecimal.ZERO) > 0) {
            batch.setLaborCost(laborCost);
        }

        // 重新计算总成本
        batch.calculateMetrics();
        return productionBatchRepository.save(batch);
    }
    public Map<String, Object> getAICostAnalysis(String factoryId, String batchId) {
        ProductionBatch batch = getBatchById(factoryId, batchId);
        Map<String, Object> aiAnalysis = new HashMap<>();
        aiAnalysis.put("batch", batch);
        List<String> suggestions = new ArrayList<>();
        // 基于成本分析提供建议
        if (batch.getMaterialCost() != null && batch.getTotalCost() != null) {
            BigDecimal materialRatio = batch.getMaterialCost().divide(batch.getTotalCost(), 2, RoundingMode.HALF_UP);
            if (materialRatio.compareTo(new BigDecimal("0.6")) > 0) {
                suggestions.add("原材料成本占比过高（" + materialRatio.multiply(new BigDecimal(100)) + "%），建议优化采购策略或寻找替代供应商");
            }
        }
        if (batch.getYieldRate() != null && batch.getYieldRate().compareTo(new BigDecimal("90")) < 0) {
            suggestions.add("良品率偏低（" + batch.getYieldRate() + "%），建议加强质量控制和工艺优化");
        }
        if (batch.getEfficiency() != null && batch.getEfficiency().compareTo(new BigDecimal("80")) < 0) {
            suggestions.add("生产效率偏低（" + batch.getEfficiency() + "%），建议优化生产流程和人员配置");
        }
        aiAnalysis.put("suggestions", suggestions);
        aiAnalysis.put("potentialSavings", calculatePotentialSavings(batch));
        return aiAnalysis;
    }
    // ========== 仪表盘 ==========
    public Map<String, Object> getDashboardOverview(String factoryId) {
        Map<String, Object> overview = new HashMap<>();
        LocalDateTime todayStart = LocalDate.now().atStartOfDay();
        LocalDateTime monthStart = LocalDate.now().withDayOfMonth(1).atStartOfDay();

        // ===== summary (概览) =====
        Map<String, Object> summary = new HashMap<>();
        // 今日批次总数
        long todayBatches = productionBatchRepository.countByFactoryIdAndCreatedAtAfter(factoryId, todayStart);
        summary.put("totalBatches", todayBatches);
        // 进行中批次数
        long activeBatches = productionBatchRepository.countByFactoryIdAndStatus(
                factoryId, ProductionBatchStatus.IN_PROGRESS);
        summary.put("activeBatches", activeBatches);
        // 已完成批次数
        long completedBatches = productionBatchRepository.countByFactoryIdAndStatusAndCreatedAtAfter(
                factoryId, ProductionBatchStatus.COMPLETED, todayStart);
        summary.put("completedBatches", completedBatches);
        // 今日质检数
        long qualityInspections = qualityInspectionRepository.countByFactoryIdAndInspectionDateAfter(
                factoryId, todayStart.toLocalDate());
        summary.put("qualityInspections", qualityInspections);
        // 活跃告警数
        List<EquipmentAlert> activeAlerts = equipmentAlertRepository.findByFactoryIdAndStatusOrderByTriggeredAtDesc(
                factoryId, AlertStatus.ACTIVE);
        summary.put("activeAlerts", activeAlerts.size());
        // 工人数量统计
        long totalWorkers = userRepository.countByFactoryId(factoryId);
        summary.put("totalWorkers", totalWorkers);
        summary.put("onDutyWorkers", totalWorkers); // 简化处理，实际应从考勤记录获取
        overview.put("summary", summary);

        // ===== todayStats (今日统计) =====
        Map<String, Object> todayStats = new HashMap<>();
        todayStats.put("productionCount", todayBatches);
        todayStats.put("qualityCheckCount", qualityInspections);
        // 今日入库原材料数
        long materialReceived = materialBatchRepository.countByFactoryIdAndReceiptDateAfter(factoryId, todayStart);
        todayStats.put("materialReceived", materialReceived);
        todayStats.put("ordersCompleted", completedBatches);
        // 生产效率
        BigDecimal avgEfficiency = productionBatchRepository.calculateAverageEfficiency(factoryId, todayStart);
        todayStats.put("productionEfficiency", avgEfficiency != null ? avgEfficiency : BigDecimal.ZERO);
        todayStats.put("activeWorkers", totalWorkers);
        // 今日产量
        BigDecimal todayOutput = productionBatchRepository.calculateTotalOutputAfter(factoryId, todayStart);
        todayStats.put("todayOutputKg", todayOutput != null ? todayOutput : BigDecimal.ZERO);
        todayStats.put("totalBatches", todayBatches);
        todayStats.put("totalWorkers", totalWorkers);
        // 设备统计
        long totalEquipment = equipmentRepository.countByFactoryId(factoryId);
        long activeEquipment = equipmentRepository.countByFactoryIdAndStatus(factoryId, "active");
        todayStats.put("totalEquipment", totalEquipment);
        todayStats.put("activeEquipment", activeEquipment);
        overview.put("todayStats", todayStats);

        // ===== yesterdayStats (昨日统计，用于计算涨幅) =====
        LocalDateTime yesterdayStart = LocalDate.now().minusDays(1).atStartOfDay();
        LocalDateTime yesterdayEnd = LocalDate.now().atStartOfDay();
        Map<String, Object> yesterdayStats = new HashMap<>();
        // 昨日批次总数
        long yesterdayBatches = productionBatchRepository.countByFactoryIdAndCreatedAtBetween(
                factoryId, yesterdayStart, yesterdayEnd);
        yesterdayStats.put("totalBatches", yesterdayBatches);
        // 昨日产量
        BigDecimal yesterdayOutput = productionBatchRepository.calculateTotalOutputBetween(
                factoryId, yesterdayStart, yesterdayEnd);
        yesterdayStats.put("outputKg", yesterdayOutput != null ? yesterdayOutput : BigDecimal.ZERO);
        // 昨日完成批次
        long yesterdayCompleted = productionBatchRepository.countByFactoryIdAndStatusAndCreatedAtBetween(
                factoryId, ProductionBatchStatus.COMPLETED, yesterdayStart, yesterdayEnd);
        yesterdayStats.put("completedBatches", yesterdayCompleted);
        overview.put("yesterdayStats", yesterdayStats);

        // ===== kpi (关键绩效指标) =====
        Map<String, Object> kpi = new HashMap<>();
        kpi.put("productionEfficiency", avgEfficiency != null ? avgEfficiency : BigDecimal.ZERO);
        // 质量合格率
        BigDecimal monthlyYieldRate = productionBatchRepository.calculateAverageYieldRate(factoryId, monthStart);
        kpi.put("qualityPassRate", monthlyYieldRate != null ? monthlyYieldRate : BigDecimal.ZERO);
        // 设备利用率
        BigDecimal equipmentUtilization = totalEquipment > 0 ?
                BigDecimal.valueOf(activeEquipment * 100.0 / totalEquipment).setScale(2, RoundingMode.HALF_UP) :
                BigDecimal.ZERO;
        kpi.put("equipmentUtilization", equipmentUtilization);
        overview.put("kpi", kpi);

        // ===== alerts (告警状态) =====
        Map<String, Object> alerts = new HashMap<>();
        alerts.put("active", activeAlerts.size());
        alerts.put("status", activeAlerts.isEmpty() ? "normal" : "warning");
        overview.put("alerts", alerts);

        // ===== period =====
        overview.put("period", "today");

        // ===== 保留旧字段（向后兼容） =====
        overview.put("todayBatches", todayBatches);
        overview.put("inProgressBatches", activeBatches);
        BigDecimal monthlyOutput = productionBatchRepository.calculateMonthlyOutput(factoryId, monthStart);
        overview.put("monthlyOutput", monthlyOutput != null ? monthlyOutput : BigDecimal.ZERO);
        overview.put("monthlyYieldRate", monthlyYieldRate != null ? monthlyYieldRate : BigDecimal.ZERO);
        Long lowStockMaterials = materialBatchRepository.countLowStockMaterials(factoryId);
        overview.put("lowStockMaterials", lowStockMaterials != null ? lowStockMaterials : 0L);

        return overview;
    }
    public Map<String, Object> getProductionStatistics(String factoryId, String period) {
        Map<String, Object> statistics = new HashMap<>();
        LocalDateTime startDate;
        switch (period.toLowerCase()) {
            case "today":
                startDate = LocalDate.now().atStartOfDay();
                break;
            case "week":
                startDate = LocalDate.now().minusDays(7).atStartOfDay();
                break;
            case "month":
                startDate = LocalDate.now().withDayOfMonth(1).atStartOfDay();
                break;
            default:
                startDate = LocalDate.now().minusDays(30).atStartOfDay();
        }
        // 批次统计
        long totalBatches = productionBatchRepository.countByFactoryIdAndCreatedAtAfter(factoryId, startDate);
        statistics.put("totalBatches", totalBatches);
        // 已完成批次统计
        long completedBatches = productionBatchRepository.countByFactoryIdAndStatusAndCreatedAtAfter(
                factoryId,
                ProductionBatchStatus.COMPLETED,
                startDate);
        statistics.put("completedBatches", completedBatches);
        // 产量统计
        BigDecimal totalOutput = productionBatchRepository.calculateTotalOutputAfter(factoryId, startDate);
        statistics.put("totalOutput", totalOutput != null ? totalOutput : BigDecimal.ZERO);
        // 成本统计
        BigDecimal totalCost = productionBatchRepository.calculateTotalCostAfter(factoryId, startDate);
        statistics.put("totalCost", totalCost != null ? totalCost : BigDecimal.ZERO);
        // 效率统计
        BigDecimal avgEfficiency = productionBatchRepository.calculateAverageEfficiency(factoryId, startDate);
        statistics.put("averageEfficiency", avgEfficiency != null ? avgEfficiency : BigDecimal.ZERO);
        return statistics;
    }
    public Map<String, Object> getQualityDashboard(String factoryId) {
        Map<String, Object> dashboard = new HashMap<>();
        LocalDate today = LocalDate.now();
        LocalDate monthStart = today.withDayOfMonth(1);
        // 本月质检统计
        Map<String, Object> monthlyStats = getQualityStatistics(factoryId, monthStart, today);
        dashboard.put("monthlyStatistics", monthlyStats);

        // 将关键统计字段提升到顶层（用于E2E测试兼容性）
        dashboard.put("totalInspections", monthlyStats.getOrDefault("totalInspections", 0));
        dashboard.put("passedInspections", monthlyStats.getOrDefault("passedBatches", 0));
        dashboard.put("failedInspections", monthlyStats.getOrDefault("failedBatches", 0));
        dashboard.put("avgPassRate", monthlyStats.getOrDefault("averagePassRate", BigDecimal.ZERO));

        // 计算缺陷率 (defectRate = 100 - passRate)
        BigDecimal passRate = (BigDecimal) monthlyStats.getOrDefault("averagePassRate", BigDecimal.ZERO);
        BigDecimal defectRate = BigDecimal.valueOf(100).subtract(passRate);
        dashboard.put("defectRate", defectRate);
        dashboard.put("passRate", passRate);

        // 添加质量等级 (基于 passRate)
        String qualityGrade;
        if (passRate.compareTo(BigDecimal.valueOf(95)) >= 0) {
            qualityGrade = "A";
        } else if (passRate.compareTo(BigDecimal.valueOf(90)) >= 0) {
            qualityGrade = "B";
        } else if (passRate.compareTo(BigDecimal.valueOf(80)) >= 0) {
            qualityGrade = "C";
        } else {
            qualityGrade = "D";
        }
        dashboard.put("qualityGrade", qualityGrade);

        // 质量趋势
        List<Map<String, Object>> trends = getQualityTrends(factoryId, 30);
        dashboard.put("trends", trends);
        // 最新质检记录
        PageRequest pageRequest = new PageRequest();
        pageRequest.setPage(1);
        pageRequest.setSize(10);
        PageResponse<Map<String, Object>> recentInspections = getInspections(factoryId, null, pageRequest);
        dashboard.put("recentInspections", recentInspections.getContent());
        return dashboard;
    }
    public Map<String, Object> getEquipmentDashboard(String factoryId) {
        Map<String, Object> dashboard = new HashMap<>();
        // 设备监控
        List<Map<String, Object>> monitoring = getEquipmentMonitoring(factoryId);
        dashboard.put("monitoring", monitoring);
        // 设备统计
        long totalEquipments = equipmentRepository.countByFactoryId(factoryId);
        long runningEquipments = equipmentRepository.countByFactoryIdAndStatus(factoryId, "running");
        long maintenanceEquipments = equipmentRepository.countByFactoryIdAndStatus(factoryId, "maintenance");
        dashboard.put("totalEquipments", totalEquipments);
        dashboard.put("runningEquipments", runningEquipments);
        dashboard.put("maintenanceEquipments", maintenanceEquipments);
        // 平均利用率
        double avgUtilization = monitoring.stream()
                .mapToDouble(m -> (double) m.get("weeklyUtilizationRate"))
                .average()
                .orElse(0);
        dashboard.put("averageUtilization", avgUtilization);
        return dashboard;
    }
    public Map<String, Object> getAlertsDashboard(String factoryId) {
        Map<String, Object> alerts = new HashMap<>();
        List<Map<String, Object>> alertList = new ArrayList<>();
        // 低库存预警
        List<Object> lowStockMaterials = materialBatchRepository.findLowStockMaterials(factoryId);
        for (Object material : lowStockMaterials) {
            Map<String, Object> alert = new HashMap<>();
            alert.put("type", "LOW_STOCK");
            alert.put("level", "WARNING");
            alert.put("message", "原材料库存低");
            alert.put("data", material);
            alertList.add(alert);
        }
        // 过期预警
        List<MaterialBatch> expiringSoon = materialBatchRepository.findExpiringSoon(factoryId, LocalDate.now().plusDays(7));
        for (MaterialBatch batch : expiringSoon) {
            Map<String, Object> alert = new HashMap<>();
            alert.put("type", "EXPIRING");
            alert.put("level", "WARNING");
            alert.put("message", "原材料即将过期: " + batch.getBatchNumber());
            alert.put("data", batch);
            alert.put("expireDate", batch.getExpireDate());
            alertList.add(alert);
        }
        // 设备维护提醒
        List<FactoryEquipment> maintenanceDue = equipmentRepository.findMaintenanceDue(factoryId, LocalDate.now().minusDays(30));
        for (FactoryEquipment equipment : maintenanceDue) {
            Map<String, Object> alert = new HashMap<>();
            alert.put("type", "MAINTENANCE");
            alert.put("level", "INFO");
            alert.put("message", "设备需要维护: " + equipment.getEquipmentName());
            alert.put("data", equipment);
            alert.put("lastMaintenance", equipment.getLastMaintenanceDate());
            alertList.add(alert);
        }
        alerts.put("alerts", alertList);
        alerts.put("totalAlerts", alertList.size());
        return alerts;
    }
    public Map<String, Object> getTrendAnalysis(String factoryId, String metric, Integer days) {
        Map<String, Object> analysis = new HashMap<>();
        LocalDate endDate = LocalDate.now();
        LocalDate startDate = endDate.minusDays(days);
        List<Map<String, Object>> trendData = new ArrayList<>();
        for (LocalDate date = startDate; !date.isAfter(endDate); date = date.plusDays(1)) {
            Map<String, Object> dayData = new HashMap<>();
            dayData.put("date", date);
            switch (metric.toLowerCase()) {
                case "production":
                    BigDecimal dayOutput = productionBatchRepository.calculateDailyOutput(
                            factoryId, date.atStartOfDay(), date.atTime(23, 59, 59));
                    dayData.put("value", dayOutput != null ? dayOutput : BigDecimal.ZERO);
                    break;
                case "quality":
                    BigDecimal dayYieldRate = productionBatchRepository.calculateDailyYieldRate(
                            factoryId, date.atStartOfDay(), date.atTime(23, 59, 59));
                    dayData.put("value", dayYieldRate != null ? dayYieldRate : BigDecimal.ZERO);
                    break;
                case "cost":
                    BigDecimal dayCost = productionBatchRepository.calculateDailyCost(
                            factoryId, date.atStartOfDay(), date.atTime(23, 59, 59));
                    dayData.put("value", dayCost != null ? dayCost : BigDecimal.ZERO);
                    break;
                default:
                    dayData.put("value", BigDecimal.ZERO);
            }
            trendData.add(dayData);
        }
        analysis.put("metric", metric);
        analysis.put("period", days);
        analysis.put("data", trendData);
        return analysis;
    }
    // 辅助方法
    private Map<String, Object> convertInspectionToMap(QualityInspection inspection) {
        Map<String, Object> map = new HashMap<>();
        map.put("id", inspection.getId());
        map.put("productionBatchId", inspection.getProductionBatchId());
        map.put("inspectorId", inspection.getInspectorId());
        map.put("inspectionDate", inspection.getInspectionDate());
        map.put("sampleSize", inspection.getSampleSize());
        map.put("passCount", inspection.getPassCount());
        map.put("failCount", inspection.getFailCount());
        map.put("passRate", inspection.getPassRate());
        map.put("result", inspection.getResult());
        map.put("notes", inspection.getNotes());
        // 添加计算字段
        map.put("qualityGrade", inspection.getQualityGrade());
        map.put("defectRate", inspection.getDefectRate());
        return map;
    }
    private BigDecimal calculatePotentialSavings(ProductionBatch batch) {
        BigDecimal savings = BigDecimal.ZERO;
        // 如果良品率提升到95%能节省的成本
        if (batch.getYieldRate() != null && batch.getYieldRate().compareTo(new BigDecimal("95")) < 0) {
            BigDecimal currentWaste = batch.getDefectQuantity().multiply(batch.getUnitCost());
            BigDecimal targetWaste = batch.getActualQuantity().multiply(new BigDecimal("0.05")).multiply(batch.getUnitCost());
            savings = savings.add(currentWaste.subtract(targetWaste));
        }
        return savings;
    }

    // ========== AI智能成本分析（新版本） ==========

    /**
     * AI智能成本分析（带缓存优化 + 完整业务链数据）
     */
    @Override
    public Map<String, Object> analyzeWithAI(String factoryId, String batchId,
                                             String sessionId, String customMessage) {
        log.info("AI成本分析(增强版): factoryId={}, batchId={}, sessionId={}, customMessage={}",
                 factoryId, batchId, sessionId, customMessage != null ? "有追问" : "初次分析");

        // 1. 检查缓存（仅对初次分析且无自定义消息的情况使用缓存）
        if (sessionId == null && customMessage == null) {
            Map<String, Object> cachedResult = cacheService.getAIAnalysisCache(factoryId, batchId);
            if (cachedResult != null) {
                log.info("返回缓存的AI分析结果: factoryId={}, batchId={}", factoryId, batchId);
                cachedResult.put("fromCache", true);
                return cachedResult;
            }
        }

        // 2. 获取增强的批次成本数据（包含完整业务链数据）
        Map<String, Object> enhancedCostData = getEnhancedBatchCostAnalysis(factoryId, batchId);

        // 3. 调用AI服务
        Map<String, Object> aiResult = aiAnalysisService.analyzeCost(
            factoryId, batchId, enhancedCostData, sessionId, customMessage);

        // 4. 组合结果
        Map<String, Object> result = new HashMap<>();
        ProductionBatch batch = getBatchById(factoryId, batchId);

        result.put("batchId", batchId);
        result.put("batchNumber", batch.getBatchNumber());
        result.put("productName", batch.getProductName());
        result.put("enhancedData", enhancedCostData); // 使用增强数据
        result.put("aiAnalysis", aiResult.get("aiAnalysis"));
        result.put("sessionId", aiResult.get("sessionId"));
        result.put("messageCount", aiResult.get("messageCount"));
        result.put("success", aiResult.get("success"));
        result.put("fromCache", false);
        result.put("dataVersion", "enhanced_v2"); // 标记使用增强版数据

        // 如果AI调用失败，添加错误信息
        if (aiResult.containsKey("error")) {
            result.put("error", aiResult.get("error"));
            result.put("errorDetail", aiResult.get("errorDetail"));
        }

        // 5. 保存到缓存（仅对成功的初次分析）
        if (sessionId == null && customMessage == null && Boolean.TRUE.equals(aiResult.get("success"))) {
            cacheService.setAIAnalysisCache(factoryId, batchId, result);
        }

        log.info("AI成本分析完成(增强版): batchId={}, 包含原材料{}种, 设备{}台, 人工{}人次, 质检{}次",
                 batchId,
                 enhancedCostData.get("materialConsumptionCount"),
                 enhancedCostData.get("equipmentUsageCount"),
                 enhancedCostData.get("laborSessionCount"),
                 enhancedCostData.get("qualityInspectionCount"));

        return result;
    }

    /**
     * 获取AI对话历史
     */
    @Override
    public List<Map<String, Object>> getAISessionHistory(String sessionId) {
        log.info("获取AI会话历史: sessionId={}", sessionId);
        return aiAnalysisService.getSessionHistory(sessionId);
    }

    /**
     * 获取时间范围内的批次成本分析数据
     */
    @Override
    public List<Map<String, Object>> getTimeRangeBatchesCostAnalysis(
            String factoryId,
            java.time.LocalDateTime startDate,
            java.time.LocalDateTime endDate) {

        log.info("获取时间范围批次成本数据: factoryId={}, startDate={}, endDate={}",
                factoryId, startDate, endDate);

        // 1. 查询时间范围内的所有批次
        List<ProductionBatch> batches = productionBatchRepository
                .findByFactoryIdAndCreatedAtBetween(factoryId, startDate, endDate);

        log.info("查询到{}个批次", batches.size());

        // 2. 限制最大批次数量（避免Token消耗过大）
        final int MAX_BATCHES = 50;
        if (batches.size() > MAX_BATCHES) {
            log.warn("批次数量过多({})，限制为前{}个", batches.size(), MAX_BATCHES);
            batches = batches.subList(0, MAX_BATCHES);
        }

        // 3. 为每个批次获取增强的成本数据
        List<Map<String, Object>> batchesCostData = batches.stream()
                .map(batch -> {
                    try {
                        Map<String, Object> costData = getEnhancedBatchCostAnalysis(factoryId, batch.getId().toString());
                        // 添加批次基本信息
                        costData.put("batchNumber", batch.getBatchNumber());
                        costData.put("productName", batch.getProductName());
                        costData.put("status", batch.getStatus());
                        costData.put("createdAt", batch.getCreatedAt());
                        return costData;
                    } catch (Exception e) {
                        log.error("获取批次成本数据失败: batchId={}, error={}",
                                batch.getId(), e.getMessage());
                        return null;
                    }
                })
                .filter(data -> data != null)
                .collect(java.util.stream.Collectors.toList());

        log.info("成功获取{}个批次的成本数据", batchesCostData.size());

        return batchesCostData;
    }

    /**
     * 获取多个批次的对比分析数据
     */
    @Override
    public List<Map<String, Object>> getComparativeBatchesCostAnalysis(
            String factoryId,
            List<String> batchIds) {

        log.info("获取批次对比分析数据: factoryId={}, batchIds={}", factoryId, batchIds);

        // 1. 参数校验：确保批次数量在2-5之间
        if (batchIds == null || batchIds.size() < 2) {
            throw new IllegalArgumentException("至少需要2个批次进行对比分析");
        }
        if (batchIds.size() > 5) {
            throw new IllegalArgumentException("最多支持5个批次进行对比分析");
        }

        // 2. 为每个批次获取增强的成本数据
        List<Map<String, Object>> comparativeBatchesData = batchIds.stream()
                .map(batchId -> {
                    try {
                        // 获取批次基本信息
                        Long id = Long.parseLong(batchId);
                        ProductionBatch batch = productionBatchRepository.findByIdAndFactoryId(id, factoryId)
                                .orElseThrow(() -> new RuntimeException("批次不存在: " + batchId));

                        // 获取增强的成本数据
                        Map<String, Object> costData = getEnhancedBatchCostAnalysis(factoryId, batchId);

                        // 添加批次基本信息
                        costData.put("batchId", batch.getId());
                        costData.put("batchNumber", batch.getBatchNumber());
                        costData.put("productName", batch.getProductName());
                        costData.put("status", batch.getStatus());
                        costData.put("createdAt", batch.getCreatedAt());

                        log.info("成功获取批次{}的成本数据", batchId);
                        return costData;

                    } catch (Exception e) {
                        log.error("获取批次成本数据失败: batchId={}, error={}", batchId, e.getMessage());
                        return null;
                    }
                })
                .filter(data -> data != null)
                .collect(java.util.stream.Collectors.toList());

        // 3. 校验：确保所有批次数据都获取成功
        if (comparativeBatchesData.size() < 2) {
            throw new RuntimeException("至少需要2个有效批次数据才能进行对比分析");
        }

        log.info("成功获取{}个批次的对比数据", comparativeBatchesData.size());

        return comparativeBatchesData;
    }

    /**
     * 获取指定时间范围内的批次成本摘要数据（用于周报告/月报告）
     * 返回轻量级的批次成本摘要，不包含详细的业务链数据
     */
    @Override
    public List<Map<String, Object>> getWeeklyBatchesCost(
            String factoryId,
            java.time.LocalDateTime startDate,
            java.time.LocalDateTime endDate) {

        log.info("获取周报告批次成本数据: factoryId={}, startDate={}, endDate={}",
                 factoryId, startDate, endDate);

        // 1. 查询时间范围内的所有批次
        List<ProductionBatch> batches = productionBatchRepository
                .findByFactoryIdAndCreatedAtBetween(factoryId, startDate, endDate);

        log.info("查询到{}个批次", batches.size());

        // 2. 为每个批次构建成本摘要（轻量级，不包含详细业务链数据）
        return batches.stream()
                .map(batch -> {
                    Map<String, Object> batchCostSummary = new HashMap<>();

                    // 基本信息
                    batchCostSummary.put("batchId", batch.getId());
                    batchCostSummary.put("batchNumber", batch.getBatchNumber());
                    batchCostSummary.put("productName", batch.getProductName());
                    batchCostSummary.put("status", batch.getStatus());
                    batchCostSummary.put("createdAt", batch.getCreatedAt());

                    // 成本汇总
                    Map<String, Object> costSummary = new HashMap<>();
                    costSummary.put("materialCost", batch.getMaterialCost() != null ? batch.getMaterialCost() : BigDecimal.ZERO);
                    costSummary.put("laborCost", batch.getLaborCost() != null ? batch.getLaborCost() : BigDecimal.ZERO);
                    costSummary.put("equipmentCost", batch.getEquipmentCost() != null ? batch.getEquipmentCost() : BigDecimal.ZERO);
                    costSummary.put("otherCost", batch.getOtherCost() != null ? batch.getOtherCost() : BigDecimal.ZERO);
                    costSummary.put("totalCost", batch.getTotalCost() != null ? batch.getTotalCost() : BigDecimal.ZERO);
                    costSummary.put("unitCost", batch.getUnitCost() != null ? batch.getUnitCost() : BigDecimal.ZERO);
                    batchCostSummary.put("costSummary", costSummary);

                    // 生产指标
                    batchCostSummary.put("actualQuantity", batch.getActualQuantity() != null ? batch.getActualQuantity() : BigDecimal.ZERO);
                    batchCostSummary.put("yieldRate", batch.getYieldRate() != null ? batch.getYieldRate() : BigDecimal.ZERO);
                    batchCostSummary.put("efficiency", batch.getEfficiency() != null ? batch.getEfficiency() : BigDecimal.ZERO);

                    return batchCostSummary;
                })
                .collect(java.util.stream.Collectors.toList());
    }

    /**
     * AI服务健康检查
     */
    @Override
    public Map<String, Object> checkAIServiceHealth() {
        log.info("检查AI服务健康状态");
        return aiAnalysisService.healthCheck();
    }

    // ========== 批次员工分配 ==========

    /**
     * 分配员工到批次
     */
    @Override
    @Transactional
    public List<Map<String, Object>> assignWorkersToBatch(String factoryId, Long batchId,
                                                           List<Long> workerIds, Long assignedBy, String notes) {
        log.info("分配员工到批次: factoryId={}, batchId={}, workerIds={}, assignedBy={}",
                factoryId, batchId, workerIds, assignedBy);

        // 1. 验证批次存在且状态正确
        ProductionBatch batch = productionBatchRepository.findByIdAndFactoryId(batchId, factoryId)
                .orElseThrow(() -> new ResourceNotFoundException("批次不存在: " + batchId));

        // 兼容 PRODUCING 和 IN_PROGRESS，以及 PLANNING 和 PLANNED
        ProductionBatchStatus status = batch.getStatus();
        if (status != ProductionBatchStatus.IN_PROGRESS &&
            status != ProductionBatchStatus.PRODUCING &&
            status != ProductionBatchStatus.PLANNED &&
            status != ProductionBatchStatus.PLANNING) {
            throw new BusinessException("只有计划中或进行中的批次可以分配员工");
        }

        // 2. 验证分配人存在
        User assigner = userRepository.findById(assignedBy)
                .orElseThrow(() -> new ResourceNotFoundException("分配人不存在: " + assignedBy));

        List<Map<String, Object>> results = new ArrayList<>();
        LocalDateTime now = LocalDateTime.now();

        for (Long workerId : workerIds) {
            try {
                // 3. 验证员工存在且属于该工厂
                User worker = userRepository.findById(workerId)
                        .orElseThrow(() -> new ResourceNotFoundException("员工不存在: " + workerId));

                if (!factoryId.equals(worker.getFactoryId())) {
                    throw new BusinessException("员工不属于该工厂: " + workerId);
                }

                // 4. 检查员工是否已分配到该批次
                Optional<BatchWorkSession> existing = batchWorkSessionRepository
                        .findActiveByBatchIdAndEmployeeId(batchId, workerId);

                if (existing.isPresent()) {
                    Map<String, Object> result = new HashMap<>();
                    result.put("workerId", workerId);
                    result.put("workerName", worker.getFullName() != null ? worker.getFullName() : worker.getUsername());
                    result.put("success", false);
                    result.put("message", "员工已分配到该批次");
                    results.add(result);
                    continue;
                }

                // 5. 创建 BatchWorkSession 记录
                BatchWorkSession session = new BatchWorkSession();
                session.setBatchId(batchId);
                session.setEmployeeId(workerId);
                session.setCheckInTime(now);
                session.setAssignedBy(assignedBy);
                session.setStatus(BatchWorkSession.Status.ASSIGNED);
                session.setNotes(notes);
                session.setCreatedAt(now);

                batchWorkSessionRepository.save(session);

                Map<String, Object> result = new HashMap<>();
                result.put("workerId", workerId);
                result.put("workerName", worker.getFullName() != null ? worker.getFullName() : worker.getUsername());
                result.put("sessionId", session.getId());
                result.put("checkInTime", now);
                result.put("success", true);
                result.put("message", "分配成功");
                results.add(result);

                log.info("成功分配员工 {} 到批次 {}", workerId, batchId);

            } catch (Exception e) {
                Map<String, Object> result = new HashMap<>();
                result.put("workerId", workerId);
                result.put("success", false);
                result.put("message", e.getMessage());
                results.add(result);
                log.error("分配员工失败: workerId={}, error={}", workerId, e.getMessage());
            }
        }

        return results;
    }

    /**
     * 员工完成批次工作（签出）
     */
    @Override
    @Transactional
    public Map<String, Object> workerCheckout(String factoryId, Long batchId, Long workerId,
                                               Integer workMinutes, String notes) {
        log.info("员工签出: factoryId={}, batchId={}, workerId={}", factoryId, batchId, workerId);

        // 1. 查找活跃的工作会话
        BatchWorkSession session = batchWorkSessionRepository
                .findActiveByBatchIdAndEmployeeId(batchId, workerId)
                .orElseThrow(() -> new ResourceNotFoundException("未找到该员工在该批次的活跃工作记录"));

        LocalDateTime now = LocalDateTime.now();

        // 2. 计算工作时长
        int actualWorkMinutes;
        if (workMinutes != null && workMinutes > 0) {
            actualWorkMinutes = workMinutes;
        } else if (session.getCheckInTime() != null) {
            actualWorkMinutes = (int) ChronoUnit.MINUTES.between(session.getCheckInTime(), now);
        } else {
            actualWorkMinutes = 0;
        }

        // 3. 计算人工成本（假设每小时50元）
        BigDecimal hourlyRate = new BigDecimal("50.00");
        BigDecimal laborCost = hourlyRate
                .multiply(BigDecimal.valueOf(actualWorkMinutes))
                .divide(BigDecimal.valueOf(60), 2, RoundingMode.HALF_UP);

        // 4. 更新工作会话
        session.setCheckOutTime(now);
        session.setWorkMinutes(actualWorkMinutes);
        session.setLaborCost(laborCost);
        session.setStatus(BatchWorkSession.Status.COMPLETED);
        if (notes != null && !notes.isEmpty()) {
            session.setNotes(session.getNotes() != null ?
                    session.getNotes() + "\n" + notes : notes);
        }
        session.setUpdatedAt(now);

        batchWorkSessionRepository.save(session);

        // 5. 获取员工信息
        User worker = userRepository.findById(workerId).orElse(null);

        Map<String, Object> result = new HashMap<>();
        result.put("sessionId", session.getId());
        result.put("workerId", workerId);
        result.put("workerName", worker != null ? (worker.getFullName() != null ? worker.getFullName() : worker.getUsername()) : "未知");
        result.put("checkInTime", session.getCheckInTime());
        result.put("checkOutTime", now);
        result.put("workMinutes", actualWorkMinutes);
        result.put("laborCost", laborCost);
        result.put("status", session.getStatus());
        result.put("success", true);
        result.put("message", "签出成功");

        log.info("员工签出成功: workerId={}, workMinutes={}, laborCost={}",
                workerId, actualWorkMinutes, laborCost);

        return result;
    }

    /**
     * 获取批次的员工列表
     */
    @Override
    public List<Map<String, Object>> getBatchWorkers(String factoryId, Long batchId) {
        log.info("获取批次员工列表: factoryId={}, batchId={}", factoryId, batchId);

        // 验证批次存在
        productionBatchRepository.findByIdAndFactoryId(batchId, factoryId)
                .orElseThrow(() -> new ResourceNotFoundException("批次不存在: " + batchId));

        // 获取批次的所有工作会话
        List<BatchWorkSession> sessions = batchWorkSessionRepository.findByBatchIdWithEmployees(batchId);

        return sessions.stream().map(session -> {
            Map<String, Object> workerInfo = new HashMap<>();
            workerInfo.put("sessionId", session.getId());
            workerInfo.put("workerId", session.getEmployeeId());

            User employee = session.getEmployee();
            if (employee != null) {
                workerInfo.put("workerName", employee.getFullName() != null ? employee.getFullName() : employee.getUsername());
                workerInfo.put("employeeNumber", employee.getUsername());
                workerInfo.put("departmentName", employee.getDepartment());
            } else {
                workerInfo.put("workerName", "未知");
            }

            workerInfo.put("checkInTime", session.getCheckInTime());
            workerInfo.put("checkOutTime", session.getCheckOutTime());
            workerInfo.put("workMinutes", session.getWorkMinutes());
            workerInfo.put("laborCost", session.getLaborCost());
            workerInfo.put("status", session.getStatus());

            // 状态显示文字
            String statusText = "未知";
            if (session.getStatus() != null) {
                switch (session.getStatus()) {
                    case BatchWorkSession.Status.ASSIGNED: statusText = "已分配"; break;
                    case BatchWorkSession.Status.WORKING: statusText = "工作中"; break;
                    case BatchWorkSession.Status.COMPLETED: statusText = "已完成"; break;
                    case BatchWorkSession.Status.CANCELLED: statusText = "已取消"; break;
                }
            }
            workerInfo.put("statusText", statusText);

            User assigner = session.getAssigner();
            workerInfo.put("assignedBy", session.getAssignedBy());
            workerInfo.put("assignerName", assigner != null ? (assigner.getFullName() != null ? assigner.getFullName() : assigner.getUsername()) : null);
            workerInfo.put("assignedAt", session.getCreatedAt());
            workerInfo.put("notes", session.getNotes());

            return workerInfo;
        }).collect(Collectors.toList());
    }

    /**
     * 取消员工批次分配
     */
    @Override
    @Transactional
    public Map<String, Object> cancelWorkerAssignment(String factoryId, Long batchId, Long workerId) {
        log.info("取消员工分配: factoryId={}, batchId={}, workerId={}", factoryId, batchId, workerId);

        // 查找活跃的工作会话
        BatchWorkSession session = batchWorkSessionRepository
                .findActiveByBatchIdAndEmployeeId(batchId, workerId)
                .orElseThrow(() -> new ResourceNotFoundException("未找到该员工在该批次的活跃工作记录"));

        // 更新状态为取消
        session.setStatus(BatchWorkSession.Status.CANCELLED);
        session.setUpdatedAt(LocalDateTime.now());
        batchWorkSessionRepository.save(session);

        Map<String, Object> result = new HashMap<>();
        result.put("sessionId", session.getId());
        result.put("workerId", workerId);
        result.put("success", true);
        result.put("message", "取消分配成功");

        log.info("取消员工分配成功: workerId={}", workerId);

        return result;
    }
}
