"""Generate mock restaurant Silver-layer data for parity-gate testing.

Produces self-contained SQL files that ``psql`` can apply to either
``smartbi_db`` (test env) or ``smartbi_prod_db`` (prod env) to seed a
fictitious factory (default ``R_TEST_MOCK``) so the parity gate can run
end-to-end without real customer data.

Scope (minimum viable for T6.6 Sub-A production endpoint testing):

* ``dim_store``  — 3 stores per chain (FK target for fact_pos_transaction)
* ``fact_pos_transaction`` — the M3 proxy query target
* ``fact_pos_item`` — optional, gated by ``--include-items`` flag

Excluded for now (out of M3-proxy parity scope):

* ``fact_pos_review`` — needed for Sub-B quality complaint rate
* ``fact_wastage_record`` — needed for Sub-B quality wastage rate
* ``dim_chain`` / ``restaurant_chain_catalog`` — assume the row already
  exists per V20260511_02 seed; this generator just references factory_id

Default scale (per Steve's MO):
  1 chain × 3 stores × 30 days × 50 txn/day = ~4500 transactions
  + 5 items/txn (when --include-items) = ~22500 fact_pos_item rows

Edge cases baked in:

* 1 of 3 stores ("empty store") gets 0 transactions over the period
* ~5% of transactions have NULL ``table_no`` (tests C3 fallback path)
* ~3% of transactions have NULL ``gross_amount`` (tests null-aggregation)
* 1 specific date in the middle has 0 transactions across all stores
  (tests day-count edge)

The generator is deterministic (seeded random) so output is stable
across runs — important for snapshot/regression of the generator itself.
"""
from __future__ import annotations

import argparse
import datetime
import os
import random
from pathlib import Path
from typing import List, Optional


# Deterministic ingredients for the synthetic data.
_DEFAULT_CHAIN = "MOCK_CHAIN"
_DEFAULT_FACTORY = "R_TEST_MOCK"
_DEFAULT_STORES = 3
_DEFAULT_DAYS = 30
_DEFAULT_TXN_PER_DAY = 50
_DEFAULT_ITEMS_PER_TXN = 5

_PRODUCTS = [
    (1, "宫保鸡丁", 38.00),
    (2, "麻婆豆腐", 28.00),
    (3, "鱼香肉丝", 32.00),
    (4, "回锅肉", 42.00),
    (5, "干煸豆角", 26.00),
    (6, "酸辣土豆丝", 18.00),
    (7, "夫妻肺片", 48.00),
    (8, "口水鸡", 36.00),
]

_ORDER_TYPES = ["堂食", "外卖", "自提"]
_CHANNELS = ["美团", "抖音", "自点", "饿了么"]


def _sql_str(s: Optional[str]) -> str:
    """SQL-quote a string or return NULL."""
    if s is None:
        return "NULL"
    return "'" + str(s).replace("'", "''") + "'"


def _sql_num(x: Optional[float], scale: int = 2) -> str:
    """SQL-quote a numeric value or return NULL."""
    if x is None:
        return "NULL"
    return f"{x:.{scale}f}"


def generate_sql(
    factory_id: str = _DEFAULT_FACTORY,
    chain_code: str = _DEFAULT_CHAIN,
    n_stores: int = _DEFAULT_STORES,
    days: int = _DEFAULT_DAYS,
    txn_per_day: int = _DEFAULT_TXN_PER_DAY,
    items_per_txn: int = _DEFAULT_ITEMS_PER_TXN,
    include_items: bool = False,
    seed: int = 42,
    start_date: Optional[datetime.date] = None,
) -> str:
    """Return a complete SQL script that seeds dim_store + fact_pos_transaction.

    The script wraps everything in BEGIN/COMMIT and deletes any existing
    rows for ``factory_id`` first so it is idempotent.
    """
    rng = random.Random(seed)
    if start_date is None:
        start_date = datetime.date(2026, 1, 1)

    out: List[str] = []
    out.append(
        f"-- Mock parity-gate seed for factory_id={factory_id}\n"
        f"-- Generated by scripts/parity-gate/mock_data_generator.py\n"
        f"-- Scale: {n_stores} stores × {days} days × {txn_per_day} txn/day = "
        f"~{n_stores * days * txn_per_day} target transactions (1 empty store excluded)\n"
        f"-- Seed: {seed} (deterministic)\n"
    )
    out.append("BEGIN;")
    out.append(
        "-- RLS context: parity_gate runs as super-user; if you're a per-tenant\n"
        f"-- session, run `SET app.factory_id = '{factory_id}';` first.\n"
        f"SET app.factory_id = '{factory_id}';"
    )

    # Cleanup (idempotent).
    out.append(f"DELETE FROM fact_pos_item WHERE factory_id = '{factory_id}';")
    out.append(f"DELETE FROM fact_pos_transaction WHERE factory_id = '{factory_id}';")
    out.append(f"DELETE FROM dim_store WHERE factory_id = '{factory_id}';")

    # ── dim_store ──
    out.append("\n-- dim_store: 3 stores; first store is 'empty store' (0 txns)")
    store_rows = []
    for i in range(n_stores):
        name = f"{chain_code}-Store-{chr(65 + i)}"  # A, B, C
        brand = chain_code
        city = "Shanghai"
        province = "Shanghai"
        region = "East China"
        store_rows.append(
            f"({_sql_str(factory_id)}, {_sql_str(name)}, {_sql_str(brand)}, "
            f"{_sql_str(city)}, {_sql_str(province)}, {_sql_str(region)})"
        )
    out.append(
        "INSERT INTO dim_store (factory_id, name, brand, city, province, region) VALUES"
    )
    out.append(",\n".join(store_rows) + ";")

    # Grab back the store_ids in a temp variable.  Postgres lets us do
    # "INSERT ... RETURNING" but we need them in subsequent INSERTs — easier
    # to look them up via a sub-select per row.
    out.append(
        "\n-- Cache store_ids for transaction insertion. We use a sub-select\n"
        "-- on (factory_id, name) per row since the BIGSERIAL ids aren't\n"
        "-- deterministic across re-runs."
    )

    # ── fact_pos_transaction ──
    # Skip first store (empty store) — only stores 1..(n-1) get transactions.
    # Reserve one mid-period date with zero transactions (day-count edge).
    skip_date = start_date + datetime.timedelta(days=days // 2)
    txn_rows: List[str] = []
    bill_idx = 0
    for day_offset in range(days):
        d = start_date + datetime.timedelta(days=day_offset)
        if d == skip_date:
            continue
        for store_idx in range(1, n_stores):  # skip store 0 (empty)
            store_name = f"{chain_code}-Store-{chr(65 + store_idx)}"
            for _ in range(txn_per_day):
                bill_idx += 1
                bill_no = f"MOCK-{bill_idx:08d}"
                # Random transaction details.
                hour = rng.randint(11, 21)
                minute = rng.randint(0, 59)
                ts = datetime.datetime.combine(
                    d, datetime.time(hour, minute, rng.randint(0, 59))
                )
                # ~3% of transactions have NULL gross_amount
                if rng.random() < 0.03:
                    gross = None
                    net = None
                    actual = None
                else:
                    gross = rng.uniform(80.0, 480.0)
                    net = gross * rng.uniform(0.85, 1.0)
                    actual = net
                discount = (gross - net) if (gross is not None and net is not None) else None
                customer_count = rng.randint(1, 6)
                avg_per_capita = (net / customer_count) if (net and customer_count) else None
                # ~5% have NULL table_no
                table_no = None if rng.random() < 0.05 else f"T{rng.randint(1, 30):02d}"
                order_type = rng.choice(_ORDER_TYPES)
                channel = rng.choice(_CHANNELS)
                item_count = rng.randint(1, 8)
                has_discount = discount is not None and discount > 0.01

                # Build VALUES tuple. store_id comes from sub-select.
                values = (
                    f"((SELECT store_id FROM dim_store WHERE factory_id = {_sql_str(factory_id)} "
                    f"AND name = {_sql_str(store_name)}), "
                    f"{_sql_str(factory_id)}, "
                    "'excel', "
                    f"{_sql_str(bill_no)}, "
                    f"{_sql_str(str(d))}, "
                    f"{_sql_str(ts.isoformat(sep=' '))}, "
                    f"{_sql_num(gross)}, "
                    f"{_sql_num(discount)}, "
                    f"{_sql_num(net * 0.06 if net else None)}, "  # tax_amount (mock 6%)
                    f"{_sql_num(net)}, "
                    f"{_sql_num(actual)}, "
                    f"{customer_count}, "
                    f"{_sql_num(avg_per_capita)}, "
                    f"{_sql_str(table_no)}, "
                    f"{_sql_str(order_type)}, "
                    f"{_sql_str(channel)}, "
                    f"{item_count}, "
                    f"{str(has_discount).lower()})"
                )
                txn_rows.append(values)

    out.append(
        f"\n-- fact_pos_transaction: {len(txn_rows)} bills "
        f"(store 0 empty; date {skip_date} skipped)"
    )
    # PG VALUES list — chunk per 500 rows to avoid hitting parser limits.
    chunk_size = 500
    cols = (
        "(store_id, factory_id, source_type, source_bill_no, date, time, "
        "gross_amount, discount_amount, tax_amount, net_amount, actual_receive, "
        "customer_count, avg_per_capita, table_no, order_type, channel_origin, "
        "item_count, has_discount)"
    )
    for i in range(0, len(txn_rows), chunk_size):
        chunk = txn_rows[i : i + chunk_size]
        out.append(f"INSERT INTO fact_pos_transaction {cols} VALUES")
        out.append(",\n".join(chunk) + ";")

    # ── fact_pos_item (optional) ──
    if include_items:
        out.append(
            f"\n-- fact_pos_item: ~{items_per_txn} items per transaction; "
            "uses sub-select on (factory_id, source_bill_no) for fk."
        )
        item_rows: List[str] = []
        for tx_i in range(1, bill_idx + 1):
            bill_no = f"MOCK-{tx_i:08d}"
            n_items = rng.randint(1, items_per_txn)
            for _ in range(n_items):
                pid, pname, base_price = rng.choice(_PRODUCTS)
                qty = rng.randint(1, 3)
                unit_price = base_price * rng.uniform(0.95, 1.05)
                amount = qty * unit_price
                # 2% of items have product_id = NULL (parser miss).
                product_id = "NULL" if rng.random() < 0.02 else str(pid)
                source_raw = f"#{pname}#_{qty}份*{unit_price:.0f}"
                vals = (
                    f"((SELECT id FROM fact_pos_transaction WHERE factory_id = {_sql_str(factory_id)} "
                    f"AND source_bill_no = {_sql_str(bill_no)}), "
                    f"{_sql_str(factory_id)}, "
                    f"{product_id}, "
                    f"{qty:.3f}, "
                    f"{unit_price:.2f}, "
                    f"{amount:.2f}, "
                    f"{_sql_str(source_raw)})"
                )
                item_rows.append(vals)

        item_cols = (
            "(transaction_id, factory_id, product_id, qty, unit_price, amount, source_item_raw)"
        )
        for i in range(0, len(item_rows), chunk_size):
            chunk = item_rows[i : i + chunk_size]
            out.append(f"INSERT INTO fact_pos_item {item_cols} VALUES")
            out.append(",\n".join(chunk) + ";")

    out.append("\nCOMMIT;")
    out.append(
        f"\n-- Verification queries:\n"
        f"-- SELECT factory_id, COUNT(*) AS bill_count, COUNT(DISTINCT store_id) AS stores,\n"
        f"--        COUNT(DISTINCT date) AS days\n"
        f"-- FROM fact_pos_transaction WHERE factory_id = '{factory_id}'\n"
        f"-- GROUP BY factory_id;"
    )

    return "\n".join(out) + "\n"


def write_mock_sql(
    output_dir: str,
    factory_id: str = _DEFAULT_FACTORY,
    timestamp: Optional[str] = None,
    **kwargs,
) -> Path:
    """Write the SQL to ``<output_dir>/<factory_id>/<timestamp>/seed.sql``.

    Returns the path written.
    """
    if timestamp is None:
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    out_path = Path(output_dir) / factory_id / timestamp / "seed.sql"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    sql = generate_sql(factory_id=factory_id, **kwargs)
    out_path.write_text(sql, encoding="utf-8")
    return out_path


def main():
    p = argparse.ArgumentParser(description="Mock restaurant Silver seed generator.")
    p.add_argument("--factory", default=_DEFAULT_FACTORY)
    p.add_argument("--chain", default=_DEFAULT_CHAIN)
    p.add_argument("--stores", type=int, default=_DEFAULT_STORES)
    p.add_argument("--days", type=int, default=_DEFAULT_DAYS)
    p.add_argument("--txn-per-day", type=int, default=_DEFAULT_TXN_PER_DAY)
    p.add_argument(
        "--include-items",
        action="store_true",
        help="Also generate fact_pos_item rows (default off — heavy).",
    )
    p.add_argument("--seed", type=int, default=42)
    p.add_argument(
        "--output-dir",
        default="mock_data",
        help="Base dir; writes <dir>/<factory>/<timestamp>/seed.sql",
    )
    p.add_argument(
        "--start-date",
        default=None,
        help="YYYY-MM-DD; defaults to 2026-01-01.",
    )
    args = p.parse_args()

    start_date = (
        datetime.date.fromisoformat(args.start_date) if args.start_date else None
    )

    path = write_mock_sql(
        output_dir=args.output_dir,
        factory_id=args.factory,
        chain_code=args.chain,
        n_stores=args.stores,
        days=args.days,
        txn_per_day=args.txn_per_day,
        include_items=args.include_items,
        seed=args.seed,
        start_date=start_date,
    )
    size = os.path.getsize(path)
    print(f"Wrote {path} ({size:,} bytes)")
    print(
        f"Apply with: psql -d smartbi_db -f {path}   (test env)\n"
        f"      or:   psql -d smartbi_prod_db -f {path}   (prod env)"
    )


if __name__ == "__main__":
    main()
