import sys
NL = chr(10)
lines = []
def L(s): lines.append(s)

# The complete audit script
L("// tests/canvas-v3/audit-4-browser-explore.mjs")
L("// Canvas V3 UX Audit 4")
L("import { chromium } from 'playwright';")
L("import fs from 'fs';")
L("import path from 'path';")
L("const BASE_URL='http://139.196.165.140:8086';")
L("const SSDIR='tests/canvas-v3/screenshots/audit-4';")
L("fs.mkdirSync(SSDIR,{recursive:true});")
L("function log(m){console.log(m);}")
L("function step(m){console.log('');console.log('>>> '+m);}")
L("async function ss(page,name){const f=path.join(SSDIR,name+'.png');await page.screenshot({path:f,fullPage:true}).catch(()=>{});log('  Screenshot: '+f);return f;}")
L("async function waitVue(page,t=12000){await page.waitForFunction(()=>document.body.innerText.trim().length>50,{timeout:t}).catch(()=>{});await page.waitForTimeout(1500);}")
L("async function mkCtx(browser){const ctx=await browser.newContext({viewport:{width:1440,height:900},locale:'zh-CN'});await ctx.route('**/fonts.googleapis.com/**',r=>r.fulfill({status:200,body:''}));await ctx.route('**/fonts.gstatic.com/**',r=>r.fulfill({status:200,body:''}));return ctx;}")
L("async function doLogin(page,u,pw){")
L("  await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:20000});")
L("  await page.waitForSelector('input[type=text],input[placeholder]',{timeout:12000}).catch(()=>{});")
L("  await page.waitForTimeout(1000);")
L("  const uInput=await page.locator('input[type=text]').first();")
L("  if(uInput)await uInput.fill(u);")
L("  await page.fill('input[type=password]',pw);")
L("  const loginBtn=await page.locator('button').filter({hasText:/\u767b/}).first();")
L("  if(loginBtn)await loginBtn.click();")
L("  await page.waitForURL(url=>!url.includes('login'),{timeout:12000}).catch(()=>{});")
L("  await page.waitForTimeout(1000);")
L("  const ok=!page.url().includes('login');")
L("  log('  Login '+u+': '+(ok?'OK':'FAIL')+' -> '+page.url());")
L("  return ok;")
L("}" )

with open('tests/canvas-v3/audit-4-browser-explore.mjs','w',encoding='utf-8') as f:
    f.write(NL.join(lines)+NL)
print('header written:', len(lines))
