/**
 * 搜索关键词管理 - 表格配置
 */
export const tableOption = {
  border: true,
  index: true,
  indexLabel: "序号",
  stripe: true,
  menuAlign: "center",
  align: "center",
  menuWidth: 200,
  menuType: "text",
  searchShow: true,
  excelBtn: true,
  printBtn: true,
  editBtn: false,
  delBtn: false,
  addBtn: false,
  viewBtn: false,
  searchMenuSpan: 6,
  column: [
    {
      label: "关键词",
      prop: "keyword",
      search: true,
      width: 200,
      fixed: true,
    },
    {
      label: "搜索次数",
      prop: "searchCount",
      sortable: true,
      width: 120,
    },
    {
      label: "无结果次数",
      prop: "noResultCount",
      sortable: true,
      width: 120,
    },
    {
      label: "商家数量",
      prop: "uniqueMerchants",
      sortable: true,
      width: 120,
    },
    {
      label: "状态",
      prop: "status",
      type: "select",
      search: true,
      width: 120,
      slot: true,
      dicData: [
        { label: "待处理", value: 0 },
        { label: "已匹配", value: 1 },
        { label: "已通知", value: 2 },
        { label: "已忽略", value: 3 },
      ],
    },
    {
      label: "热门",
      prop: "isHot",
      width: 80,
      slot: true,
    },
    {
      label: "首次搜索",
      prop: "firstSearchTime",
      sortable: true,
      width: 160,
    },
    {
      label: "最后搜索",
      prop: "lastSearchTime",
      sortable: true,
      width: 160,
    },
    {
      label: "匹配商品",
      prop: "matchedProductIds",
      width: 120,
      slot: true,
    },
  ],
};
